# -*- coding: utf-8 -*-
"""Universita dell'Edilizia - generatori pack Robotica, Domotica, Impiantistica."""
import json, os, shutil, zipfile

ROOT = os.path.abspath(os.path.dirname(__file__))
UNI = os.path.join(ROOT, "UNIVERSITA_EDILIZIA")

def s(cat, nome, descrizione, tecnologia, applicazioni, vantaggi, limiti, costi, casi, normative, note):
    return {"categoria": cat, "nome": nome, "descrizione": descrizione,
            "tecnologia": tecnologia, "applicazioni": applicazioni,
            "vantaggi": vantaggi, "limiti": limiti, "costi_e_economia": costi,
            "casi_real_world": casi, "normative": normative, "note_cantiere": note}

# ===========================================================================
# PACK 1 — ROBOTICA EDILIZIA
# ===========================================================================
ROBOTICA = [
s("Stampa 3D edilizia","Stampante 3D per calcestruzzo (extrusion)",
 "Stampanti a braccio/portalino che estrudono strati di calcestruzzo rapido per pareti portanti.",
 "Extrusion layer-by-layer; mix accelerati (additivi acceleratori, spesso geopolimeri); controllo CNC 3-6 assi.",
 "Villette monopiano, case popolari, uffici, pareti e murature in loco.",
 "Riduzione manodopera (-50/-80% sulla muratura), velocità (10-100 m2/giorno), minor spreco, geometrie libere.",
 "Richiede progettazione ad hoc (DfAM); superfici grezze da rifinire; normativa ancora in sviluppo; capital cost elevato.",
 "Macchina 300k-1,5M€; costo parete stampata 30-60% in meno rispetto a muratura tradizionale su grandi volumi.",
 "COBOD BOD2 (usata da GE, PERI, HeidelbergCement); ICON Vulcan; Apis Cor; CyBe; WASP Crane.",
 "EILCO/ISO/ASTM in definizione; in Italia CNR-DT 125 (prime linee guida stampa 3D).",
 "La stampa 3D sostituisce la muratura, NON la struttura: la platea, le travi e la copertura restano tradizionali o prefabbricate."),
s("Stampa 3D edilizia","Stampa 3D case intere (Icon Vulcan)",
 "Sistema mobile di stampa intero edificio in ~7-14 giorni.",
 "Extrusion su binari/scala mobile; mix proprietario 'Lavacrete'.",
 "Housing sociale, emergency housing, edilizia residenziale USA.",
 "Tempo di cantiere drasticamente ridotto; 2-4 addetti per casa; costo materiale basso.",
 "Geometrie a parete semplice; reti impianti da progettare prima (canaline integrate).",
 "Casa stampata: 4.000-10.000 € in materiali + macchina; totale 30-50% sotto mercato USA.",
 "ICON: comunità in Texas (East 17th), progetti NASA per habitat lunari.",
 "Normativa edilizia locale, ASTM in corso; codici anti-sismici da adattare.",
 "Prevedere nel modello BIM la posa di canaline per impianti prima della stampa delle pareti."),
s("Stampa 3D edilizia","Stampa 3D con terra cruda e geopolimeri",
 "Stampa con materiali di terra locali, rifiuti industriali attivati, geopolimeri a basso carbonio.",
 "Leganti geopolimerici (metacaolino, scorie attivate) o terra stabilizzata; estrusione a bassa energia.",
 "Architetture sostenibili, padiglioni, edilizia rurale, esteri emergenti.",
 "Impronta carbonica molto bassa; uso di rifiuti e terra locale; niente cemento.",
 "Resistenza meccanica inferiore al cls; vulnerabilità all'acqua senza protezioni; ricerca ancora attiva.",
 "Materiale 5-20 €/m3 (terra locale) contro 60-120 €/m3 di cls; macchina COBOD/wasp da 50-200k€.",
 "TECLA (Mario Cucinella + WASP); case in India/Africa con stampanti low cost.",
 "Linee guida sperimentali; per opere strutturali serve validazione accademica e prove su campioni.",
 "Ideale per strutture non portanti, recinzioni, padiglioni e murature di riempimento verificate sismicamente."),
s("Stampa 3D edilizia","Inchiostri (mix) per stampa 3D",
 "I mix stampabili: requisiti di pompa-bilità, apertura di staglio, costruibilità (buildability).",
 "Cls con aggregati fini, acceleratori, fibrorinforzo; viscosità regolata da additivi cellulosa/argille.",
 "Qualsiasi progetto di stampa 3D.",
 "Possibilità di mix custom (leggeri, isolanti, fibrati); integrazione di fibre per anti-sismico.",
 "Catena di fornitura e certificazione del mix ancora limitata; richiede laboratorio di dosaggio.",
 "Mix stampabile: +10-30% sul cls ordinario; sviluppo mix dedicato: 5-20k€.",
 "Mix di HeidelbergCement, CEMEX D.fab, mix CNR per ENEA.",
 "Prove di costruibilità e reologia (EN 12350 adattate); nessuna norma armonizzata specifica.",
 "Testare sempre il mix con prova di crollo a torre (slump flow a torre) prima del cantiere."),
s("Stampa 3D edilizia","Stampa 3D di metalli (WAAM e SLM)",
 "Prototipi e componenti strutturali in acciaio/alluminio stampati in 3D.",
 "Wire Arc Additive Manufacturing (WAAM) e Selective Laser Melting (SLM).",
 "Nodi strutturali complessi, ponti pedonali, architetture parametriche.",
 "Forme impossibili con lamiere; personalizzazione di massa; spreco quasi nullo di metallo.",
 "Costo orario macchina elevato; dimensioni limitate; verifica strutturale su-sito complessa.",
 "WAAM 100-500 €/kg; SLM 300-1.000 €/kg; competitivo solo per forme estreme o prototipi.",
 "Ponte MX3D in acciaio ad Amsterdam; nodi per Renzo Piano Building Workshop.",
 "EN ISO/ASTM 52900; verifica a fatica e saldabilità secondo Eurocodici.",
 "Per il progettista: pensare al metallo stampato come getto metallico, non come laminato."),
s("Robot muratori","SAM100 (Semi-Automated Mason)",
 "Robot collaborativo che posa mattoni pieni/forati con malta, con operaio alimentatore.",
 "Braccio robotico 6 assi + nastro alimentazione; posizionamento laser 1 mm.",
 "Facciate in laterizio, murature di tamponamento, rivestimenti a faccia vista.",
 "Produttività 3.000+ mattoni/turno (6 volte l'umano); qualità costante del giunto.",
 "Serve operaio dedicato all'alimentazione; non posa angoli e aperture (resta manuale).",
 "Acquisto 400-600k$; rientro indicativo 3-5 anni su grandi cantieri di facciata.",
 "Construction Robotics SAM100: usato su cantieri Walmart, scuole USA.",
 "NESSUNA norma robotica specifica; rispetto Direttiva macchine 2006/42/CE.",
 "Adatto a grandi superfici rettilinee: su piccoli cantieri residenziali non ripaga."),
s("Robot muratori","Hadrian X (FBR)",
 "Robot mobile su cingoli che posa blocchi forati adesivi (no malta) interi muri dall'esterno.",
 "Pala caricatrice + testa posa blocchi + colla poliuretanica strutturale; precisione sub-millimetrica.",
 "Villette, villette a schiera, muri di recinzione e contenimento.",
 "Posa 200+ blocchi/ora anche di notte; opera a distanza di sicurezza; nessuna impalcatura.",
 "Limitato a geometrie compatibili con i blocchi; ecosistema blocchi dedicati.",
 "Macchina multi-milione $; contratti licensing/licenza per costruttori.",
 "FBR (Fastbrick Robotics) in Australia/USA; case pilota in Florida.",
 "Certificazioni locali su colla e blocchi; verifica statica a cura del progettista.",
 "Segnale del futuro: la muratura diventa posa di 'lego industriali', il progettista modella a blocchi."),
s("Robot muratori","Robot posa piastrelle e pavimenti",
 "Robot semi-automatici per la posa di piastrelle grandi formato e levigatura.",
 "Ventose + braccio + laser leveling; applicazione colla a pettine automatica.",
 "Aeroporti, centri commerciali, grandi pavimentazioni continue.",
 "Produttività 3-5x; qualità di planarità costante; riduzione malattie muscolo-scheletriche.",
 "Setup e messa a punto iniziale lenti; non gestisce tagli e particolari.",
 "Robot TileRobot/SAM: 150-400k€; rientro su >5.000 m2.",
 "Robot della Università di Monash (Hadrian 'piastrellista'); Tile laying robots in Cina.",
 "Direttiva macchine; accordi collettivi su sicurezza in cantiere.",
 "Su grandi superfici il robot conviene; su bagni e cucine resta l'artigiano."),
s("Robot demolizione","Robot demolizione telecomandati (Brokk)",
 "Mini escavatori demolitori telecomandati con frantumi e bracci idraulici.",
 "Elettrici/diesel, telecomando radio, attrezzature multipla (frantumo, pinza, fresa).",
 "Demolizioni interne, ambienti confinati, centrali nucleari, tunnel, cantieri urbani.",
 "Operatore lontano dal pericolo; accesso a spazi stretti; minor vibrazione e polvere.",
 "Portata e raggio limitati; costo orario elevato; serve manutentore formato.",
 "Noleggio 1.500-4.000 €/giorno; acquisto 60-300k€.",
 "Brokk, Husqvarna DXR: usati a Chernobyl, metropolitane, demolizioni ospedaliere.",
 "Direttiva macchine; valutazione rumore/polvere; amianto: procedure D.Lgs 81/08.",
 "Per demolizioni selezionate e interne è quasi sempre più sicuro e spesso più economico dell'escavatore grande."),
s("Robot demolizione","Robot carotatura e taglio",
 "Carotatrici e seghe robotizzate per tagli di precisione in cls e roccia.",
 "Utensili diamantati motorizzati, guida meccanica o robotica.",
 "Fori per impianti, tagli per rinforzi, aperture, demolizioni controllate.",
 "Precisione millimetrica; nessuna fatica per l'operatore; continuità di lavoro.",
 "Polvere e acqua di raffreddamento da gestire; consumo utensili diamantati.",
 "Carotatrice robotizzata 15-60k€; utensile diamantato 50-300 €/m di taglio.",
 "Hilti, Tyrolit robot systems per tagli su dighe e ponti.",
 "Direttiva macchine; ATEX per ambienti con polveri esplosive.",
 "Il taglio robotizzato evita microfessurazioni: fondamentale prima di incollaggi FRP."),
s("Macchine teleoperate","Escavatori e mezzi pesanti teleoperati",
 "Buldozer, escavatori e dumper comandati a distanza per cantieri pericolosi.",
 "Telecomando radio/5G + telecamere + LiDAR; oppure driver-assist (semi-autonomia).",
 "Frane, discariche, cave, cantieri con rischio instabilità, ambiente radioattivo.",
 "Eliminazione del rischio uomo-macchina; lavoro continuo su più turni.",
 "Latenza e banda critiche; percezione ridotta rispetto alla cabina.",
 "Kit retrofit teleoperato: 30-150k€; macchina nuova autonoma: +20-40%.",
 "Komatsu/Hitachi autonomous trucks nelle miniere (Rio Tinto); teleoperazione nelle centrali nucleari (JTEKT).",
 "Direttiva macchine + UNI per macchine da cantiere (EN 474).",
 "La teleoperazione è il gradino prima dell'autonomia: investire in reti 5G private del cantiere."),
s("Droni","Droni rilievo fotogrammetrico",
 "Rilievo 3D da drone con foto georiferite per mappatura di cantiere e patrimonio.",
 "UAV multirotore/fixed-wing + fotogrammetria SfM (Structure from Motion) + GCP o PPK.",
 "Rilievo di terreni, monitoraggio avanzamento lavori, patrimonio architettonico, lastrico solare.",
 "Rilievo 10-50 ha/giorno; nessun ponteggio; ortofoto e nuvole di punti cm-level.",
 "Dipendenza da meteo; autorizzazioni ENAC; non penetra la vegetazione fitta.",
 "Drone professionale 5-30k€; software elaborazione 2-10k€/anno; costo rilievo: 0,5-5 €/ha vs rilievo tradizionale 10x.",
 "DJI Phantom/M300 + Pix4D/Agisoft; usati da tutti i general contractor.",
 "Regolamento UE 2019/945 (droni), ENAC; privacy per immagini.",
 "Ogni rilievo ripetibile nel tempo crea il 'diario fotografico metrico' del cantiere: oro in caso di contenzioso."),
s("Droni","Droni ispezione facciate, ponti e strutture alte",
 "Ispezione visiva e termografica di superfici verticali e orizzontali con sensori ottici/IR.",
 "UAV con zoom ottico 30x, termocamera FLIR, luci; volo ravvicinato programmato.",
 "Ispezioni di ponti, torri, pannelli fotovoltaici, gru, antenne, facciate vetro.",
 "Niente piattaforme aeree o funi nella maggior parte dei casi; ispezione 5-10x più veloce.",
 "Batteria 20-40 min; normativa volo in area urbana; attesa condizioni meteo.",
 "Servizio ispezione: 300-1.500 €/giornata; risparmio 40-70% vs ponteggio.",
 "CyberHawk, Skydio per ponti; ispezioni FV termografiche con DJI M300.",
 "Regolamento droni UE specific/SORA; ENAC; coordinamento con Ente gestore infrastruttura.",
 "Documentare ogni anomalia con foto georiferita: la relazione diventa base di computo per manutenzione."),
s("Droni","Drone LiDAR e rilievo boschi/infrastrutture",
 "Rilievo laser a scansione dal drone per vegetazione e geometrie complesse.",
 "LiDAR UAV (Velodyne/Ouster) + IMU + GNSS; 100-400 pt/m2.",
 "Rilievi in foreste, linee elettriche, frane, scavi e cave, modelli digitali di terreno.",
 "Penetra la vegetazione (rimbalzi multipli); accuratezza 3-10 cm anche senza GCP.",
 "Peso/batteria: 10-25 min volo; costo sensore; elaborazione specialistica.",
 "Sistema LiDAR drone: 40-150k€; costo rilievo bosco: 1-5 €/ha.",
 "YellowScan, RIEGL miniVUX; adozione da ferrovie e TSO elettrici.",
 "COME per fotogrammetria; sicurezza laser classe.",
 "Il DTM da LiDAR è la base per la modellazione idraulica e geotecnica: investire qui ripaga in progettazione."),
s("Droni","Droni logistica di cantiere",
 "Consegna di piccoli materiali, strumenti e campioni via drone.",
 "UAV cargo con winch/cassetti; percorso pre-programmato; carico 2-20 kg.",
 "Cantieri estesi, isole, aree montane, consegna attrezzature urgenti tra gru e baraccamenti.",
 "Taglio dei tempi di attesa; nessun mezzo di superficie; sicurezza del personale.",
 "Autonomia limitata con carico; regolamento di volo; costo/km ancora alto.",
 "Drone cargo: 20-200k€; consegna 5-30 € vs 50-150 € di mezzo+personale.",
 "Wing (Alphabet) per consegne; EHang cargo; test in cantieri minerari.",
 "Regolamento droni UE; assicurazioni; certificazione classe specifica.",
 "Oggi conviene per emergenze e siti remoti; la scala arriverà con regolamentazione U-space."),
s("Wearable","Esoscheletri per operai",
 "Strutture indossabili attive (motore) o passive (molle) che aiutano a sollevare e tenere posizioni.",
 "Motori elettrici/batteria o sistemi passivi a elastomeri; sensori IMU.",
 "Movimentazione sacchi, posa in quota, sbattimento prolungato, logistica magazzino.",
 "Riduzione affaticamento 30-60%; minor infortuni muscolo-scheletrici (50% degli infortuni edili).",
 "Peso 3-8 kg; caldo in estate; adozione culturale; manutenzione batterie.",
 "Esoscheletro passivo 3-10k€; attivo 20-50k€; rientro su riduzione infortuni e assenze.",
 "SuitX/Dephy; esoscheletri usati da Ford, Delta, in prova da Webuild sui cantieri.",
 "Direttiva DPI; valutazione ergonomica D.Lgs 81/08 allegato XXXIII.",
 "Il miglior esoscheletro è quello che l'operaio accetta: coinvolgerlo nella scelta del modello."),
s("Robot swarm","Robot collettivi e modulari (TERMES, swarms)",
 "Gruppi di piccoli robot autonomi che costruiscono cooperando, ispirati alle termiti.",
 "Swarm robotics; comunicazione stigmergica; moduli di costruzione standard.",
 "Ricerca, ambienti estremi, costruzione spaziale, strutture di emergenza.",
 "Robustezza (nessun singolo punto critico); parallelizzazione; accesso a zone pericolose.",
 "TRL basso (3-5); scalabilità non dimostrata in edilizia reale.",
 "Prototipi accademici; costo sistema sperimentale 50-200k€.",
 "TERMES (Harvard), swarms ETH Zurich; NASA JPL per habitat lunari.",
 "Nessuna normativa; etica e sicurezza collettive in studio.",
 "Da monitorare: è la direzione di lungo periodo, non una tecnologia da cantiere 2026."),
s("Off-site automation","Prefabbricazione robotizzata (off-site, DfMA)",
 "Fabbriche con robot saldatori, carroponte CNC e linee automatizzate per componenti edilizi.",
 "Saldatura robotica, taglio CNC, montaggio automatico pannelli 3D, linee di produzione.",
 "Strutture in acciaio, facciate unitizzate, pannelli parete, bagni monoblocco, moduli completi.",
 "Qualità industriale; cantiere 30-70% più veloce; meno sprechi e meno personale in quota.",
 "Investimento impianto pesante; progettazione BIM obbligatoria; trasporto dei moduli.",
 "Impianto prefabbricazione: 5-50M€; risparmio cantiere 10-20% del totale.",
 "Katerra (fallimento da studiare), Kleusberg, Lindbäcks, Sekisui House; bagni monoblocco Caleffi.",
 "Marcatura CE componenti; EN 1090 per acciaio; DfMA come metodo progettuale.",
 "La prefabbricazione robotizzata è la robotica che FUNZIONA oggi: chi progetta per DfMA vince su tempi e qualità."),
s("Automazione armature","Legatura e piegatura barre automatizzata",
 "Macchine automatiche per piegare e legare reti e barre d'armatura.",
 "Bender CNC a doppia testa, robot legatori a filo (tie-wire robots).",
 "Centri di lavorazione armature, grandi opere, gabbie di pali e travi.",
 "Produttività 5-10x; precisione di piega costante; meno malattie professionali.",
 "Batch minimo per ripagare; programmazione CAD delle forme.",
 "Bender CNC: 100-500k€; robot legatore: 40-100k€.",
 "Schnell, EVG, Progress: standard nelle fabbriche di prefabbricati.",
 "Direttiva macchine; UNI EN 10080 acciai.",
 "Chi armava a mano 3 addetti, con la macchina ne serve 1: riallocare la manodopera sulla posa."),
s("BIM-to-Robot","Layout robotizzato dal modello BIM",
 "Robot che tracciano e posano da soli layout di cantiere e componenti partendo dal BIM.",
 "Import IFC/CSV; robot mobile con spray/penna/laser per segnare pareti e solai.",
 "Tracciamento pareti, posa travi laser, verifica posa contro modello (scan-to-BIM).",
 "Zero errori di misura; aggiornamento continuo as-built; meno rilievi manuali.",
 "Richiede BIM affidabile e coordinato; superfici pulite e accessibili.",
 "Dusty Robotics FieldPrinter: noleggio/servizio 3-10k€/mese su cantieri grandi.",
 "Dusty (USA) su cantieri di data center; HP SitePrint per layout elettrico/idraulico.",
 "Nessuna; integra processo BIM ISO 19650.",
 "Stampare il layout sul solaio prima delle partizioni cambia il cantiere: niente misure a nastro."),
s("Strumentazione","Stazioni totali robotiche e laser tracker",
 "Strumenti geodetici a guida automatica per il posizionamento ad alta precisione.",
 "Stazione totale motorizzata (TS), laser tracker, livelli digitali; prismi robotici.",
 "Posa strutture in acciaio, monitoraggi, piloni, binari, prefabbricati di precisione.",
 "Precisione 1-2 mm su centinaia di metri; un solo operatore; misure continue.",
 "Vista libera richiesta; umidità/polvere degradano; costo strumento.",
 "Stazione totale robotica: 15-50k€; laser tracker: 60-150k€.",
 "Leica TS16, Trimble S7; standard nei cantieri di ponte e grattacielo.",
 "UNI geodesia; tracciati secondo norma (es. UNI 7317).",
 "Fondamentale abbinare il rilievo continuo al modello: la stazione totale 'guida' la posa come un GPS del cantiere."),
s("AI vision","Computer vision e AI per la sicurezza di cantiere",
 "Telecamere intelligenti che rilevano DPI mancanti, zone pericolo e vicinanza a mezzi.",
 "Deep learning su stream video edge/cloud; alert in tempo reale; dashboard HSE.",
 "Sicurezza cantieri, monitoraggio accessi, conteggio presenze, analisi near-miss.",
 "Sicurezza proattiva 24/7; dati oggettivi per audit; riduzione incidenti dimostrata 20-40%.",
 "Privacy (lavoratori sorvegliati); falsi positivi; qualità installazione.",
 "SaaS 2-15 €/camera/mese + hardware; progetto cantiere: 5-50k€.",
 "Everguard.ai, SmartVid.io (acquisita da Oracle); adozione da general contractor USA.",
 "GDPR + accordi sindacali; DPIA obbligatoria per videosorveglianza lavoratori.",
 "Usare l'AI come coach, non come spia: comunicare lo scopo preventivo o il progetto fallisce culturalmente."),
s("Digital twin","Gemello digitale di cantiere e opera",
 "Modello vivo dell'opera aggiornato in tempo reale da sensori, rilievi e avanzamento.",
 "BIM + IoT + scan periodici (drone/laser scanner) + dashboard e simulazioni.",
 "Cantieri complessi, gestione patrimonio, smart buildings, manutenzione predittiva.",
 "Decisioni su dati reali; simulazioni prima di intervenire; consegna as-built garantita.",
 "Costo integrazione; disciplina nel mantenere il modello aggiornato.",
 "Piattaforma digital twin: 20-200k€/anno + sensoristica.",
 "Singapore Virtual Singapore; Heathrow; cantiere di Grand Paris Express.",
 "ISO 19650; nessuna norma unica ancora.",
 "Un digital twin abbandonato è peggio di niente: serve un data manager di cantiere dedicato."),
s("Middleware","ROS e middleware robotici in edilizia",
 "Piattaforme software open per comandare robot eterogenei in cantiere.",
 "ROS/ROS2, MQTT, OPC-UA; integrazione flotte miste (droni+mezzi+sensori).",
 "Cantieri pilota, ricerca, automazione impianti di produzione prefabbricati.",
 "Standard aperto; enorme ecosistema; riuso di algoritmi già sviluppati.",
 "Richiede competenze software in azienda; affidabilità da industrializzare.",
 "Software gratuito; competenze: 60-120k€/anno di un ingegnere robotico.",
 "ROS-Industrial; progetti Horizon Europe per costruzione robotizzata.",
 "Nessuna; buone pratiche open source.",
 "Per un'impresa edile media: iniziare da MQTT+OPC-UA per i sensori, ROS solo se si sviluppa robotica propria."),
s("Sicurezza robotica","Normativa sicurezza robotica in cantiere",
 "Come rendere conforme un cantiere con robot e macchine automatizzate.",
 "Direttiva macchine 2006/42/CE; ISO 10218 (robot industriali); ISO/TS 15066 (cobot); UNI EN 474 (macchine da cantiere).",
 "Qualsiasi adozione robotica: dal robot demolitore al cobot muratore.",
 "Quadro chiaro di responsabilità; valutazione rischi aggiornata; LAVORATORI FORMATI.",
 "Normativa frammentata; regolamenti nazionali da armonizzare; interpretazioni locali.",
 "Costo compliance: valutazione+formazione 5-30k€ per cantiere robotizzato.",
 "Cantieri nord-europei come riferimento; protocolli ENEL/Webuild per robot in opera.",
 "D.Lgs 81/08 + allegato V macchine; Direttiva macchine (nuova 2023/1230).",
 "Regola d'oro: il robot entra in cantiere solo dopo la valutazione del RSPP e con percorso pedonale segregato."),
s("Economia","Economia e ROI della robotica edilizia",
 "Quando la robotica ripaga: il quadro economico realistico.",
 "Analisi costo-orario robotico vs manodopera; produttività; qualità; sicurezza.",
 "Decisione investimenti di imprese, direzioni lavori, committenti.",
 "Sui grandi volumi e lavori ripetitivi il ROI è 1-3 anni; su piccoli lavori tradizionali non ripaga mai.",
 "Macchine sottoutilizzate sono perdita; mancanza di manutentori; obsolescenza software.",
 "Robot muratore: rientro 2-4 anni a >15.000 m2 di facciata; drone rilievo: rientro immediato (<3 mesi).",
 "Dati da McKinsey Global Institute e da casi FBR/Construction Robotics pubblicati.",
 "Nessuna; è analisi gestionale.",
 "Criterio pratico: comprare robot dove c'è (1) ripetitività, (2) volume, (3) carenza di manodopera qualificata."),
s("Criticità","Limiti, barriere e rischi della robotica edilizia",
 "La verità critica: cosa NON funziona ancora nella costruzione robotizzata.",
 "Analisi critica: tecnologia immatura, skill gap, normativa, cultura, economics.",
 "Formazione del LLM al pensiero critico (spirito critico richiesto dall'utente).",
 "Evita entusiasmi ingiustificati; guida investimenti razionali; riconosce il valore dell'artigianato.",
 "Rischio di hype: molti progetti dimostrativi non scalano mai.",
 "Il fallimento di Katerra (1,6 miliardi $ bruciati) insegna: la tecnologia senza processo uccide.",
 "Casi studio: Katerra, Arrivo, molte startup di stampa 3D scomparse dal 2018.",
 "Nessuna; è cultura manageriale.",
 "Regola per il LLM: la robotica vince sul RIPETITIVO e PERICOLOSO; l'umano vince sul VARIO e CREATIVO: il cantiere del futuro è ibrido."),
]

# ===========================================================================
# PACK 2 — DOMOTICA E BUILDING AUTOMATION
# ===========================================================================
DOMOTICA = [
s("Architettura","Architettura di un impianto domotico",
 "Come è organizzato un impianto domotico: sensori, attuatori, bus, supervisione, cloud.",
 "Topologia a livelli: campo (sensori/attuatori) -> controllo (attuatori bus/KNX) -> gestione (supervisore/HMI) -> cloud/servizi.",
 "Qualsiasi edificio: residenziale, terziario, industriale, hospitality.",
 "Struttura modulare ed espandibile; ogni livello può evolvere indipendentemente.",
 "Progettazione sbagliata = rigetto costoso; serve un progettista qualificato (tra cui certificazione KNX Partner).",
 "Impianto base appartamento: 3-8k€; villa completa: 10-40k€; edificio terziario: 20-100 €/m2.",
 "Standard KNX Association per l'architettura a 3 livelli.",
 "L.46/90 (criteri CEN); CEI 64-8 per la parte elettrica.",
 "Prima regola: definire gli scenari di vita PRIMA dei protocolli: la tecnologia serve il comfort, non il contrario."),
s("BUS cablato","KNX/EIB (bus europeo)",
 "Il protocollo bus cablato più diffuso al mondo per edilizia residenziale e terziaria.",
 "Bus a 2 fili (TP) 9600 baud; telegrammi; indirizzi fisici/logici; ETS come software di progettazione.",
 "Controllo luce, clima, tapparelle, sicurezza, energia in edifici nuovi e retrofit.",
 "Affidabilità certificata (decenni di esercizio); interoperabilità tra 500+ produttori; standard aperto (ISO/IEC 14543-3).",
 "Costo cavo e componenti superiore al wireless; progettazione ETS specializzata.",
 "Attuatore KNX: 80-300 €; sensore: 50-250 €; software ETS: licenza 200-1.000 €.",
 "Ospedali, stadi, aeroporti, hotel di lusso; ~500 milioni di dispositivi installati.",
 "EN 50090 / ISO-IEC 14543-3; marchio KNX.",
 "In retrofit il bus viaggia spesso sul 230V esistente (KNX Powerline) o su wireless KNX."),
s("BUS cablato","KNX Secure (cybersecurity)",
 "Estensione KNX per cifrare i telegrammi e autenticare i dispositivi.",
 "Crittografia AES-128 CCM; meccanismi IP Secure e Data Secure; chiavi per edificio.",
 "Edifici sensibili (banche, ospedali, hotel luxury), chiunque voglia proteggere l'impianto da accessi remoti.",
 "Conformità alla cybersecurity dell'impianto; requisito sempre più richiesto dagli appalti pubblici.",
 "Retrofit complesso su impianti vecchi; gestione chiavi disciplinata.",
 "+10-20% sui componenti; nessun cambio architetturale.",
 "Mandato sempre più frequente in gare d'appalto europee.",
 "IEC 62443 (cybersecurity industriale) come riferimento.",
 "Abilitare KNX Secure in fase di messa in servizio, non dopo: la migrazione a cantiere finito costa il triplo."),
s("BUS edifici terziari","BACnet",
 "Protocollo per l'automazione di edifici terziari (HVAC, centrali termiche, BMS).",
 "BACnet/IP e BACnet MS/TP; oggetti standard (analog input, binary output...); BIBB per interoperabilità.",
 "Uffici, ospedali, scuole, centri commerciali: supervisione impianti e contabilizzazione.",
 "Standard ISO (ISO 16484-5); scambio dati tra marche diverse di centraline e BMS.",
 "Più complesso del KNX lato residenziale; orientato al tecnico impiantista.",
 "Gateway BACnet: 300-1.500 €; integrazione in BMS: 2-10k€ per edificio.",
 "Metasys (JCI), Desigo (Siemens), Niagara Framework come supervisor.",
 "ISO 16484; EN di prodotto per componenti.",
 "Per il LLM: BACnet parla 'impianti', KNX parla 'stanze': gli edifici intelligenti usano entrambi con un gateway."),
s("BUS industriale","Modbus",
 "Protocollo seriale/TCP semplice per controllori, inverter, centrali misura.",
 "Modbus RTU (seriale RS485) e Modbus TCP; registro a 16 bit; master/slave.",
 "Fotovoltaico (inverter), contabilizzazione calore, gruppi elettrogeni, strumentazione.",
 "Semplicità assoluta; supportato da qualunque dispositivo industriale; gratuito.",
 "Nessuna sicurezza nativa; nessun modello dati condiviso (vendor-specific).",
 "Integrazione: quasi gratuita; gateway Modbus-KNX/BACnet: 150-800 €.",
 "Qualunque inverter FV, qualunque contatore di energia.",
 "Nessuna certificazione formale; IEC 61158 come famiglia fieldbus.",
 "Mai esporre Modbus su Internet aperto: tunnel VPN o gateway con autenticazione."),
s("BUS cablato","LonWorks / TP",
 "Piattaforma di controllo di rete per automazione edilizia (storica).",
 "Neuron Chip; Free Topology; LonTalk.",
 "Trasporti, tunnel, illuminazione pubblica, alcuni BMS.",
 "Robustezza in ambienti difficili; topologia libera.",
 "Ecosistema in declino rispetto a KNX/BACnet; competenze rare.",
 "Componenti costosi e di nicchia.",
 "Tunnel stradali, aeroporti storici.",
 "ISO/IEC 14908.",
 "Menzionare per cultura: i nuovi progetti scelgono KNX o BACnet."),
s("Wireless","Zigbee",
 "Mesh radio a basso consumo per sensori e attuatori domotici.",
 "IEEE 802.15.4, 2,4 GHz, mesh auto-riparante, profili applicativi (ZHA, ZLL).",
 "Sensori ambiente, prese smart, illuminazione, chiavi intelligenti.",
 "Bassissimo consumo (batterie anni); mesh estendibile; dispositivi economici.",
 "Interferenze Wi-Fi sulla stessa banda; qualità variabile tra marche.",
 "Dispositivo: 10-60 €; hub: 50-150 €.",
 "Philips Hue, IKEA Tradfri, Samsung SmartThings, Aqara.",
 "Zigbee Alliance -> Connectivity Standards Alliance.",
 "Per un LLM: Zigbee è perfetto per il RETROFIT senza demolizioni: vale l'oro in ristrutturazioni."),
s("Wireless","Z-Wave",
 "Protocollo radio sub-GHz per domotica residenziale (mesh).",
 "863-870 MHz (Europa); mesh fino a 4 hop; bassa potenza.",
 "Sicurezza, sensori, attuatori in contesti residenziali.",
 "Banda libera da congestione Wi-Fi; segnale che attraversa pareti meglio del 2,4 GHz.",
 "Ecosistema più piccolo di Zigbee; hub dedicato.",
 "Dispositivo: 20-80 €; hub: 100-250 €.",
 "Fibaro, Aeotec, Somfy (parzialmente).",
 "Z-Wave Alliance; certificazione obbligatoria.",
 "In edilizia europea ha perso terreno verso Zigbee e Matter, ma resta solido in sicurezza."),
s("Wireless","Matter e Thread",
 "Lo standard unificato 2022+ per la smart home: interoperabilità tra Google, Apple, Amazon, Samsung.",
 "Matter (applicativo) su Thread (rete mesh IP a basso consumo) o Wi-Fi.",
 "Nuovi impianti e aggiornamenti smart home: un solo ecosistema per ogni dispositivo.",
 "FINALMENTE: un dispositivo Matter funziona con tutti gli assistenti; commissioning semplice.",
 "Dispositivi ancora non esaustivi; certificazione in corso per molte categorie.",
 "Dispositivi Matter: 15-100 €; border router integrato in altoparlanti/hub esistenti.",
 "Google Nest, Apple HomeKit, Amazon Echo, SmartThings convergenti su Matter.",
 "Standard CSA (Connectivity Standards Alliance).",
 "Per nuovi impianti residenziali: preferire dispositivi Matter-certified per non restare imprigionati in un ecosistema."),
s("Wireless","Wi-Fi domotico",
 "Dispositivi smart direttamente sulla rete Wi-Fi dell'edificio.",
 "Wi-Fi 2,4/5/6 GHz; cloud del produttore; app dedicata.",
 "Piccoli impianti, singoli ambienti, B&B, retrofit leggero.",
 "Nessun hub aggiuntivo; prezzo basso; app immediata.",
 "Consumo elevato (batterie durano poco); congestione rete; dipendenza dal cloud esterno.",
 "Dispositivo: 10-50 €.",
 "Sonoff, Shelly, Tuya/Smart Life (migliaia di prodotti).",
 "CEI 64-8 per l'impianto elettrico.",
 "Il cloud esterno è un rischio continuità: se il produttore chiude, i dispositivi muoiono. Preferire dispositivi con API locali."),
s("Wireless","Bluetooth Mesh (illuminazione)",
 "Rete mesh Bluetooth per illuminazione smart professionale.",
 "Bluetooth Mesh su 2,4 GHz; modelli publish/subscribe; provisioning via app.",
 "Uffici, retail, hotel: illuminazione + localizzazione indoor (asset tracking).",
 "Una sola rete per luce e localizzazione dei badge/carrelli; installazione semplice.",
 "Ecosistema in crescita ma inferiore a KNX/DALI; distanza hop limitata.",
 "Componenti: 15-80 €/punto luce.",
 "Signify Interact, Silicon Labs reference designs.",
 "Bluetooth SIG Mesh specifications.",
 "La killer feature è il posizionamento indoor: retail e ospedali lo adottano per questo."),
s("Gateway","Gateway e integrazione multprotocollo",
 "Come far parlare insieme KNX, BACnet, Modbus, Zigbee, Matter, cloud.",
 "Gateway hardware (es. home server, edge gateway) + software (Niagara, Home Assistant, Node-RED).",
 "Qualsiasi edificio con sottosistemi eterogenei (tipico: BMS + domotica + FV + sicurezza).",
 "Un unico cruscotto; logiche condivise; dati unificati per energia e manutenzione.",
 "Punto critico: se il gateway cade, l'integrazione cade; ridondanza e manutenzione.",
 "Gateway edge: 300-3.000 €; licenze software: 0-5k€/anno.",
 "Home Assistant (open source), Tridum Niagara (professionale), Node-RED (prototipi).",
 "Nessuna specifica; IEC 62443 per la sicurezza.",
 "Regola: il gateway deve 'spegnere bene' — in assenza di cloud e gateway, luce e tapparelle devono funzionare comunque."),
s("Sensori","Sensoristica domotica",
 "Gli occhi dell'impianto: presenza, movimento, luce, temperatura, umidità, CO2, qualità aria.",
 "PIR, mm-wave (radar 60 GHz), luxmetri, sonde NTC, NDIR per CO2, eCO2/VOC.",
 "Controllo illuminazione, clima, sicurezza, VMC, scenari anti-allagamento/gas.",
 "mm-wave rileva presenza anche ferma (uffici, anziani); CO2 guida la VMC con dati reali.",
 "Falsi positivi PIR in ambienti con animali; taratura iniziale lunga.",
 "Sensore PIR: 10-50 €; mm-wave: 30-80 €; CO2 NDIR: 60-150 €.",
 "Dispositivi KNX/Aqara/Shelly per ogni fascia.",
 "Marcatura CE; CEI EN per compatibilità elettromagnetica.",
 "I sensori sono il 30% del comfort e l'80% dei malfunzionamenti percepiti: investire in qualità e taratura."),
s("Attuatori","Attuatori domotici",
 "Le mani dell'impianto: relè, dimmer, motori, valvole, attuatori multifunzione.",
 "Attuatori bus (KNX) o Wi-Fi; attuatori a relè per carichi; attuatori motori per tapparelle; valvole termostatiche elettroniche.",
 "Attuare luci, carichi, tapparelle, clima, irrigazione, serrature.",
 "Sostituzione quasi plug-and-play in centralino; diagnostica da bus.",
 "Compatibilità carichi (LED, motori) da verificare; scatti elettrici su bobine.",
 "Attuatore 4 canali KNX: 150-300 €; attuatore Wi-Fi: 15-40 €.",
 "MDT, Jung, Gira (KNX); Shelly, Sonoff (Wi-Fi).",
 "Marcatura CE; CEI 64-8-4 protezioni.",
 "Sovradimensionare i contatti per i carichi capacitivi LED: la regola è corrente nominale x3 in scelta."),
s("Illuminazione smart","Gestione illuminazione avanzata",
 "Controllo luci: accensioni sceniche, dimmer, presenza, luce naturale integrata (daylight harvesting).",
 "Dimmer LED compatibili, sensori lux+PIR, logica circadiana (HCL - Human Centric Lighting).",
 "Uffici, scuole, hotel, abitazioni: comfort visivo e risparmio energetico.",
 "Risparmio 30-60% su illuminazione; benessere visivo documentato (HCL).",
 "Qualità dimmer: flicker e compatibilità lampade da testare.",
 "Dimmer KNX: 100-250 €/canale; sensori: 50-150 €.",
 "Standard DALI-2 per il controllo lampade professionali.",
 "EN 12464-1 illuminazione luoghi di lavoro.",
 "Il daylight harvesting in ufficio ripaga in 2-4 anni: sensori + logica che abbassano l'artificiale quando entra il sole."),
s("Protocollo luce","DALI (Digital Addressable Lighting Interface)",
 "Protocollo digitale dedicato al controllo dell'illuminazione professionale.",
 "Bus a 2 fili fino a 64 driver/indirizzo; DALI-2 aggiunte sensori e emergency; DT6/DT8 per LED color/tunable white.",
 "Uffici, retail, musei, ospedali: ogni punto luce indirizzabile.",
 "Controllo fine di ogni lampada; retrofit facile (bus sui fili delle fasi); emergency test integrato.",
 "Richiede progettazione indirizzi; integrazione con BMS via gateway.",
 "Driver DALI: +5-15 €/punto; gateway DALI-BACnet: 400-1.500 €.",
 "Qualunque produttore illuminotecnico professionale.",
 "IEC 62386 (DALI-2); EN 62386.",
 "DALI dentro, BACnet fuori: la coppia standard dell'edificio terziario moderno."),
s("Scenari","Scenari, logiche e sequenze",
 "La programmazione comportamentale: 'cinema', 'benvenuto', 'notte', 'emergenza'.",
 "Logiche AND/OR temporizzate; scene memorizzate nei dispositivi o nel supervisore.",
 "Residenze luxury, hotel (scene benvenuto), uffici (scene riunione/presentazione).",
 "Trasforma la tecnologia in esperienza; il valore percepito aumenta 10x.",
 "Logiche troppo complesse confondono l'utente: regola '3 tap massimo'.",
 "Programmazione: parte dei costi d'installazione (10-20%).",
 "Scene KNX standard, scene Philips Hue/Apple Home.",
 "Nessuna; best practice progettuali.",
 "Una scena si giudica da quanto è ovvia: se serve il manuale d'uso, è sbagliata."),
s("Clima smart","Termoregolazione intelligente",
 "Controllo climatizzazione per zone con presenza, finestre aperte, apprendimento orari.",
 "Valvole termostatiche elettroniche (zigbee/Matter/KNX), sonde ambiente, logiche anti-spreco (finestra aperta = stop).",
 "Riscaldamento e raffrescamento residenziale e terziario.",
 "Risparmio 10-25% su clima; comfort zonale reale; integrazione con calendario.",
 "Impianti idronici mal bilanciati vanificano i controlli.",
 "Valvola smart: 40-100 €; centrale zone: 200-800 €.",
 "Netatmo, Tado, Honeywell (Matter/Cloud); KNX (locale).",
 "UNI EN 215 valvole; direttiva EED per contabilizzazione.",
 "La regola d'oro: regolare PRIMA l'impianto idraulico (bilanciamento), POI i termostati smart."),
s("Sicurezza","Antintrusione integrata",
 "Impianto di sicurezza con sensori volumetrici, perimetrali, centrali, integrato alla domotica.",
 "Doppia tecnologia IR+microonde, contatti magnetici, vibrazione, centrali con bus (es. Bentel, Tyco).",
 "Ville, uffici, negozi, magazzini.",
 "Integrazione: l'allarme attiva scene (accendi luce, alza tapparelle, invia notifica).",
 "Standard antintrusione rigidi sul cablaggio (tamper); integrazione domotica da certificare.",
 "Impianto appartamento: 800-2.500 €; villa: 2-8k€.",
 "Bentel, Ajax (wireless), Satel, DSC.",
 "CEI 79-2/3/4; VDE 0833 per componentistica bus.",
 "La domotica NON sostituisce l'impianto certificato: convivono, con l'antintrusione che manda stati alla domotica."),
s("Videocamere","Videosorveglianza e privacy",
 "Telecamere IP per sicurezza, con vincoli GDPR per aree comuni e lavoro.",
 "IP cam PoE, NVR/VMS, analitiche AI (rilevamento persone, veicoli, LPR).",
 "Cantieri, condomini, aziende, showroom.",
 "Deterrenza documentata; analitiche riducono falsi allarmi 90%.",
 "GDPR: DPIA obbligatoria, tempi conservazione, divieto aree sensibili (uffici, spogliatoi).",
 "Cam IP: 80-400 €; NVR 8ch: 300-800 €; progetto: 50-300 €/punto installato.",
 "Hikvision, Dahua, Axis (top), Ubiquiti (semplice).",
 "GDPR; Legge 76/2013 sicurezza urbana (flussi verso PS); norma videosorveglianza lavoro.",
 "La telecamera si posiziona sulla PROPRIETA', mai sullo spazio pubblico: 1 metro può costare una sanzione."),
s("Accessi","Controllo accessi",
 "Gestione ingressi: badge, RFID, QR, biometria, serrature smart.",
 "Wiegand/OSDP per lettori; RFID 125kHz/13.56MHz; biometria impronta/volto; serrature motorizzate.",
 "Uffici, cantieri, palestre, B&B (check-in digitale).",
 "Tracciabilità ingressi; revoca immediata; niente chiavi perse.",
 "La biometria è dato sensibile GDPR; blackout = aprire in sicurezza (fail-safe vs fail-secure).",
 "Lettore: 50-300 €; serratura smart: 150-600 €; software: 100-500 €/anno.",
 "Kaba, SALTO, Nuki (residenziale), August.",
 "GDPR biometria; EN 60839 controllo accessi.",
 "Cantieri: il controllo accessi con timbratura integrata risolve giacenze e sicurezza (chi è in cantiere in caso d'emergenza)."),
s("Energia","Gestione energetica e load control",
 "Monitorare e gestire i carichi elettrici: produzione FV, consumi, priorità, wallbox.",
 "Contatori smart, sensori corrente, relè di priorità, logiche di load shedding, integrazione inverter.",
 "Ville con FV+auto elettrica+induzione+pompa di calore: il caso limite di carico.",
 "Zero distacchi enel; uso massimo dell'autoconsumo FV; bolletta sotto controllo.",
 "Sistemi chiusi cloud-to-cloud poco affidabili; serve standard (Modbus!).",
 "Kit monitoraggio: 200-600 €; energy manager integrato: 1-3k€.",
 "Shelly EM, Fronius Solar.web, SolarEdge, open source Home Assistant + Modbus.",
 "CEI 0-16 per allacciamenti; UNI CEI 11339 energy management.",
 "Con pompa di calore + wallbox + induzione serve quasi sempre un gestore di carichi: il contatore da 6 kW ringrazia."),
s("FV integrato","Domotica + fotovoltaico e accumulo",
 "L'impianto domotico come cervello del sistema energetico: consumi, produzione, accumulo, EV.",
 "Lettura inverter via Modbus, gestione batteria, logica 'carica la batteria, poi la macchina, poi scalda l'acqua'.",
 "Abitazioni efficienti, B&B, piccoli condomini.",
 "Autoconsumo >70% possibile con logiche di carico; rendimento della batteria monitorato.",
 "API cloud soggette a cambi; dipendenza marca inverter.",
 "Integrazione software: 0-1k€; hardware aggiuntivo minimo.",
 "Home Assistant Energy, Fronius, Victron (flessibili), Sonnen.",
 "CEI 0-21; UNI 9174 impianti generazione.",
 "La scalda-acqua con resistenza 'fotovoltaica' (SG Ready) è il primo upgrade economico: 300 € di relè, +15% autoconsumo."),
s("VMC integrata","Qualità dell'aria e CO2-driven ventilation",
 "La domotica comanda la VMC in base a CO2, umidità e presenza: aria pulita con minimo consumo.",
 "Sensori CO2/UMidità nei locali; comando centralina VMC (velocità, bypass, umidità).",
 "Case passive, uffici, scuole, camere hotel.",
 "Comfort e salute documentati (concentrazione, sonno); consumi della VCA ottimizzati (-30%).",
 "Centraline VMC 'chiuse' senza interfaccia: scegliere modelli con ingresso 0-10V/Modbus.",
 "Centralina VMC smart-ready: +200-500 € rispetto a standard.",
 "Zehnder, Mitsubishi Lossnay, Vortice con controlli esterni.",
 "UNI EN 13779 classificazione aria; UNI/TS 11300 per calcoli.",
 "Sopra i 1.000 ppm di CO2 le prestazioni cognitive calano: sensori CO2 in ufficio sono salute, non gadget."),
s("Irrigazione","Irrigazione smart",
 "Irrigazione giardini e giardini pensili guidata da meteo e umidità del suolo.",
 "Valvole elettroniche, sensori umidità, gateway meteo, logica ET (evapotraspirazione).",
 "Ville, condomini, hotel, aziende agrituristiche, cantieri con verde.",
 "Risparmio acqua 30-50%; prato sano senza pensieri.",
 "Sensori di suolo da calibrare; congelamento valvole in inverno.",
 "Kit zona: 100-300 €; sistema completo giardino: 500-2k€.",
 "Rachio, Hunter Hydrawise, Orbit B-hyve.",
 "Risparmio idrico raccomandato D.Lgs 152/06.",
 "Con green roof e giardini pensili (sempre più richiesti in edilizia), l'irrigazione smart passa da optional a progetto."),
s("Assistiva","Domotica assistiva e senior living",
 "La casa che aiuta: monitoraggio non invasivo di anziani, sicurezza, teleassistenza.",
 "Sensori presenza mm-wave, letti smart, pulsantiere, rilevamento cadute (radar), notifiche caregiver.",
 "Abitazioni anziani, RSA, housing sociale, home care.",
 "Autonomia prolungata a domicilio; famiglia tranquilla; dati per teleassistenza.",
 "Equilibrio tra controllo e autonomia: il consenso è eticamente obbligatorio.",
 "Kit assistenza: 300-1.500 €; servizio monitoring: 20-50 €/mese.",
 "Vayyar radar, Nokia/Withings, soluzioni KNX Health.",
 "GDPR (datore di lavoro no; famiglia sì con consenso).",
 "Il valore sociale è enorme: una caduta rilevata in 2 minuti vale più di qualsiasi scenario 'cinema'."),
s("Progettazione","Cablaggio e quadri dell'impianto domotico",
 "Come si progetta fisicamente: canaline, quadretti, centralini, automazioni elettriche conformi.",
 "Norma CEI 64-8; centralino domotico con attuatori per piano; cablaggio bus separato dai 230V o schermato.",
 "Impianti nuovi e ristrutturazioni radicali.",
 "Manutenibilità: ogni attuatore etichettato e mappato; crescita futura garantita.",
 "Errori classici: bus accoppiato a 230V, centralini saturi, zero documentazione.",
 "Costo cablaggio domotico: +20-40% sull'impianto elettrico tradizionale.",
 "Best practice KNX Association, guide CEI.",
 "CEI 64-8 (impianti utilizzatori a tensione <=1000V); DM 37/08.",
 "Consegnare SEMPRE il progetto ETS/documentazione: un impianto domotico senza documentazione è un'arma puntata contro il futuro proprietario."),
s("Cybersecurity","Sicurezza informatica dell'edificio smart",
 "Proteggere l'edificio connesso: reti, dispositivi, cloud, accessi remoti.",
 "VLAN dedicate IoT, VPN, aggiornamenti firmware, password uniche, zero-trust, IEC 62443.",
 "Ogni edificio connesso: da casa a grattacielo.",
 "L'edificio è ora un sistema informatico: rischio ransomware arriva anche dal termostato.",
 "Complessità per l'installatore tradizionale; dispositivi cinesi senza aggiornamenti.",
 "Hardering base: 0-500 €; progetto sicurezza: 1-5k€.",
 "Firewall UniFi/pfSense; piattaforme certificate KNX Secure, BACnet/SC.",
 "IEC 62443; GDPR per dati personali; NIS2 per enti/gestori infrastrutture.",
 "Prima regola: cambiare TUTTE le password di default. Seconda: rete ospiti separata. Terza: aggiornamenti trimestrali calendarizzati."),
s("Normativa e costi","Normativa e costi dell'impianto domotico",
 "Il quadro normativo e economico completo per progettare e preventivare.",
 "L.46/90: criteri CEN per qualifica impianti; marcatura CE; CEI 64-8; contratto di manutenzione.",
 "Preventivi, direzione lavori, formazione cliente.",
 "Chiarezza contrattuale; qualifica dell'installatore; valore immobiliare aumentato (5-15% percepito).",
 "Mancanza di standard sui prezzi: preventivi eterogenei.",
 "Prezzi 2025: punto luce domotico 60-150 €; attuatore 80-250 €; quadro completo appartamento 3-10k€; villa 15-50k€.",
 "Tabelle prezzi installatori KNX/Mater.",
 "L.46/90; CEI 64-8; contratti tipo ANIT/Confartigianato.",
 "Il vero costo della domotica non è l'hardware: è il progetto e la programmazione (30-50% del totale). Chi risparmia lì compra un impianto che non funziona."),
]

# ===========================================================================
# PACK 3 — IMPIANTISTICA COMPLETA (IDRAULICA, ELETTRICA, HVAC, ANTINCENDIO, FER)
# ===========================================================================
IMPIANTI = [
s("Idraulica","Adduzione acqua potabile",
 "Distribuzione acqua fredda e calda sanitaria (ACS) dall'allaccio ai punti di erogazione.",
 "Tubi multistrato (PE-Xb/Al/PE-Xb), PPR, acciaio inox pressato; collettori con valvole di regolazione e detentori; circolazione ACS per grandi impianti.",
 "Abitazioni, uffici, alberghi, ospedali, laboratori.",
 "Multistrato: rapidità di posa e nessuna ossidazione; collettori: bilanciamento e manutenzione puntuale.",
 "PPR richiede attrezzatura di saldatura; la circolazione ACS costa se non isolata bene.",
 "Multistrato 16-20mm: 1,5-4 €/ml; collettore 8 vie: 60-150 €; installazione punto acqua: 150-350 €.",
 "Impianti a collettore (impianto a 'pettine') ora standard nelle abitazioni moderne.",
 "UNI EN 806; D.M. 174/2004 (requisiti acque potabili interni); D.Lgs 18/2023 (edilizia).",
 "L'ACS deve arrivare <25 s e >50°C (anti-legionella): percorso max 15-20 m dal generatore o inserire circolazione."),
s("Idraulica","Scarichi acque nere e grigie",
 "Evacuazione acque reflue: colonne di scarico, rami orizzontali, ventilazione.",
 "PVC-U e PP silenziosi, HTEM ad alta temperatura per lavatrici/ospedali; vasi a sifone e pilette; colonna con attacco ventilazione.",
 "Bagni, cucine, lavanderie, laboratori, condomini.",
 "Il PP silenzioso riduce il rumore di scarico di 10-15 dB: comfort notturno.",
 "Pendenze errate = intasamenti cronici; curve eccessive vietate.",
 "Tubo PP silenzioso 110: 6-12 €/ml; posa verticale: 30-60 €/ml compreso accessori.",
 "Colonne a ventilazione secondaria negli edifici alti (norma).",
 "UNI EN 12056; EN 1329 (PVC); UNI 9494 (pilette).",
 "Mai ridurre il diametro verso il basso: la colonna va calcolata sul numero di apparecchi scaricanti contemporaneamente (UNI EN 12056)."),
s("Idraulica","Scarichi pluviali",
 "Collezioni e smaltimento acque meteoriche: tetti, lastrici, cortili.",
 "Pluviali in PVC/PP, caditoie per lastrici solari, vasche di prima pioggia (per reintegro), fognatura separata.",
 "Tetti, terrazzi, piazzali, parcheggi interrati (con vasche di laminazione).",
 "Separazione acque piovane/recupero: riduzione bolletta idrica e rischio allagamenti.",
 "Fognatura mista satura = rigurgiti; vasche di laminazione grandi da pulire.",
 "Pluviale 80-110: 3-8 €/ml; caditoia lastrico: 30-80 €/pz; vasca laminazione: 80-200 €/m3.",
 "Sistemi di recupero acque piovane con cisterna e riuso per irrigazione/WC.",
 "UNI EN 12056-3; D.Lgs 152/06 (tutela acque).",
 "Su lastrici e cortili: caditoie + disconnessione fognaria nera sono la prima difesa contro gli allagamenti urbani."),
s("Idraulica antincendio","Impianto idranti e naspi",
 "Rete antincendio a presidi manuali: idranti UNI 45 e avvolgibili (naspi).",
 "Rete dedicata in acciaio zincato/saldato, idranti a colonna o a parete, naspo 30 m DN25/45, quadro di alimentazione e pressurizzazione.",
 "Condomini, uffici, scuole, musei, esercizi commerciali.",
 "Spegnimento immediato con personale addestrato; costo contenuto.",
 "Richiede addestramento dei residenti; manutenzione semestrale obbligatoria.",
 "Idrante UNI 45: 150-400 €; naspo: 80-200 €; quadro antincendio con 2 elettropompe: 2-6k€.",
 "Ogni condominio italiano >10.000 m3 (o >24 m altezza) secondo norma.",
 "UNI 9484; NFPA 14 (per avvolgibili); DM 2 settembre 2021.",
 "Gli idranti richiedono portata: verificare la rete idrica condominiale prima di installarli (spesso serve quadro di pressurizzazione)."),
s("Idraulica antincendio","Impianto a sprinklers",
 "Spegnimento automatico a pioggia: la protezione antincendio più efficace al mondo.",
 "Teste sprinkler a bulbo termico (57-141°C), reti calcolate a portata, centrale di allarme-valvole, serbatoio/gruppo pompe dedicato.",
 "Magazzini, archivi, parcheggi, hotel, ospedali, data center, cucine industriali.",
 "Riduce morti e danni del 80-90% quando attivo; abbassa polizze assicurative.",
 "Costo iniziale; acqua danni su beni non protetti; progetto certificato (VdS/FM o UNI).",
 "Impianto: 15-40 €/m2 per capannoni (tubi nudi) a 40-80 €/m2 per uffici con controsoffitti.",
 "Sistemi NFPA 13/EN 12845; teste 'fast response' per hotel e ospedali.",
 "UNI EN 12845; NFPA 13; UNI 9490 (progettazione).",
 "I sprinkler si progettano SULLA FALSO SOFFITTO definitivo: cambiare il controsoffitto dopo = rifare l'impianto. Coordinamento col cartongesso è critico."),
s("Gas","Adduzione gas metano e GPL",
 "Reti interne gas: dal contatore agli apparecchi, con sicurezza attiva e passiva.",
 "Tubi acciaio, rame, multistrato con marcatura gas, valvole di sicurezza VS, rilevatori gas certificati (UNI 11144).",
 "Abitazioni, ristoranti, laboratori, industrie.",
 "Il VS chiude in 2 s in caso di fuga: salva vite (incidenti domestici).",
 "Le vecchie reti in gomma sono pericolo reale; verifica triennale da professionista abilitato.",
 "Rete interna appartamento: 300-900 €; ristorante: 1-3k€; rilevatore certificato: 60-150 €.",
 "Valvole di sicurezza ora OBBLIGATORIE in nuovi impianti e in caso di ristrutturazione.",
 "UNI 7129; UNI 7131; legge reg. gas (DPR 144/2000).",
 "Norma chiara: in ristrutturazione l'impianto gas va MESSO A NORMA INTEGRALMENTE, non a pezzi: è l'occasione giusta per rivedere tutto."),
s("Idraulica","Protezione contro rischio di contaminazione (sistemi a tenuta di rifiuto)",
 "Dispositivi antinquinamento per evitare risalite nei punti d'acqua: zone di protezione.",
 "Vasi di espansione con membrane conformi, dispositivi BA (break tank), rubinetti termostatici con limitazione.",
 "Ospedali, dentisti, laboratori, cucine industriali, idromassaggio.",
 "Previene contaminazioni chimiche e batteriche (legionella inclusa).",
 "Sottovalutato dai piccoli artigiani; controlli sanitari severi negli edifici pubblici.",
 "Dispositivi: 50-400 €/punto; progetto zone: da 200 €.",
 "Zone di protezione secondo EN 1717.",
 "UNI EN 1717 (fondamentale); circolari ministeriali legionella.",
 "Ogni punto d'acqua deve avere la giusta 'zona di protezione': è il requisito più trascurato e più sanzionato negli esercizi pubblici."),
s("Idraulica","Addolcimento e trattamento acque",
 "Condizionamento chimico e fisico delle acque: durezza, ferro, sedimenti, legionella.",
 "Addolcitori a resine (Na+), dosatori polifosfati, filtri a sedimenti/carbone, sistemi UV, trattamenti shock per legionella.",
 "Zone molto dure (>30 °F), caldaie, torri evaporative, ospedali, piscine, laboratori.",
 "Riduce incrostazioni (+20% efficienza caldaia); protegge scambiatori e rubinetteria.",
 "L'acqua addolcita non è potabile: ramo separato; manutenzione resine.",
 "Addolcitore domestico: 400-1.200 €; industriale: 2-10k€; analisi acqua: 50-150 €.",
 "Addolcimento standard in gran parte del Centro-Sud Italia (acque >25-35 °F).",
 "DPR 236/88 (qualità acque potabili); UNI EN 806.",
 "Prima di qualsiasi trattamento: ANALISI dell'acqua (60 €) che determina tutto il resto. Mai vendere un addolcitore senza analisi."),
s("Elettrica","Cabina di trasformazione MT/BT",
 "Il cuore elettrico di edifici grandi: trasformazione da media tensione a bassa tensione.",
 "Celle MT (sezionatori, interruttori, trasformatore 15-20/0,4 kV), celle BT, sistema SG, misura ENEL in cabina.",
 "Condomini grandi, uffici, hotel, industrie, data center.",
 "Autonomia gestionale; tariffe MT più convenienti; continuità di servizio.",
 "Manutenzione obbligatoria con personale abilitato; spazio e costi iniziali.",
 "Cabina 630-1000 kVA: 40-120k€ chiavi in mano; manutenzione: 3-8k€/anno.",
 "Cabine standardizzate 15/20 kV secondo norma CEI.",
 "CEI 0-16 (allacciamenti); DPR 462/01 (esercizio); leggi gioco? no: L.186/68.",
 "La gestione della cabina richiede un 'esercente' nominato: molti condomini lo ignorano e rischiano sanzioni e blackout."),
s("Elettrica","Quadro generale di bassa tensione",
 "Distribuzione e protezione dell'energia elettrica di un edificio.",
 "Interruttore generale, magnetotermici (MCB), differenziali (RCD 30 mA / 300 mA selettivi), barre, quadri modulari DIN.",
 "Qualsiasi edificio: dal monolocale alla torre.",
 "Selettività e protezione delle persone; manutenibilità modulare.",
 "Quadri pieni zeppi e mal etichettati: incubo decennale; aggiunte abusive.",
 "Quadro appartamento completo: 300-900 € materiali; quadro condominiale: 1-5k€.",
 "Componenti ABB, Schneider, Gewiss, Siemens.",
 "CEI 64-8; CEI EN 61439 (quadri).",
 "Il differenziale 30 mA salva la vita: ogni ambiente bagnato deve avere protezione dedicata. Punto non negoziabile."),
s("Elettrica","Impianto di terra (SG)",
 "Dispersore di terra: protezione di persone e cose dai guasti elettrici e fulmini.",
 "Piazzola dispersori (aste/spire rame), conduttore di terra PE, morsettiera, interruttore differenziale coordinato.",
 "Tutti gli edifici, obbligatorio per legge.",
 "La messa a terra è IL sistema che rende efficaci i differenziali; resistenza <40 ohm (valore tipico) o secondo progetto.",
 "Realizzata male nei cantieri (bastano poche decine di ohm in più per non funzionare).",
 "Messa a terra casa: 200-600 €; misura con protocollo: 150-300 €.",
 "Piazzole con aste da 1,5-2 m in terreno omogeneo.",
 "CEI 64-8; CEI EN 61936.",
 "Ogni ristrutturazione radicale = nuova verifica del dispersore (obbligatoria) con VERBALE: niente verbale, niente conformità."),
s("Elettrica","Protezione da sovratensioni (SPD)",
 "Difesa da fulmini e manovre rete: scaricatori di sovratensione.",
 "SPD Tipo 1+2 (testa 10/350 μs) a monte, Tipo 2 nei quadri di zona, Tipo 3 vicino ai carichi sensibili.",
 "Edifici con impianto fulmini, zone fulminose, impianti elettronici/FV.",
 "Protegge elettronica, quadri KNX, inverter FV, elettrodomestici: danni da fulmine costano 10x gli SPD.",
 "Spesso omessi per risparmio; installati male (cavi troppo lunghi).",
 "SPD Tipo 1+2: 100-300 €; installazione compresa: 200-500 €.",
 "Dehn, ABB, Citel.",
 "CEI 64-8-4; CEI EN 61643.",
 "L'impianto fulmini senza SPD interni protegge l'involucro, non l'elettronica: dopo un fulmine i danni tipici sono sul domotica/FV. Gli SPD costano meno di un inverter."),
s("Elettrica","Cavidotti e canaline",
 "Distribuzione dei cavi elettrici in canaline, tubi protettivi, sottotraccia.",
 "Tubi corrugati 16-25 mm, canaline 25x40+, sottoservizi; cavi FG16OR16, N07V-K; il posatoio va nella muratura secondo norma.",
 "Ogni edificio: posa in opera dei cavi.",
 "Sistematicità e tracciabilità; il sottotraccia è invisibile ed esteticamente perfetto.",
 "Tubi troppo pieni (>40% riempimento) surriscaldano; canaline esteticamente critiche se non progettate.",
 "Posa punto luce in traccia: 60-120 €; canalina 25x40: 3-6 €/ml.",
 "Sistemi a secco: canaline esterne certificate CEI.",
 "CEI 64-8-2 (posa); CEI 64-8-5 (selezione cavi).",
 "La regola 40% di riempimento tubo non è burocratica: un tubo pieno surriscalda il cavo e degrada l'isolante in anni."),
s("Elettrica","Impianto TV, satellitare e broadcast",
 "Distribuzione segnali TV terrestri/satellitari, DAB, streaming strutturato.",
 "Antenne UHF, parabole, centralini d'antenna, prese multimediali (TV+SAT+DATA), amplificatori, matrici.",
 "Condomini, hotel, ospedali (sistemi SMATV).",
 "La presa multimediale unificata semplifica ogni locale; matrici per hospitality.",
 "Le vecchie reti cascata degradano: i condomini storici hanno impianti TV pessimi.",
 "Impianto condominiale: 30-80 €/appartamento; matrice hotel: 1-5k€.",
 "Centralini Fracarro, IKUSI, Televes.",
 "Legge 249/97 (Telecom); CEI 28-1.",
 "In ristrutturazione: passare cavo coassiale 5E + LAN in ogni stanza: il 'cordone' mediale della casa moderna."),
s("Elettrica","Rete dati LAN strutturata",
 "Cablaggio dati ethernet dell'edificio: dorsali e punti rete in ogni ambiente.",
 "Cavo Cat6/Cat6A FTP, armadietti rack con patch panel, switch PoE, Wi-Fi access point cablati.",
 "Abitazioni (ufficio smart working), uffici, hotel, scuole.",
 "La dorsale di dati è la 'ferrovia' della domotica moderna: ogni dispositivo IP ci passa.",
 "Wi-Fi mesh senza dorsale cablata = colli di bottiglia.",
 "Punto rete posato: 80-150 €; switch PoE 8 porte: 100-300 €; AP Wi-Fi 6: 100-400 €.",
 "Standard Cat6A per dorsali (10 Gbit-ready); PoE per camere e AP.",
 "ISO/IEC 11801; CEI EN 50174.",
 "Regola moderna: 2 prese dati per camera + 1 per TV + dorsale al router. Il Wi-Fi si aggiunge SOPRA la dorsale, mai al suo posto."),
s("HVAC","Caldaia a condensazione",
 "Generatore di calore a gas a rendimento 90-109%: il punto di riferimento europeo.",
 "Bruciatore a modulazione, condensatore che recupera calore latente, scarico a bassa temperatura (materiali PP).",
 "Riscaldamento e ACS per abitazioni, condomini, terziario.",
 "Efficienza reale con ritorni freddi (pannelli radianti); compatibile con Conto Termico.",
 "Compatibile solo con impianti a bassa temperatura; con radianti alti spreca.",
 "Caldaia a camera aperta 24-32 kW: 1.200-2.800 € installata; manutenzione annuale 80-150 €.",
 "Modulazione 1:10 per convivere con le micro-richieste delle case efficienti.",
 "UNI EN 483; Ecodesign ERP; UNI 10389 (verifiche).",
 "La caldaia si dimensiona sull'INVOLUCRO, non sulla metratura: una casa efficiente da 150 m2 in montagna può bastare 15 kW."),
s("HVAC","Pompa di calore aria-acqua",
 "Macchina frigorifera inversa che scalda (e raffresca) usando l'aria esterna: 1 kWh elettrico -> 3-5 kWh termici.",
 "Unità esterna (sorgente) + unità idronica interna; compressori inverter R32; produzione ACS con accumulo; integrazione FV.",
 "Nuove abitazioni, ristrutturazioni profonde, piccoli terziari, case in montagna.",
 "Riduzione consumi 50-70% vs caldaia a gas; raffrescamento incluso; abbinamento perfetto a pannelli radianti e FV.",
 "Rumorosità unità esterna da gestire; performance che calano sotto -10°C (serve integrazione o dimensionamento prudente).",
 "PDC aria-acqua 8-12 kW: 6.000-12.000 € installata; PDC aria-aria multisplit: 1.500-4.000 € per zona.",
 "Mitsubishi, Daikin, Vaillant, Panasonic: le 'big' del settore residenziale.",
 "F-gas Reg. UE 517/2014 (manutenzione obbligatoria); UNI 11300 per calcoli.",
 "La PDC è la scelta di default 2025+ in Italia (anche per il Conto Termico 3.0): il progettista deve saperla dimensionare con il metodo bin (temperature esterne di progetto)."),
s("HVAC","Pannelli radianti a pavimento/parete/soffitto",
 "Distribuzione del calore (e fresco) per irraggiamento: il comfort termico più efficiente.",
 "Tubi PE-Xa/PERT in massetto (spessore 5-8 cm sopra i tubi) o sistemi a secco (predalles, ponteggio radiante); mandata 28-35°C.",
 "Abitazioni nuove, ristrutturazioni con massetto, soffitti radianti per raffrescamento.",
 "Confort superiore (uniformità ±0,5°C), riduzione polveri (no convezione), perfetto per PDC e caldaie a condensazione.",
 "Inerzia termica: lenta a reagire (va con prognosi meteo, non con accensioni manuali); attenzione in massetti con parquet.",
 "Pavimento radiante: 40-80 €/m2 materiali+posa (massetto escluso); soffitto radiante: 50-100 €/m2.",
 "Sistemi a bassa inerzia (secco) per il retrofit; sistemi in massetto per le nuove.",
 "UNI EN 1264; UNI 1264-4 calcoli.",
 "Il radiante si controlla con curve climatiche e sonde esterne: il termostato in ogni stanza è quasi un danno col radiante. Da spiegare al cliente."),
s("HVAC","VMC: ventilazione meccanica controllata",
 "Ricambio d'aria con recupero di calore: obbligatoria (di fatto) nelle case efficienti e passive.",
 "Centralina con scambiatore entalpico o controflusso (rendimento 80-92%), reti di distribuzione aria, bocchette a flusso continuo o variabile.",
 "Nuove costruzioni, ristrutturazioni profonde, scuole, uffici (legge obbliga ricambio).",
 "Fino al 90% del calore recuperato; umidità e CO2 controllate; niente muffa da condensa.",
 "La manutenzione filtri è obbligatoria e trascurata; le reti mal progettate sono rumorose.",
 "VMC centralizzata casa: 3.000-8.000 € installata; VMC decentralizzata (monoblocco parete): 500-1.500 €/locale.",
 "Zehnder, Zehnder ComfoAir; Mitsubishi Lossnay; Vortice.",
 "UNI EN 13779; UNI/TS 11300-2; DM 26/06/2015 (requisiti energetici, ventilazione).",
 "La VMC decentralizzata è il compromesso giusto per il retrofit: il 70% del beneficio a 1/4 del costo e senza opere murarie."),
s("HVAC","Climatizzazione VRF/VRV multisplit",
 "Sistemi di climatizzazione multisplit evoluti: una sola unità esterna per decine di interni.",
 "Refrigerante variabile (R32/R410A in uscita), inverter su ogni interno, recupero di calore tra le zone (simultaneo caldo/freddo).",
 "Uffici, hotel, ristoranti, grandi abitazioni, condomini.",
 "Simultaneità caldo/freddo (uffici con facciate diverse) con recupero: efficienza estrema; nessun gas di scarico in locale.",
 "Costo iniziale; manutenzione F-gas certificata; la refrigerante distribuita in edifici è dibattuta (norme in aggiornamento).",
 "Impianto VRF ufficio: 60-120 €/m2 installato; manutenzione: 5-15 €/m2/anno.",
 "Daikin VRV, Mitsubishi VRF, LG Multi V, Samsung DVM.",
 "F-gas; EN 378 (sicurezza refrigeranti).",
 "Il VRF con recupero totale è la scelta dei terziari premium: chi progetta uffici lo deve saper dimensionare per zone e simultaneità."),
s("HVAC","Ventilazione ambienti di lavoro e capannoni",
 "Aspirazione e ricambio nei luoghi di lavoro: salute obbligatoria e spesso progettata male.",
 "Capiato (ventilatori a tetto), ventilatori a parete, sistemi di destratificazione, condizionatori evaporativi.",
 "Capannoni, officine, magazzini, cucine industriali, laboratori.",
 "Riduzione stress termico (protezione lavoratori); in estate i capannoni senz'aria sono fermi produttivi.",
 "La destratificazione nei capannoni alti ripaga in 1-2 anni ma pochi la fanno.",
 "Ventilatore a tetto 1.500 mm: 400-1.000 €; sistema destratificazione capannone: 5-15 €/m2.",
 "Big Ass Fans, standard industriale.",
 "D.Lgs 81/08 allegato XVII (microclima); UNI EN ISO 7730 (comfort).",
 "Prima di installare il condizionatore in un capannone, chiedi: il tetto è coibentato? Un tetto caldo annulla qualsiasi climatizzazione (soffitti radianti 60-70°C in estate)."),
s("HVAC","Pompe di calore ibrido (integrazione)",
 "Combinazione caldaia a gas + pompa di calore: la PDC copre il 90% del fabbisogno, la caldaia i picchi.",
 "Gestione intelligente del punto di switch (economica o termica), unico accumulo ACS, integrazione con tariffe dinamiche.",
 "Ristrutturazioni dove la rete elettrica non basta o il clima è severo; chi vuole il meglio dei due mondi.",
 "Massimo risparmio senza rinunciare alla sicurezza del picco; derating elettrico ridotto.",
 "Doppio generatore da mantenere; controllo integrato da marca unica.",
 "Ibrido PDC+caldaia: 8.000-15.000 € installato (PDC + caldaia a condensazione compatte).",
 "Daikin Hybrid, Vaillant aroTHERM hybrid, Mitsubishi Ecodan Hydro.",
 "F-gas + UNI 7129 (gas); Conto Termico 3.0 ammissibile.",
 "L'ibrido è la risposta prudente per il retrofit del patrimonio italiano (4,6 milioni di caldaie a gas obsolete): il mio LLM deve conoscerlo bene."),
s("Antincendio","Rilevazione incendi e analisi",
 "Sensori che rilevano fumo, calore, fiamma, gas: il primo anello della catena di sicurezza.",
 "Rivelatori ottici (fumo), termovelocimetrici, multisisma, centrali analogiche indirizzate, aspirazione per ambienti alti (ASD).",
 "Uffici, hotel, ospedali, data center, magazzini, parcheggi.",
 "Evacuazione precoce: la differenza tra un incidente e una tragedia; la manutenzione è normata e tracciata.",
 "Falsi allarmi in cucine e parcheggi (sensori sbagliati); centraline non manutenute.",
 "Rivelatore: 30-150 €; centrale indirizzata: 800-3k€; progetto: 3-15 €/m2.",
 "Esser, Bosch, NOTIFIER (Honeywell), Siemens Cerberus.",
 "EN 54 (serie completa); DM 2/9/2021.",
 "La rilevazione si progetta per COMPARTI e rischi (cucina, parcheggio, camera): lo stesso edificio ha sensori diversi per ambiente."),
s("Antincendio","Evacuazione vocale e emergenza",
 "Diffusione sonora di emergenza: messaggi chiari che guidano l'uscita.",
 "Impianti EVAC (EN 50849), altoparlanti a onde guidate per stadi/aeroporti, megafoni centralizzati, collegamento centrale incendio.",
 "Stadi, scuole, ospedali, centri commerciali, industrie.",
 "L'evacuazione vocale dimezza i tempi di uscita rispetto alla sirena; in stadi è l'unica via praticabile.",
 "Progetto specialistico; la batteria tampone va mantenuta (la causa #1 dei guasti).",
 "Impianto EVAC edificio: 5-20 €/m2; centrali grandi impianti: 10-50k€.",
 "Bosch PAVIRO, Dynacord, systems integrators certificati.",
 "EN 50849 (EVAC); EN 54-16.",
 "L'emergenza si prova: la simulazione annuale con cronometro è l'unico modo di sapere se funziona."),
s("Antincendio","Porte tagliafuoco e compartimentazione",
 "Barriere fisiche al fuoco: porte REI 60-120, pareti, serrande, vetri tagliafuoco.",
 "Porte metalliche certificate UNI 9723, sigillanti intumescenti, serrande coibentate, vetri EI30-120.",
 "Ogni edificio: corridoi, vani scale, garage interrati, laboratori.",
 "Il comparto funziona SOLO se tutte le chiusure sono a norma: una porta spalancata annulla tutto.",
 "Le porte tagliafuoco spesso vengono 'bloccate' per comodità; i fermi automatici costano e vengono tolti.",
 "Porta REI 60: 400-1.200 €; vetro tagliafuoco: 300-800 €/m2; verifica annuale: 10-30 €/porta.",
 "Porte Dierre, Novoferm; vetri Saint-Gobain, Schott.",
 "UNI 9723 (porte); DM 3/8/2015 (prevenzione incendi); UNI EN 13501 (classi).",
 "Il controllo annuale delle chiusure tagliafuoco è l'obbligo più economico e più trascurato: un check di 1 giorno salva un intero edificio."),
s("FER","Fotovoltaico: stringhe, inverter e connessione",
 "Generazione elettrica da sole: il cuore della transizione energetica degli edifici.",
 "Moduli (400-600 Wp, TOPCon/IBC oggi), inverter stringa o microinverter/ottimizzatori, stringbox, connessione BT con CEI 0-21/0-16, metering bidirezionale.",
 "Tetti di abitazioni, capannoni, facciate, carport, agrivoltaico.",
 "Il costo è crollato (70% in 15 anni); il risparmio in bolletta è immediato con autoconsumo; incentivi (Ritiro Dedicato, CER).",
 "La resa dipende da orientamento/inclinazione/ombreggiamenti; la burocrazia (GSE) scoraggia.",
 "Impianto 6 kWp residenziale: 7.000-12.000 € (2025) installato; capannone 100 kWp: 60.000-90.000 €.",
 "Moduli: LONGi, Jinko, Trina; inverter: SolarEdge, Fronius, Huawei, SMA.",
 "CEI 0-21 (BT), CEI 0-16 (MT); UNI 9174; D.Lgs 28/2011.",
 "Il vero rendimento di un FV si decide al sopralluogo: alberi, comignoli, antenne possono distruggere la produzione di un tetto 'bello'."),
s("FER","Accumulo batterie domestico",
 "Batterie agli ioni di litio per accumulare il FV e usarlo di sera: l'autoconsumo oltre il 60-80%.",
 "LiFePO4 (sicuri, lunghi cicli), modulari 5-20 kWh, ibridi o retrofit AC/DC, gestione con inverter ibrido.",
 "Abitazioni con FV, B&B, piccoli terziari, condomini con CER.",
 "Massimizza l'autoconsumo; backup di emergenza per blackout (funzione islanding).",
 "Il ROI puro è lungo (8-15 anni se non c'è incentivo); la batteria degrada (80% dopo 6.000 cicli).",
 "Batteria 10 kWh: 4.000-8.000 € installata; costo/kWh in calo continuo.",
 "Tesla Powerwall, BYD, Pylontech, Sonnen (tedesco, servizi CER).",
 "UNI CEI 0-16 (connessi BT); regole CEI 0-21 aggiornate per accumulo.",
 "L'accumulo conviene davvero con: prezzi elettricità alti, incentivi, backup desiderato. Altrimenti la PDC consuma il surplus di giorno: 'batteria termica' gratis."),
s("FER","Colonnine di ricarica veicoli elettrici",
 "Infrastruttura di ricarica privata e condominiale: la nuova frontiera degli edifici.",
 "Wallbox 7-22 kW AC, colonnine DC per flotte, gestione carichi (dynamic load management), prese tipo 2, contabilizzazione (RFID).",
 "Box auto, parcheggi condominiali, uffici, hotel, aziende.",
 "L'edificio diventa 'distributore': servizio ai residenti/dipendenti; richiesto sempre più spesso in vendita/affitto.",
 "I quadri elettrici condominiali non sono pronti: serve load management; i condomini litigano sul costo dell'energia comune.",
 "Wallbox 7 kW: 400-1.200 € + posa; colonnina DC 50 kW: 15.000-25.000 €.",
 "Wallbox Pulsar, Zaptec, ABB Terra; gestione: monta o openWB.",
 "CEI EN 61851; CEI 0-21 per connessione.",
 "La regola d'oro condominiale: wallbox con dynamic load management + contabilizzazione RFID (chi consuma paga). Nessun attrito, nessuna guerra tra condomini."),
s("Contabilizzazione","Contabilizzazione diretta e indiretta del calore",
 "Misurare il calore consumato da ogni unità immobiliare: obbligatoria nei condomini centralizzati.",
 "Contatori diretti (acqua calda primaria) o ripartitori indiretti (sulle superfici radianti) + unità centrali; lettura radio.",
 "Condomini con riscaldamento centralizzato (millioni di unità in Italia).",
 "Chi consuma paga: risparmi medi documentati del 15-25% post-contabilizzazione; equità tra vicini.",
 "I ripartitori mal posizionati misurano male; le manutenzioni saltate rovinano tutto.",
 "Ripartitore: 30-80 €/unità; centrale: 300-800 €; contatore diretto: 150-400 €.",
 "Ista, Techem, Sontex: i 'big three' europei.",
 "UNI EN 834/835 (ripartitori/contatori); legge 10/91 art. 26 bis (obbligo).",
 "La contabilizzazione è il provvedimento energetico italiano MIGLIORE al mondo per diffusione: un LLM edile italiano DEVE conoscerla nei dettagli."),
s("Normativa impianti","D.Lgs 37/08: appalti e gestione impianti",
 "La legge italiana dell'impiantistica: installazione, manutenzione, abilitazioni dei professionisti.",
 "Requisiti dei progettisti/installatori (abilitazione DM), Dichiarazione di Conformità (DiCo), libretto impianto, verifiche periodiche.",
 "Ogni intervento su impianti: dal nuovo impianto alla sostituzione della caldaia.",
 "Tutto tracciato e legale; il libretto è il 'libro sanitario' dell'edificio.",
 "Sanatorie e abusi comuni (lavori senza DiCo); il compratore di casa poi paga.",
 "Costo DiCo e pratiche: 100-400 €; verifica energetica (legge 10): 300-900 €.",
 "Pratiche standardizzate per legge 10, CPI, prevenzione incendi.",
 "D.Lgs 37/08; DM 37/08; Legge 10/91 (energetica).",
 "Chi compra casa DEVE chiedere libretti e DiCo di tutti gli impianti: l'immobile senza documentazione vale meno, punto."),
s("Normativa impianti","Legge 10/91 e certificazione energetica (APE)",
 "La normativa energetica degli edifici: requisiti, calcoli, attestato di prestazione energetica.",
 "Calcolo dei fabbisogni (UNI/TS 11300), metodologia energetica nazionale (decreto requisiti), APE in vendita/affitto, CTU progettazione.",
 "Nuove costruzioni, ristrutturazioni importanti, compravendite.",
 "L'APE orienta compratori e affittuari; i requisiti spingono l'efficienza (involucro, impianti).",
 "Calcoli spesso 'di facciata' per chiudere pratica; il valore APE 'alla rovescia' è un rischio legale.",
 "Progetto legge 10 + APE: 300-900 €; pratica edilizia energetica grande: 1-3k€.",
 "Software Namirial, Logical Soft, MC4, Blumatica.",
 "Legge 10/91; D.Lgs 192/2005 (EPBD); D.Lgs 48/2020 aggiornato.",
 "Da quando esiste la 'scheda descrittiva' dell'APE (2023), l'attestato è diventato uno strumento di marketing: l'LLM deve saper leggere e spiegare le classi (A4-G)."),
s("Incentivi","Conto Termico 3.0, CEE e detrazioni per impianti",
 "Gli incentivi 2025+ per la riqualificazione energetica e gli impianti efficienti.",
 "Conto Termico 3.0 (2025): incentivi a premio per pompe di calore, caldaie a biomassa, solare termico; CEE (certificati bianchi) per scambi termici e VMC; detrazioni fiscali se disponibili.",
 "Ristrutturazioni di involucro e impianti: la maggior parte degli interventi rientra in qualcosa.",
 "Gli incentivi cambiano la bancabilità degli interventi: la PDC con CT3.0 diventa la scelta quasi obbligata.",
 "Le regole cambiano spesso (il LLM deve sapere di verificare sempre il testo vigente); le pratiche richiedono professionisti abilitati.",
 "Premio CT3.0: percentuali sul costo (fino a 40-50% per le PDC in sostituzione caldaia); i valori esatti vanno verificati su GSE.",
 "Portale GSE; EGE (esperti in gestione energetica) per le pratiche grandi.",
 "DM Conto Termico 3.0 (2025); direttive CEE ARERA; normativa fiscale annuale.",
 "Regola critica per il LLM: MAI citare cifre di incentivi come certe: indicare SEMPRE la fonte (GSE/ENEA) e la data di verifica — gli incentivi sono la causa #1 di informazioni datate nel settore."),
s("Dimensionamento","Dimensionamento rapido idraulico",
 "Le regole pratiche per dimensionare tubazioni e portate senza software.",
 "Portata per tipologia: lavabo 0,10-0,15 l/s, doccia 0,15-0,20, vasca 0,20-0,30, WC 0,10-0,12; tubo multistrato 16mm = 1 punto erogazione, 20mm = 2-3 punti, 25-26mm = colonnina piano.",
 "Preventivi rapidi, verifiche di progetto, piccole ristrutturazioni.",
 "Velocità immediata di stima; coerenza tra tubo e punti d'uso.",
 "Resta una stima: il calcolo di norma (UNI EN 806) serve per gli edifici complessi.",
 "Tabella portate disponibile in ogni manuale tecnico.",
 "Metodo del 'carico di somma' (DIN 1988-300).",
 "UNI EN 806-3.",
 "Regola mnemonica: 'un tubo 16 per ogni becco, 20 per due, 26 per la colonna' copre il 90% delle abitazioni ordinarie."),
s("Dimensionamento","Dimensionamento rapido elettrico",
 "Le regole pratiche per sezioni di cavo e protezioni dell'impianto elettrico.",
 "Sezioni tipiche: illuminazione 1,5 mm2 con magnetotermico 10A; prese 2,5 mm2 con 16A; forno/induzione 4-6 mm2 con 20-25A; PDC/wallbox dedicata 6-10 mm2; caduta di tensione max 4% (BT).",
 "Verifiche rapide in cantiere, ampliamenti, controlli.",
 "Controllo immediato della coerenza cavo-protezione: il 70% dei guasti derivano da disaccordo.",
 "Le regole rapide non sostituiscono il calcolo di verifica della IEC 60364.",
 "Tabella sezioni-prese standard in ogni manuale.",
 "Metodo delle 'correnti di impiego' e di cortocircuito (CEI 64-8).",
 "CEI 64-8; IEC 60364.",
 "Regola mnemonica: 1,5 con 10, 2,5 con 16: chi non rispetta questa accoppiata è in errore. Poi: una linea = un magnetotermico dedicato."),
]

# ===========================================================================
# GENERAZIONE PACK + INDICE MASTER
# ===========================================================================
PACKS = {
 "ROBOTICA_EDILIZIA_PACK": ("Robotica applicata alle costruzioni",
     "Stampa 3D, robot muratori, droni, esoscheletri, prefabbricazione automatizzata, BIM-to-robot, economia e limiti.",
     ROBOTICA),
 "DOMOTICA_PACK": ("Domotica e building automation",
     "Protocolli KNX/BACnet/Modbus/Zigbee/Matter, sensori e attuatori, sicurezza, energetica, normativa e costi.",
     DOMOTICA),
 "IMPIANTI_COMPLETA_PACK": ("Impiantistica completa",
     "Idraulica, elettrica, HVAC, antincendio, FER, normativa, incentivi e dimensionamento rapido.",
     IMPIANTI),
}

COUNTS = {}
for nome, (titolo, desc, data) in PACKS.items():
    pdir = os.path.join(UNI, nome)
    os.makedirs(os.path.join(pdir, "schede"), exist_ok=True)
    with open(os.path.join(pdir, "schede", "schede.jsonl"), "w", encoding="utf-8") as f:
        for it in data:
            f.write(json.dumps(it, ensure_ascii=False) + "\n")
    with open(os.path.join(pdir, "README.md"), "w", encoding="utf-8") as f:
        f.write(f"# {nome}\n\n**{titolo}**\n\n{desc}\n\nSchede: {len(data)} (formato JSONL, un oggetto per riga).\n")
    COUNTS[nome] = len(data)

index = ["# 🎓 UNIVERSITA DELL'EDILIZIA E DELLE COSTRUZIONI\n",
 "Knowledge base universale per l'addestramento di LLM specializzati in edilizia,\n",
 "costruzioni, impiantistica, architettura, ingegneria, innovazione edile e mondo\n",
 "dell'impresa costruttiva. Ogni pack è un 'corso'; ogni scheda è una 'lezione'.\n\n",
 "## Struttura del curriculum\n\n",
 "| # | Corso (pack) | Contenuto | Schede |\n",
 "| --- | --- | --- | --- |\n"]

rows = [
 ("01","EDILIZIA_PACK","Tecnologia e costruzioni: strutture, fondazioni, muratura, solai, involucro, pratiche, sicurezza"),
 ("02","MATERIALEDILE_PACK","Materiali da costruzione: 162 schede in 20 categorie, dal fissaggio alle innovazioni"),
 ("03","CAD_Library","Dataset CAD open source: DWG, DXF, 3DS, 3DM, STEP con metadati geometrici"),
 ("04","IMPIANTI_COMPLETA_PACK","Impiantistica completa: idraulica, elettrica, HVAC, antincendio, FER, incentivi"),
 ("05","DOMOTICA_PACK","Domotica e building automation: protocolli, sensori, sicurezza, energia"),
 ("06","ROBOTICA_EDILIZIA_PACK","Robotica delle costruzioni: stampa 3D, robot, droni, AI vision, digital twin"),
 ("07","Fondamenti_Pack","Matematica, geometria, fisica, scienze: le basi del calcolo strutturale"),
 ("08","Storia_Pack","Storia dell'edilizia, dell'architettura e dell'ingegneria dall'antichità a oggi"),
 ("09","Italia_Sistema_Pack","Costituzione, fisco, tributi, sistema Paese, appalti pubblici, normativa italiana"),
 ("10","Digitale_Marketing_Pack","Marketing edile, social, branding, video, gestione agenti AI"),
 ("11","Coding_Master_Pack 1-5","Coding completo: dal fondamento all'ingegneria del software"),
]
for num, nome, desc in rows:
    cnt = COUNTS.get(nome, "")
    index.append(f"| {num} | {nome} | {desc} | {cnt} |\n")

index.append(f"""
## Totale pack consegnati: 13 zip + questa repository (aggiornata al 2026-09-30)

## Licenza d'uso
Materiale originale creato come corpus di training: riutilizzabile liberamente
per addestramento, fine-tuning e RAG di modelli LLM proprietari.
""")
with open(os.path.join(UNI, "INDEX.md"), "w", encoding="utf-8") as f:
    f.writelines(index)

# Zip master della repository
zip_path = os.path.join(ROOT, "UNIVERSITA_EDILIZIA_MASTER.zip")
if os.path.exists(zip_path):
    os.remove(zip_path)
folders = [d for d in os.listdir(ROOT) if os.path.isdir(os.path.join(ROOT, d)) and d not in (".git",)]
with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
    for folder in folders:
        base = os.path.join(ROOT, folder)
        for b, _, files in os.walk(base):
            for fn in files:
                full = os.path.join(b, fn)
                z.write(full, os.path.relpath(full, ROOT))
shutil.copy2(zip_path, r"C:\Users\alessandro\Desktop\UNIVERSITA_EDILIZIA_MASTER.zip")

print(f"Schede nuove: Robotica={len(ROBOTICA)}, Domotica={len(DOMOTICA)}, Impianti={len(IMPIANTI)}")
print(f"Zip master: {zip_path} ({os.path.getsize(zip_path)} byte)")
print("Folder nello zip:", len(folders), folders)
