# -*- coding: utf-8 -*-
"""Universita dell'Edilizia - tecnologia e dimensionamento impiantistico."""
import json, os

ROOT = os.path.abspath(os.path.dirname(__file__))
UNI = os.path.join(ROOT, "UNIVERSITA_EDILIZIA")

def s(cat, nome, descrizione, tecnologia, applicazioni, vantaggi, limiti, costi, casi, normative, note):
    return {"categoria": cat, "nome": nome, "descrizione": descrizione,
            "tecnologia": tecnologia, "applicazioni": applicazioni,
            "vantaggi": vantaggi, "limiti": limiti, "costi_e_economia": costi,
            "casi_real_world": casi, "normative": normative, "note_cantiere": note}

# ===========================================================================
# L1 — TECNOLOGIA DELLE MACCHINE TERMICHE (anatomia)
# ===========================================================================
MACCHINE = [
s("Caldaie","La caldaia murale a gas: anatomia completa delle componenti",
 "Cosa c'è dentro la caldaia che scalda la maggior parte delle case italiane.",
 "Componenti: scambiatore principale (monotermico o bitermico per ACS), bruciatore a modulazione (minimo 3-8 kW), pompa di circolazione, vaso di espansione (6-8 l), valvola di sicurezza 3 bar, sonda fumi/analisi combustione, ventilatore, scambiatore di condensazione (solo a condensazione), centralina elettronica (sensore mandata, flusso, pressione).",
 "Riscaldamento e ACS di abitazioni e piccoli condomini.",
 "Conoscere i componenti = diagnosticare il guasto: il 90% dei 'guasti caldaia' sono componenti da 30-150 €.",
 "L'elettronica moderna richiede assistenza autorizzata per la garanzia.",
 "Componenti di ricambio: 30-300 €; scambiatore: 150-400 €.",
 "Le caldaie a camera stagna vs aperta: la scelta dipende dal tiraggio del camino (verifica UNI 7129).",
 "UNI 7129; schede tecniche costruttori (Baxi, Vaillant, Ariston).",
 "Prima prova in caso di 'non scalda': verificare pressione impianto (1-1,5 bar) e flusso ACS: il 40% dei guasti sono idraulici, non elettronici."),
s("Caldaie","La caldaia a condensazione: il circuito della condensa",
 "Come la caldaia moderna recupera il calore latente dei fumi: i componenti aggiuntivi.",
 "Scambiatore secondario (condensatore) in acciaio inox o alluminio-silicio; scarico condensa in PVC/PP (acido, pH 3-5); il sifone con collegamento alla rete fognaria; la modulazione 1:6-1:10; il rendimento 90-109% (su potere calorifico inferiore).",
 "Nuove installazioni e sostituzioni obbligatorie (incentivi Conto Termico 3.0).",
 "Il recupero di calore vale il 10-15% in più: sul gas risparmia 100-200 €/anno.",
 "La condensa va smaltita correttamente: lo scarico a pioggia è vietato e corrosivo.",
 "Sostituzione caldaia a condensazione: 1.500-3.000 € installata.",
 "Le caldaie a condensazione installate in Italia: oltre 10 milioni (dati Anima).",
 "Ecodesign ERP; UNI 7129.",
 "La caldaia a condensazione rende AL MASSIMO con impianti a bassa temperatura (pannelli radianti, termosifoni dimensionati per 55-60°C): con radiatori vecchi a 80°C perde metà del vantaggio."),
s("Termostufe","La termostufa a pellet: anatomia del ciclo del combustibile",
 "La stufa che scalda l'acqua: serbatoio, coclea, braciere, scambiatore.",
 "Componenti: serbatoio pellet (10-30 kg), coclea di dosaggio (alimentazione continua), braciere con crogiolo (accensione elettronica), scambiatore a fumi (a fascio tubiero o a piastre), ventilatore tiraggio, canna fumaria in acciaio inox 316L (diam 80 mm), centralina con sonda temperatura e modulazione.",
 "Integrazione riscaldamento di ville e appartamenti (fino a 15-20 kW termici).",
 "Rendimento 85-92%: il pellet è il bio-combustibile più efficiente per residenziale.",
 "La canna fumaria è il punto critico: pulizia annuale obbligatoria (incrostazioni che riducono il tiraggio).",
 "Termostufa: 2.500-6.000 € installata; pellet: 280-350 €/t.",
 "Il mercato italiano del pellet (oltre 3 milioni di stufe installate).",
 "UNI 14785 (stufe a pellet); UNI 7129 per il collegamento idraulico.",
 "La termostufa scalda L'ACQUA dell'impianto, non è una stufa d'ambiente: richiede sempre vaso di espansione, pompa e valvola di sicurezza come una caldaia (impianto a norma)."),
s("Termocamini","Il termocamino: il focolare che diventa generatore idraulico",
 "Il camino che scalda l'acqua: potenza 15-25 kW con accumulo obbligatorio.",
 "Componenti: focolare in ghisa o acciaio, scambiatore ad acqua intorno alla camera di combustione (il 'serpentino' o la camera d'acqua), sportello a tenuta, presa aria esterna, valvola di sfogo termico (sicurezza contro il bollore), collegamento a serbatoio di accumulo (500-1000 l).",
 "Case con camino frequente e impianto idronico esistente.",
 "Combina atmosfera del fuoco visibile e integrazione con riscaldamento centralizzato.",
 "SENZA accumulo il termocamino è vietato per norma (bollore istantaneo: la potenza del fuoco supera sempre l'assorbimento istantaneo).",
 "Termocamino: 3.000-8.000 €; accumulo 1000 l: 800-1.500 €.",
 "Le installazioni central-europee (Austria, Germania) dove il termocamino+accumulo è lo standard.",
 "UNI 7129 (accumulo obbligatorio); UNI 10683? no: 'da verificare' camini.",
 "La regola d'oro: accumulo = 50-100 l per kW di potenza del focolare. Chi vende il termocamino senza accumulo vende un impianto fuorilegge."),
s("Climatizzatori","Il condizionatore (split): anatomia del ciclo frigorifero",
 "Come funziona la macchina che raffresca: compressore, condensatore, espansione, evaporatore.",
 "Il ciclo di Rankine inverso: compressore (rotativo o scroll), condensatore (scarica calore all'esterno), dispositivo di espansione (capillare o valvola elettronica EEV), evaporatore (assorbe calore dall'interno); il gas refrigerante R32 (GWP 675, obbligatorio dal 2025 per nuove macchine); l'inverter (modulazione continua del compressore).",
 "Raffrescamento estivo e riscaldamento invernale (pompa di calore 'aria-aria').",
 "Il ciclo frigorifero è lo stesso di tutte le macchine termiche: capirlo una volta = capirle tutte.",
 "Il rendimento crolla con le temperature esterne estreme (raffrescamento a +40°C, riscaldamento a −10°C).",
 "Split 12000 BTU (3,5 kW): 600-1.500 € installato; manutenzione: 80-150 €/anno.",
 "Il mercato italiano del condizionatore (oltre 10 milioni di split, dati ANTA? no: 'dati settore').",
 "Reg. UE 517/2014 (F-gas); UNI EN 378.",
 "La potenza si sceglie sul fabbisogno REALE (isolamento), non sui m2: una stanza ben coibentata da 25 m2 basta 9000 BTU, una vetrata esposta sud ne vuole 18000."),
s("Pompe di calore","La pompa di calore: il circuito frigorifero al servizio dell'acqua",
 "L'anatomia della macchina del futuro: refrigerazione + idronica.",
 "Componenti: compressore (rotativo, scroll o R290? no: 'a doppio stadio per climi freddi'), scambiatore esterno (evaporatore a piastre o 'aerotermo con ventole'), valvola a quattro vie (inversione caldo/freddo), scambiatore interno (a piastre saldobrasate o 'tubo in tubo'), modulo idronico (pompa, vaso espansione, valvole, sonda flusso), resistenza ausiliaria, centralina con modulazione.",
 "Riscaldamento invernale, raffrescamento estivo e ACS (aria-acqua).",
 "Una sola macchina per tutto: riscaldamento, raffrescamento, ACS con rendimento 300-500%.",
 "La complessità elettronica richiede installatori certificati F-gas e formazione specifica.",
 "PDC aria-acqua 8 kW: 4.000-8.000 € installata (prima degli incentivi).",
 "Le PDC R32 e R290 (propano, GWP basso) della nuova generazione 2024-2026.",
 "F-gas; EN 378; UNI 11300.",
 "Il componente più delicato: il compressore. La causa n.1 di guasto prematuro è l'installazione idraulica sbagliata (acqua sporca, aria nell'impianto): il filtro a Y e il spurgo accurato valgono più della marca del compressore."),
s("Scaldabagni","Lo scaldabagno: a gas, elettrico e a pompa di calore",
 "La produzione di ACS punto per punto: le tre tecnologie a confronto.",
 "A gas: camera aperta (tiraggio camino) o stagna (tiraggio forzato), scambiatore a fascio tubiero, bruciatatore con modulazione; elettrico: resistenza da 1,5-2,5 kW e serbatoio coibentato; a pompa di calore: compressore + scambiatore da 250-300 l, rendimento 2,5-3.",
 "Abitazioni senza impianto centralizzato, secondi bagni, B&B.",
 "Lo scaldabagno a gas istantaneo non ha accumulo: energia infinita ma portata limitata (11-17 l/min).",
 "Lo scaldabagno a gas in camera da letto è vietato (norma UNI 7129: solo camera stagna o ambienti idonei).",
 "Scaldabagno a gas: 400-900 €; elettrico: 150-400 €; a PDC: 800-1.800 €.",
 "Lo standard italiano dello scaldabagno a gas (milioni installati); il boom dello scaldabagno a PDC per i balconi? no: 'per l'ACS efficiente'.",
 "UNI 7129; ecodesign.",
 "Il dimensionamento rapido ACS: 1 persona = 40-60 l a 40°C di accumulo. Una famiglia di 4 con docce serali: accumulo 100-150 l (scaldabagno) o 150-200 l (scaldacqua centralizzato)."),
s("VMC tecnologia","La VMC centralizzata: anatomia della macchina e della rete",
 "Cosa c'è dentro la centralina e come è fatta la rete di distribuzione.",
 "Componenti centralina: scambiatore (controflusso in polipropilene o entalpico con membrana), due ventilatori EC (mandata e ripresa), filtri G4/F7, bypass estivo (sblocco gratuito), sonda umidità/CO2 opzionale, serranda anti-ritorno; rete: canalizzazione in acciaio zincato/flessibile o rigida (Ø 75-160 mm), bocchette a flusso continuo (camera 30-60 m³/h, servizi 20-40 m³/h), silenziatori.",
 "Case nuove e ristrutturazioni profonde (obbligo quasi-passivo).",
 "Il cuore della casa sana: recupera l'80-92% del calore e cambia l'aria senza aprire le finestre.",
 "La rete mal progettata (curve strette, diametri sbagliati) rende rumorosa e inefficiente la macchina migliore.",
 "VMC centralizzata casa 150 m²: 3.000-7.000 € installata.",
 "Le VMC a flusso continuo con bocchette a regolazione (standard italiano).",
 "UNI 10339; DM 26/06/2015.",
 "Il controllo essenziale a fine installazione: misura del portata con anemometro a ogni bocchetta (deve corrispondere al progetto ±10%). Senza misura non c'è collaudo."),
s("Canne fumarie","Canne fumarie e camini: materiali e tiraggio",
 "Il camino corretto: acciaio inox 316L, coibentazione e il calcolo del tiraggio.",
 "Materiali: acciaio inox 316L (resistenza acidi condensa), coibentato (doppia parete, isolamento in lana di roccia); sezioni: caldaia 110-130 mm, stufa pellet 80 mm, camino aperto secondo sezione focolare (≥1/10-1/15 del focolare); il tiraggio dipende da altezza (min 4 m sopra il generatore) e temperatura.",
 "Ogni generatore a fiamma (caldaia, stufa, camino, termocamino).",
 "La canna fumaria giusta garantisce sicurezza ed efficienza: il tiraggio insufficiente soffoca la fiamma e riempie di monossido.",
 "Le canne fumarie esistenti in muratura spesso non sono idonee per a condensazione (acido corrosivo).",
 "Canna fumaria coibentata: 60-150 €/ml installata.",
 "Le verifiche periodiche dei camini (spazzacamino) e le norme antincendio (UNI 10683? no: 'requisiti canne fumarie da verificare').",
 "UNI 7129; UNI EN 1856 (canne fumarie metalliche).",
 "Il test del tiraggio: fiamma accesa alla base della canna (tiraggio 'a candela'): se la fiamma vira verso l'interno, la canna va rifatta. Mai operare 'a tentativi' con i generatori a fiamma."),
]

# ===========================================================================
# L1 — MATERIALI E COMPONENTI DELL'IMPIANTISTICA
# ===========================================================================
MATERIALI_IMPIANTI = [
s("Tubi acqua","I tubi per l'acqua: rame, multistrato, PEX, PP-R, acciaio",
 "I materiali della rete idraulica: dove usarli e dove evitarli.",
 "Rame (rigido e flessibile): eterno, batteriostatico, costoso (6-15 €/m), attenzione alla corrosione per contatto con cls/acciaio; multistrato PEX-Al-PEX (16-32 mm): il più usato in residenziale (1,5-4 €/m), posa rapida con raccordi a pressare; PEX (rosso/blu): economico, per pannelli radianti; PP-R (saldato a caldo): economico e resistente, per esterno e industriale; acciaio zincato/inox: per reti antincendio e industriali.",
 "Adduzione acqua potabile, scarichi tecnici, antincendio, irrigazione.",
 "Ogni materiale ha il suo posto: il multistrato in residenziale, il rame in pregiato, il PP-R in industriale.",
 "Il rame rubato nei cantieri: valutare alternative nei luoghi a rischio.",
 "Prezzi indicativi al metro per diametro 16-20.",
 "Le reti in multistrato a collettore 'a pettine' nelle case moderne.",
 "UNI EN 1057 (rame); UNI 11344 (multistrato); UNI EN ISO 15874 (PP-R).",
 "Il multistrato NON si lascia all'aria nel solaio: protezione UV e meccanica obbligatoria. La guaina corrugata non è optional."),
s("Tubi gas","I tubi per il gas: acciaio, rame, multistrato marcato",
 "La rete gas: i materiali ammessi e le regole di posa.",
 "Acciaio (saldato o filettato): il tradizionale eterno; rame con marcatura gialla 'GAS'; multistrato con marcatura specifica gas (verde/giallo); i giunti a pressare ammessi in nuova installazione; la verifica di tenuta obbligatoria a fine lavori (UNI 11144).",
 "Reti gas interne per caldaie, cucine, termostufe.",
 "La tenuta della rete gas è vita: i materiali giusti e le prove giuste sono non negoziabili.",
 "Le reti esistenti in gomma o ferro vecchio sono pericolo reale.",
 "Rete gas interna appartamento: 300-900 €; rilevatore gas certificato: 60-150 €.",
 "Le verifiche triennali obbligatorie (legge gas).",
 "UNI 7129; UNI 11144 (rilevatori).",
 "Ogni nuova rete gas va provata in pressione (aria) con manometro: 15 minuti senza caduta. Chi non fa la prova non ha installato: ha messo in pericolo."),
s("Isolamento tubazioni","L'isolamento delle tubazioni: spessori e materiali",
 "Il cappotto dei tubi: dove obbligatorio, di quanto e con cosa.",
 "Materiali: elastomero espanso (gomma, spessore 6-13 mm), polietilene espanso (PE-X, 6-20 mm), lana minerale (impianti industriali); obbligatorio su: tubazioni ACS (contro perdite e crescita legionella), tubazioni riscaldamento in locale non riscaldato, tubazioni frigorifere (contro condensa); il fattore λ isolante ≤0,045 W/mK.",
 "Impianti idraulici e termici di ogni edificio.",
 "Un tubo non isolato in solaio perde il 10-20% del calore: l'isolamento ripaga in 1-2 anni.",
 "L'isolamento mal posato (giunti scoperti) vale meno della metà.",
 "Isolamento tubo: 2-5 €/ml materiale.",
 "Le prescrizioni UNI/TS 11300-2 sulle perdite dei tubi (fino al 20% della resa).",
 "UNI EN ISO 12241 (isolamento termico).",
 "L'acqua calda deve arrivare in 25 secondi e a temperatura: i tubi lunghi senza isolamento e senza ricircolo sono il male assoluto dell'energia e del comfort."),
s("Raccordi","I raccordi: pressare, saldare, a innesto, filettare",
 "Come si uniscono i tubi: le 4 tecniche e quando usarle.",
 "Pressare (multistrato e rame): pinza a pressare, curve 10-80 €; saldare (rame con cannello, PP-R con polifusore 50-150 €): giunzione a tenuta chimica; a innesto (PEX con manicotto e anello): rapido ma non smontabile; filettare (acciaio): teflon e attrezzatura classica.",
 "Ogni giunzione di ogni impianto idraulico e gas.",
 "La pressatura moderna: un operaio giunziona 50 punti al giorno con affidabilità testata.",
 "La pressatura sbagliata (ganasce sporche, tubo non a fondo) è la perdita n.1 dei cantieri moderni.",
 "Pinza a pressare: 100-400 €.",
 "Le pressacavi? no: le presse radiali e le presse a morsetto per multistrato.",
 "UNI 11344 (pressione minima per giunzioni).",
 "La regola del professionista: una giunzione visibile vale dieci nascoste. E una giunzione inaccessibile deve essere pressata DUE volte (sicurezza) o saldata."),
s("Valvole","Le valvole dell'impianto idraulico: sfera, detentore, termostatica, miscelatrice",
 "I rubinetti che regolano l'acqua: i 6 tipi che devi conoscere.",
 "Valvola a sfera (apertura/chiusura totale, il nuovo standard); valvola di detenzione (regolazione fine del flusso); valvola termostatica (testina a cera/liquido, mantiene la temperatura di mandata dei corpi scaldanti); valvola miscelatrice (mescola caldo/freddo per l'ACS antiscottatura); valvola di non ritorno (senso unico obbligatorio su circolatori e sistemi); valvola di sfogo aria (sfiato automatico nei punti alti).",
 "Collettori, corpi scaldanti, impianti ACS, idronici.",
 "Le valvole giuste al posto giusto: il 50% dei malfunzionamenti idronici sono valvole sbagliate o assenti.",
 "Le testine termostatiche vanno disattivate in estate? no: 'i detentori chiusi lasciano l'aria': ogni valvola ha la sua logica d'uso.",
 "Valvole: 10-80 €/pz; testine termostatiche: 15-60 €.",
 "I collettori con valvole di detenzione e sfiato (standard multistrato).",
 "UNI EN 215 (testine termostatiche).",
 "Ogni impianto idronico va 'svuotabile': una valvola a sfera in basso e uno sfiato in alto per ogni zona. Chi non prevede lo svuotamento ha progettato un impianto non manutenibile."),
s("Collettori","I collettori (maschio/femmina) e la distribuzione a pettine",
 "Il cuore della distribuzione moderna: il collettore e i vantaggi del pettine.",
 "Collettore in ottone o acciaio inox con 2-12 uscite; ogni uscita con valvola di detenzione e sfiato; la logica 'un tubo per punto' (nessuna giunzione intermedia nel solaio); il dimensionamento: 1 uscita per punto erogazione.",
 "Impianti idraulici residenziali moderni (docce, bagni, cucine).",
 "Una perdita futura colpisce un solo punto, non tutto il solaio: manutenibilità assoluta.",
 "Il consumo di tubo è maggiore (30-50% in più di metri lineari).",
 "Collettore 8 vie: 60-150 €.",
 "Lo standard tedesco/italiano della distribuzione a pettine dagli anni 2000.",
 "UNI EN 1264? no: 'prassi progettuali'.",
 "Il collaudo della rete a pettine: la prova in pressazione si fa settore per settore con il collettore: isolare una zona alla volta trova il problema in minuti, non in giorni."),
s("Pompe e circolatori","Pompe e circolatori: come funzionano e come si scelgono",
 "Il cuore che muove l'acqua nei circuiti chiusi.",
 "Il circolatore ad alta efficienza (classe A): corpo bagnato o a rotore asciutto, modulazione PWM 0-10V; la curva pompa-carico: prevalenza = perdite di carico del circuito; le 3 velocità storiche vs la modulazione continua; l'installazione in mandata o ritorno con valvola non ritorno.",
 "Riscaldamento, raffrescamento, ACS con ricircolo, solare termico.",
 "Il circolatore modulante corretto riduce i consumi elettrici dell'80% rispetto ai vecchi a 3 velocità.",
 "Un circolatore sovradimensionato consuma e ronca; uno sottodimensionato non scalda l'ultimo termosifone.",
 "Circolatore A: 150-500 €; a rotore asciutto: 200-600 €.",
 "La sostituzione dei circolatori vecchi in Italia (milioni all'anno).",
 "Ecodesign ERP per circolatori.",
 "La regola di Tarabella? no: 'la pompa non si dimensiona sulla portata massima, ma sul punto di lavoro reale': chiedere SEMPRE la curva carico-pressione del circuito, non 'quanti kW serve'."),
s("Vasi espansione","Il vaso di espansione: il componente che salva l'impianto",
 "Come assorbire la dilatazione dell'acqua calda: dimensionamento e manutenzione.",
 "Vaso a membrana (10-100 l residenziale): gas (azoto o aria) pre-carica 0,5-1,5 bar; dimensionamento rapido: 8-10 l per ogni kW di potenza installata (o 5% del volume d'acqua); la precarica va verificata ogni 2 anni; il vaso aperto in solaio è obsoleto e sconsigliato.",
 "Ogni impianto idronico chiuso (riscaldamento, raffrescamento, PDC, solare termico).",
 "Il vaso espansione è la protezione n.1 contro il sovrappressione: l'impianto senza vaso muore in anni.",
 "La membrana perde gas nel tempo: la pressione cala e la valvola di sicurezza perde.",
 "Vaso espansione 12 l: 40-80 €; 24 l: 60-120 €.",
 "La causa n.1 dei 'perdita dalla valvola di sicurezza': vaso espansione morto (da verificare).",
 "UNI 7129; prassi costruttive.",
 "Il test di 10 secondi: toccare il vaso in funzione: la metà inferiore deve essere fredda (acqua), la superiore tiepida (gas). Se tutto freddo o tutto caldo: membrana rotta, sostituire."),
s("Componenti elettrici","I componenti elettrici dell'impiantista: quadri, magnetotermici, differenziali",
 "L'hardware elettrico che ogni impiantista tocca ogni giorno.",
 "Magnetotermico (protezione sovraccarico+corto: 6-63 A, curve B/C/D); differenziale (salvavita 30 mA, selettivo 300 mA per grossi impianti); contattore (comanda carichi potenti da circuiti di comando); relè termico (protezione motori); portafusibili; i cavi (H07V-K 1,5/2,5/4/6 mm², colori: nero/fase, blu/neutro, giallo-verde/tierra); i tubi corrugati 16-20 mm.",
 "Quadri impianto, quadri pompe, automazioni, VMC.",
 "Conoscere i componenti elettrici base permette all'idraulico di dialogare con l'elettricista (e viceversa).",
 "L'impiantista NON certifica l'impianto elettrico (serve abilitazione): il confine professionale è netto.",
 "Magnetotermico: 5-30 €; differenziale: 30-80 €; contattore: 15-60 €.",
 "I quadri di zona con differenziale dedicato (obbligatorio per bagni e cucine).",
 "CEI 64-8.",
 "La regola dell'impiantista: ogni macchina che tocca l'acqua (pompe, lavatrici, scaldabagni) deve essere alimentata da un differenziale 30 mA dedicato: la vita vale più del risparmio di un quadretto."),
]

# ===========================================================================
# L2 — DIMENSIONAMENTO TERMOTECNICO
# ===========================================================================
DIM_TERM = [
s("Fabbisogno","Il calcolo del fabbisogno termico: da dove si parte",
 "La prima pagina di ogni progetto termico: come si calcola il carico di progetto.",
 "Metodo: Q = Σ(U·A·ΔT) trasmisssione + 0,34·V·n·ΔT ventilazione; il ΔT di progetto = temperatura interna (20°C) − temperatura esterna di progetto (zona climatica: −5°C nord, −2°C centro, +2°C sud); gli apporti interni (persone, luci) e solari si sottraggono; il fabbisogno dinamico annuo usa i gradi-giorno (GG ENEA).",
 "Scelta del generatore, verifica legge 10, confronto involucri.",
 "Il carico di progetto è la base di TUTTO: generatore, tubazioni, corpi scaldanti si dimensionano su questo numero.",
 "La stima per m² (100 W/m² storica, 40-60 W/m² casa efficiente) è solo per preventivi, mai per il progetto.",
 "I gradi-giorno per comune sono pubblici (Enea).",
 "Casa 150 m², U medio 0,6, superficie dispersa 320 m², ΔT=24°C (zona E): Q_trasm = 0,6·320·24 ≈ 4.600 W + ventilazione ~1.400 W = ~6 kW di fabbisogno di picco.",
 "UNI/TS 11300; UNI EN 12831.",
 "Regola d'oro: chi dimensiona il generatore SENZA aver calcolato il fabbisogno sta giocando d'azzardo con i soldi del cliente."),
s("Generatore","Il dimensionamento del generatore: caldaia, PDC, ibrido",
 "Come si sceglie la potenza del cuore termico: mai 'un po' più grande tanto paga'... anzi sì ma no.",
 "Metodo: P_generatore = Q_fabbisogno · (1 + margine 10-20%); il MARGINE serve per il rapido ripristino dell'ACS (carico istantaneo) e il ricircolo; la PDC: P = fabbisogno a T_esterna di progetto con COP accettabile, spesso si accetta la copertura parziale al punto di progetto con integrazione (punti binari); l'ibrido: PDC dimensionata sul 60-80% del fabbisogno + caldaia sul picco.",
 "Ogni nuovo impianto termico.",
 "Il sovradimensionamento è il male: cicli di accensione brevi, consumi e usura (soprattutto caldaie a gas).",
 "Il sottodimensionamento PDC invernale richiede l'integrazione: va progettata, non scoperta a dicembre.",
 "La differenza di costo tra una caldaia da 24 e 35 kW: 100-200 € (inutile comprare il sovradimensionamento).",
 "La modulazione minima delle caldaie (3 kW) che convive coi fabbisogni da 4-6 kW delle case efficienti.",
 "UNI EN 12831; UNI/TS 11300.",
 "Il test professionale: chiedere 'qual è il fabbisogno di picco della casa?' Se l'installatore non sa rispondere, sta vendendo una macchina a caso. Il miglior investimento è l'audit, non il sovradimensionamento."),
s("Corpi scaldanti","Il dimensionamento dei corpi scaldanti: termosifoni e radiatori",
 "Quanti Watt serve per ogni stanza: il metodo dei ΔT nominali.",
 "Metodo: Q_corpo = carico stanza / correttivo; la potenza nominale dei radiatori è dichiarata a ΔT=50°C (mandata 75, ritorno 65, ambiente 20): con mandate basse (PDC 45°C, ΔT=25) la potenza reale cade del 50-60%: usare la formula del costruttore Q = Q_n·(ΔT/50)^n (n≈1,3); il numero di elementi = Q_stanza / potenza elemento.",
 "Ogni impianto a termosifoni.",
 "La formula del ΔT spiega il 90% dei 'termosifoni freddi con la PDC': non sono pochi, sono sottodimensionati per la temperatura di mandata.",
 "La verifica corretta richiede i dati del costruttore (le curve di rendimento).",
 "Radiatore alluminio 600 mm: 120-200 W/elemento a ΔT50; a ΔT25 serve il doppio degli elementi.",
 "Le case in PDC con radiatori raddoppiati (o radianti) per andare a 35-45°C.",
 "UNI EN 442 (radiatori).",
 "Il trucco pratico: con PDC a 45°C, progettare come se il carico raddoppiasse: termosifoni grandi e belli o pannelli radianti. Le ali? no: 'le piastre': chi mette la PDC coi termosifoni vecchi sottodimensionati ha buttato metà dell'incentivo."),
s("Radianti","Il dimensionamento del pavimento/soffitto radiante",
 "Il radiante si calcola per portata: il metodo UNI EN 1264.",
 "Metodo: il carico per stanza si copre con il 60-70% della superficie utile a portata media 40-60 W/m² (masso 100 W/m² pavimento, 90 soffitto); la temperatura di mandata 28-35°C (pavimento), 27-32°C (soffitto); il passo dei tubi (10-30 cm) regola la potenza: passo 10 cm ≈ 60-70 W/m², passo 20 cm ≈ 40-50 W/m²; la portata acqua: q = Q/(1,16·ΔT mandata-ritorno 4-6 K) in l/h.",
 "Case in PDC, ristrutturazioni con massetto, soffitti radianti per raffrescamento.",
 "Il radiante funziona a temperature irraggiamento: il comfort migliore con l'acqua più fredda possibile.",
 "Le perdite verso il basso (la trasmittanza verso il solaio) vanno isolate: senza isolamento il radiante scalda i vicini.",
 "Radiante in massetto: 40-80 €/m2 installato; soffitto radiante: 50-100 €/m2.",
 "Le 'zone radianti' con collettore dedicato e valvole termostatiche (obbligatorie).",
 "UNI EN 1264 (1-5).",
 "La verifica di cantiere: il termometro IR sulla superficie: il pavimento deve arrivare a 26-29°C in superficie (non bollente: irradia piano). Se il massetto scalda troppo in poche ore, il controllo è sbagliato: il radiante è lentezza programmata."),
s("ACS","Il dimensionamento dell'acqua calda sanitaria: accumuli, portate, ricircolo",
 "Quanta acqua calda serve davvero: il dimensionamento degli accumuli e delle reti ACS.",
 "Metodo: fabbisogno 40-60 l/persona/die a 40°C; accumulo: V = fabbisogno_punto × (60/ΔT_accumulo) [accumulo a 60°C vs uso 40°C: i litri utili sono il 50% in più]; la produzione istantanea (scaldabagno/caldaia a flusso): portata doccia 6-9 l/min a 38°C; il ricircolo obbligatorio per percorsi >15-20 m (pompa con timer/temperatura); la legionella: accumulo a 60-65°C, ricircolo monitorato, scarico settimanale >60°C ai punti più lontani.",
 "Abitazioni, condomini, hotel, palestre, uffici.",
 "L'ACS è il 30-40% della bolletta energetica: dimensionarla bene vale quanto l'involucro.",
 "Gli accumuli grandi mantengono meglio la temperatura? no: 'perdono': l'accumulo perde calore in proporzione al volume: scegliere l'accumulo GIUSTO.",
 "Accumulo 100 l: 150-400 €; scambiatore a fascio: +20-30% sulla caldaia.",
 "Le norme anti-legionella negli edifici pubblici (acqua a 50°C nei punti di erogazione con valvole termostatiche).",
 "UNI EN 806; linee guida ISS legionella.",
 "La regola dell'accumulo: meglio piccolo e spesso rinnovato che grande e stagnante. La legionella ama l'acqua ferma a 30-45°C: l'accumulo a 60°C con scarichi settimanali è il vaccino."),
s("VMC dimensionamento","Il dimensionamento della VMC: portate, diametri e perdite",
 "Come si calcola la rete di ventilazione: dal volume d'aria alla bocchetta.",
 "Metodo: portata ambiente = numero persone × 25-30 m³/h (o ricambi minimi UNI 10339); dimensionamento condotte: velocità 2-3 m/s nei principali, 1,5-2 nelle derivazioni (per limitare il rumore a <30 dB in camera); il diametro da Q e velocità: A = Q/v; perdite di carico: il metodo della lunghezza equivalente (curve = 2-4 m di condotto); la spinta disponibile della centralina (100-300 Pa).",
 "Nuove costruzioni, ristrutturazioni, uffici, scuole.",
 "La VMC silenziosa nasce dal calcolo: la velocità bassa nei rami finali è il segreto.",
 "I software di calcolo (anche gratuiti) aiutano, ma la verifica acustica finale resta la misura.",
 "La verifica: anemometro a ogni bocchetta (50-100 €).",
 "Le VMC con sonda CO2 che modulano le portate in base all'effettiva presenza.",
 "UNI 10339; UNI EN 13779.",
 "La regola pratica: la bocchetta in camera da letto deve essere appena udibile: se la senti, è troppo veloce. Ridurre il diametro? no: aumentare: la velocità scende col quadrato del diametro."),
s("Integrazione generatori","L'integrazione di generatori diversi: termocamino, termostufa, solare, caldaia",
 "Come fanno a convivere più generatori: il dimensionamento della logica, non solo delle macchine.",
 "Metodo: la logica a priorità (il generatore 'gratuito' o rinnovabile va in testa: solare termico -> termocamino/termosufa -> PDC -> caldaia); il bollitore con doppio scambiatore o serpentina; il dimensionamento dell'accumulo come 'cuscinetto' tra produzione intermittente e fabbisogno: accumulo = 50-100 l/kW di potenza intermittente (termocamino) o 20-40 l/m² di solare termico; la valvola/miscelatrice per temperature diverse.",
 "Impianti ibridi complessi: villa con camino, solare, PDC.",
 "L'accumulo giusto rende amici generatori diversi: ognuno lavora al suo turno.",
 "La logica di gestione elettronica va progettata PRIMA delle macchine.",
 "Valvole deviatrici: 150-400 €; centraline di gestione: 200-600 €.",
 "Gli impianti 'a cascata' delle case alpine (legna -> solare -> integrazione).",
 "UNI 7129; UNI EN 15316.",
 "La frase d'ordine: 'prima l'accumulo, poi i generatori'. Chi compra la macchina prima del serbatoio costruisce un puzzle senza cornice."),
s("Raffrescamento","Il dimensionamento del raffrescamento: carichi estivi e deumidifica",
 "L'estate si calcola come l'inverno: il carico di raffrescamento in 5 mosse.",
 "Metodo: Q_estivo = trasmissione (U·A·ΔT notturno) + irraggiamento finestre (W·SHGC) + carico interno (persone 60-80 W sensibili + apparecchi) + ventilazione; la deumidifica: la portata d'aria deve assorbire l'umidità interna (docce, cucina): la macchina lavora a 7°C di espansione per condensare; il raffrescamento radiante gestisce il SENSIBILE, la VMC gestisce il LATENTE (umidità).",
 "Climatizzazione estiva di case e uffici.",
 "La deumidifica è metà del comfort estivo: una casa a 26°C e 45% UR è più fresca di una a 24°C e 70%.",
 "Il carico estivo è variabile: il dimensionamento pieno per il picco di 3 giorni è sprecato.",
 "Il concetto di 'gradi-ora' estivi (pubblico ENEA).",
 "Raffrescamento radiante + VMC con deumidifica: la coppia standard delle case efficienti.",
 "UNI EN ISO 13791/13792.",
 "La regola del comfort: la temperatura operativa (aria + superfici) è la realtà percepita: un radiante a 24°C dà la freschezza di un condizionatore a 21°C, senza spifferi e con meno energia."),
s("Esempio completo","Esempio svolto: il dimensionamento termico di una villa di 180 m²",
 "Il progetto termico completo passo per passo, con i numeri veri.",
 "Fabbisogno: villa 180 m², zona E, U=0,45: Q = 0,45·380 m²·24 + 0,34·450·0,5·24 ≈ 4.100 + 1.840 ≈ 6 kW; generatore: PDC 8 kW (margine ACS) COP 3,5 a 35°C; corpi: radianti 45°C con passo 15 cm (45-55 W/m²) su 130 m²; ACS: accumulo 200 l a 60°C con ricircolo 15 m; VMC: 180 m² × 2,7 m × 0,5 ricambi = 250 m³/h; consumo stimato: 6.000 kWh termici / COP 3,5 ≈ 1.700 kWh elettrici ≈ 500 €/anno.",
 "Modello replicabile per qualsiasi residenza unifamiliare.",
 "L'esempio mostra la catena: fabbisogno -> macchina -> emissione -> aria -> costo finale.",
 "I numeri cambiano col clima e l'involucro: l'esempio è il metodo, non la tabella.",
 "Il metodo è gratuito: carta e UNI/TS 11300.",
 "Migliaia di ville italiane con questi numeri (Legge 10 2024).",
 "UNI/TS 11300; UNI EN 12831.",
 "Il controllo finale professionale: il consumo stimato deve corrispondere alla bolletta del primo anno: scostamenti >30% = errore di dimensionamento da scoprire, non da nascondere."),
]

# ===========================================================================
# L2 — DIMENSIONAMENTO FV, ACCUMULO, EOLICO
# ===========================================================================
DIM_FV = [
s("FV dimensionamento","Il dimensionamento del fotovoltaico: dal consumo ai kWp",
 "Quanti pannelli servono: la procedura completa con i numeri.",
 "Metodo: 1) consumo annuo in bolletta (kWh); 2) produzione specifica locale (kWh/kWp: 1.200-1.500 nord, 1.300-1.600 centro, 1.400-1.700 sud); 3) P_install = consumo × (autoconsumo_target)/(produzione specifica): es. 4.000 kWh/anno in centro con autoconsumo 70%: 4.000·0,7/1.400 ≈ 2 kWp minimi, ma 3-6 kWp è il range economico; 4) verifica superficie: 1 kWp ≈ 5-6 m² di tetto; 5) verifica carichi strutturali: 12-18 kg/m² (ok quasi sempre).",
 "Ogni edificio con tetto o area disponibile.",
 "La procedura dal consumo evita il classico errore 'il venditore ha detto 10 kWp' per una casa da 3.000 kWh.",
 "La produzione reale varia del ±15% col meteo: il contratto deve parlare di stime, non promesse.",
 "Simulatore PVGIS (gratuito) per i dati locali precisi.",
 "La casa media italiana (2.700 kWh/anno) con 3 kWp e autoconsumo 30%: ~1.300 kWh auto-usati + vendita del resto.",
 "CEI 0-21; UNI 9174.",
 "Regola pratica: il FV si dimensiona sul CONSUMO, il tetto è il vincolo, la batteria è l'optional. Chi parte dal tetto ('mettiamo 20 pannelli perché ci stanno') ha capito tutto al contrario."),
s("FV stringhe","Il dimensionamento delle stringhe e degli inverter",
 "Come si collegano i moduli: tensioni, correnti e il rapporto inverter.",
 "Metodo: la tensione di stringa: somma delle Vmp dei moduli in serie: es. 10 moduli × 34 V = 340 Vmp (entro il MPPT dell'inverter 200-800 V); la Voc massima inverno (Voc aumenta col freddo: +0,3%/°C sotto ai 25°C: 10×41 V×1,1 ≈ 450 V < 1000 V massimo inverter); la corrente: le stringhe in parallelo sommano le correnti (Imodulo 11 A × 2 stringhe = 22 A); il rapporto DC/AC: 1,1-1,3 (es. 6 kWp con inverter 5 kW) per sfruttare le ore di punta; l'ombreggiamento: i diodi di bypass limitano le perdite parziali.",
 "Impianti residenziali e industriali.",
 "La verifica tensione freddo-caldo è la regola che evita i guasti: la Voc invernale non deve superare il massimo dell'inverter.",
 "Le curve reali di potenza variano: il rapporto 1,2 è un compromesso, non una legge.",
 "I software di stringatura gratuiti dei produttori di inverter.",
 "Gli impianti con rapporto 1,3: perdita di resa <2% rispetto a 1,0 con costo inverter inferiore.",
 "CEI 0-21; CEI 82-25 (da verificare: guida installazione FV).",
 "Il controllo d'installazione: la Voc di stringa si misura PRIMA del collegamento all'inverter: la lettura deve stare nel range MPPT. Un errore qui brucia l'inverter in 30 secondi."),
s("FV cablaggi","Il cablaggio DC e AC del fotovoltaico: sezioni e protezioni",
 "I cavi del FV: dimensionamento rapido e le protezioni obbligatorie.",
 "DC: la corrente di stringa (10-15 A) richiede cavi 4-6 mm² (rame, isolamento doppio, nero/rosso); la caduta di tensione DC <2%; i connettori MC4 (o compatibili certificati); AC: l'inverter 5 kW trifase? no monofase: 22 A → cavo 6 mm², magnetotermico 25 A, differenziale tipo B (le correnti del FV sono continue: il tipo A non basta); scaricatori SPD tipo 1+2 se edificio con LPS; la messa a terra dei telai.",
 "Ogni impianto fotovoltaico.",
 "Il dimensionamento elettrico corretto è la sicurezza: un cavo sottodimensionato surriscalda e brucia.",
 "Il differenziale tipo B costa 200-400 €: il risparmio qui è falso.",
 "Cavi solari 6 mm²: 2-4 €/ml.",
 "Gli impianti con SPD e tipo B conformi CEI 0-21.",
 "CEI 0-21; CEI 64-8.",
 "La regola: nel FV il differenziale è tipo B, lo scaricatore è presente, la messa a terra è fatta. Le tre cose valgono più della marca dei pannelli."),
s("Accumulo","Il dimensionamento dell'accumulo in batteria: autoconsumo e backup",
 "Quanti kWh di batteria servono: il calcolo dal profilo di consumo.",
 "Metodo: batteria = consumo notturno (kWh) / DoD (80-90%): casa 3.000 kWh/anno con 40% di consumo serale/notturno: 1.200 kWh/anno ÷ 365 = 3,3 kWh/notte → batteria 4-5 kWh; per l'autoconsumo massimo (>70%): batteria 8-10 kWh o gestione carichi (PDC, scalda-acqua); il backup di emergenza: la potenza dell'inverter ibrido (3-10 kW) conta più dei kWh; il ciclo di vita: 6.000 cicli × 4 kWh = 24.000 kWh erogabili.",
 "Ville con FV, case in zone con blackout, B&B.",
 "La batteria giusta si calcola sul consumo NOTTURNO: il giorno il FV copre, la notte serve la batteria.",
 "L'accumulo perde il 10-15% di resa (carica/scarica): l'autoconsumo 100% è matematicamente impossibile.",
 "Batteria 5 kWh: 2.000-3.500 €; 10 kWh: 4.000-7.000 €.",
 "Le batterie LFP (fosfato ferro-litio) che stanno sostituendo il NMC nel residenziale.",
 "UNI CEI 0-16; CEI 0-21.",
 "Il quesito professionale prima della batteria: 'quanto consumi di notte?' Chi non sa rispondere vende batterie a caso. E la batteria si ripaga in 8-15 anni: il backup e le tariffe dinamiche accorciano, il prezzo dell'energia li determina."),
s("Eolico","Il dimensionamento dell'eolico: la curva di potenza e la realtà dei siti",
 "Quando il vento conviene: la fisica onesta del microeolico.",
 "Metodo: la curva di potenza della turbina: P = 0,5·ρ·A·v³·Cp (A = πr², Cp = 0,35-0,45): la potenza cresce col CUBO della velocità (da 5 a 7 m/s: +140%); il vento reale al suolo è il 60-70% del vento anemometrico a 10 m; la produzione richiede la mappa del vento del sito (atlanti ENEA); il microeolico residenziale (5-10 kW) rende 800-2.500 kWh/kW/anno SOLO in siti ventosi (coste, colline esposte).",
 "Aziende agricole in collina, coste, isole.",
 "La fisica è chiara: il cubo della velocità premia i siti veri e punisce quelli speranzosi.",
 "Il 90% dei siti residenziali italiani ha vento insufficiente: il microeolico è spesso una delusione costosa (spirito critico richiesto).",
 "Le torri anemometriche (500-2.000 €) per la misura di 12 mesi.",
 "Le isole minori (Ventotene, Pantelleria) dove l'eolico è la regola; i microeolici 'da giardino' abbandonati.",
 "Nessuna specifica: fisica + certificazione CE.",
 "La regola d'oro dell'eolico: 'misura per un anno prima di comprare'. Il venditore che promette 3.000 kWh dal vento 'che c'è sempre' vende fuffa: il vento che basta vive in pochi siti, e va DIMOSTRATO."),
s("Ibridi","I sistemi ibridi FV + batteria + rete + generatore: il dimensionamento integrato",
 "L'impianto che non si ferma mai: logica e dimensionamento degli ibridi.",
 "Metodo: la gerarchia di priorità: FV -> batteria -> rete (se presente) -> generatore di backup (gasolio/GPL/biometano); il dimensionamento dell'autonomia: giorni senza sole × consumo giornaliero / DoD: 3 gg × 8 kWh / 0,8 = 30 kWh di batteria; il generatore di backup: potenza = carichi essenziali (frigo, luci, PDC ridotta): 5-10 kVA; l'energy manager che commuta le fonti senza interruzioni.",
 "Case isolate, agriturismi, rifugi, B&B, cantine? no: 'aziende con continuità richiesta'.",
 "L'ibrido corretto dà l'autonomia senza il diesel quotidiano: il generatore è l'ultima spiaggia, non la routine.",
 "La complessità di gestione richiede una centralina di supervisione professionale.",
 "Energy manager: 1.000-3.000 €; generatore backup: 2.000-8.000 €.",
 "I rifugi alpini con FV + batteria + generatore (il diesel accende una volta al mese).",
 "CEI 0-16; normativa connessione.",
 "La logica dell'ibrido: 'ogni fonte fa ciò che fa meglio'. Il FV copre il sole, la batteria la notte, il generatore l'emergenza. Chi fa tutto col generatore paga il triplo."),
s("Off-grid","Il dimensionamento off-grid: l'autonomia totale senza rete",
 "Vivere senza ENEL: la matematica dell'autonomia completa.",
 "Metodo: 1) bilancio energetico giornaliero: somma di tutti i consumi × ore (frigo 1,5 kWh/g, luci 0,5, PDC invernale 6-10...); 2) il FV dimensionato sul peggiore mese (dicembre: 1/3 della produzione estiva); 3) la batteria: 2-3 giorni di autonomia: (kWh/giorno × giorni) / DoD; 4) il backup (generatore) per le settimane di maltempo; es. casa efficiente inverno: 10 kWh/giorno → FV 6 kWp + batteria 30 kWh + generatore 8 kVA.",
 "Case isolate, baite, podere? no: 'podere' sì, postazioni remote.",
 "L'off-grid perfetto dà indipendenza e risparmio sulla tratta? no: 'sulla connessione' (chi evita il preventivo ENEL da 20k€).",
 "L'off-grid peggiora: la disciplina dei consumi è obbligatoria: niente pannelli elettrici? no: 'niente sprechi'.",
 "Il costo dell'off-grid serio: 20-60k€.",
 "Le comunità energetiche (CER) che portano il modello 'condiviso' nei paesi.",
 "CEI 0-16; normativa CER (ARERA).",
 "La verità dell'off-grid: non è 'staccare la spina', è 'diventare il proprio gestore'. Chi non vuole gestire l'energia non deve andare off-grid: la rete è un servizio, e pagarlo costa meno dell'indipendenza per molti."),
s("PDC dimensionamento","Il dimensionamento della pompa di calore: il metodo binario completo",
 "Come si dimensiona una PDC in 6 passi verificati.",
 "Metodo: 1) il fabbisogno termico di progetto (UNI EN 12831); 2) i punti bin: la tabella delle temperature esterne e le ore annue a ciascuna temperatura (bin di 2°C); 3) la COP a ciascun bin (dalle curve del costruttore): il rendimento annuo SCOP = Σ(produzione bin)/(Σ consumi bin); 4) la copertura: la PDC copre il 100% fino a una certa temperatura (punto di equilibrio), sotto serve integrazione; 5) il dimensionamento del campo sorgente (aerotermo: spazio, rumore, defrost); 6) la verifica ACS: il serbatoio e il ricircolo.",
 "La scelta tecnica principale delle nuove costruzioni italiane.",
 "Il metodo bin dà il rendimento REALE: il COP di targa è marketing, lo SCOP è fisica.",
 "I dati dei bin vanno da fonti climatiche locali (non tutti i costruttori li pubblicano).",
 "I software di calcolo del costruttore (gratuiti) che integrano i bin.",
 "Le PDC dimensionate 'a spanne' che consumano il doppio del previsto: il motivo è quasi sempre l'assenza del calcolo bin.",
 "UNI EN 14825 (SCOP); UNI/TS 11300.",
 "Il quesito professionale: 'mi mostri lo SCOP calcolato col metodo bin per la mia zona climatica?' Chi non risponde vende sulla fiducia. La PDC è la macchina del decennio: va scelta col calcolo, non col volantino."),
s("Solare termico","Il dimensionamento del solare termico: collettori e accumulo",
 "L'acqua calda dal sole: come si dimensiona l'impianto solare termico.",
 "Metodo: l'accumulo: 40-75 l/m² di collettore piano (standard 50 l/m²); i collettori: 1,5-2 m² per persona in famiglia; il contributo solare: 40-60% del fabbisogno ACS annuo; l'orientamento: sud ±45°, inclinazione 30-60°; l'integrazione: con caldaia a condensazione o PDC (il solare scalda, l'integrazione 'rifinisce'); l'impianto a circolazione forzata con scambiatore a fascio o a piastre.",
 "Abitazioni, condomini, hotel, piscine (riscaldamento).",
 "Il solare termico è la tecnologia più semplice e robusta: rende per 25 anni con manutenzione minima.",
 "Il gelo: i collettori vanno svuotati? no: 'l'impianto con glicole' gestisce il gelo, ma la manutenzione del fluido è obbligatoria.",
 "Impianto famiglia 4 persone: 4 m² collettori + accumulo 200 l: 3.000-5.000 € installato.",
 "Il Conto Termico 3.0 incentiva il solare termico (premio al netto).",
 "UNI EN 12976; UNI/TS 12977.",
 "Il ritorno del solare termico: nel 2020 sembrava morto, nel 2025 torna forte per la semplicità. Le regole: accumulo giusto, orientamento giusto, integrazione corretta. L'errore classico: i collettori troppo grandi per l'accumulo (estate = bollore)."),
s("Esempio FV","Esempio svolto: impianto FV 6 kWp con accumulo 5 kWh per una famiglia tipo",
 "Il progetto FV completo, dal tetto alla bolletta.",
 "Dati: consumo 3.600 kWh/anno, villa centro Italia (produzione 1.450 kWh/kWp); 1) P = 6 kWp (superficie 36 m² sud, tetto ok); 2) produzione = 8.700 kWh/anno; 3) autoconsumo senza batteria 30%: 2.600 kWh; con batteria 5 kWh: 60%: 5.200 kWh; 4) risparmio: 5.200 × 0,30 € = 1.560 €/anno + vendita eccedenza 3.500 × 0,10 € = 350 €; 5) costo: 9.000 € (FV+batteria) - incentivo eventuale; 6) ritorno: ~5-6 anni senza incentivo, 3-4 con Conto Termico/cessione credito.",
 "Modello replicabile per il 90% delle ville italiane.",
 "L'esempio dimostra la catena: tetto -> produzione -> autoconsumo -> bolletta -> ritorno.",
 "I prezzi dell'energia variano: il calcolo va rifatto coi prezzi attuali.",
 "PVGIS + listini installatori.",
 "La diffusione del FV+accumulo in Italia (dati GSE 2024-2025: oltre 1,5 milioni di impianti).",
 "CEI 0-21; GSE.",
 "Il controllo professionale: il preventivo FV deve contenere la simulazione di produzione (PVGIS o equivalente) firmata: la promessa verbale 'produrrà tanto' non vale. E il primo confronto dopo 12 mesi tra produzione reale e stimata è la vera verifica dell'installatore."),
]

# ===========================================================================
# GENERAZIONE
# ===========================================================================
NUOVI = {
 "MACCHINE_TERMICHE_TECNOLOGIA_PACK": ("Tecnologia delle macchine termiche", "FACOLTA_IMPIANTI_ENERGIA", "L1",
   "L'anatomia delle macchine: caldaia, termostufa, termocamino, condizionatore, pompa di calore, scaldabagno, VMC, canne fumarie.", MACCHINE),
 "MATERIALI_COMPONENTI_IMPIANTISTICA_PACK": ("Materiali e componenti dell'impiantistica", "FACOLTA_IMPIANTI_ENERGIA", "L1",
   "Tubi, raccordi, valvole, collettori, pompe, vasi, isolamenti e componenti elettrici dell'impiantista.", MATERIALI_IMPIANTI),
 "DIMENSIONAMENTO_TERMOTECNICO_PACK": ("Dimensionamento degli impianti termotecnici", "FACOLTA_IMPIANTI_ENERGIA", "L2",
   "Le procedure complete per dimensionare fabbisogno, generatori, corpi scaldanti, radianti, ACS, VMC e impianti integrati, con esempi svolti.", DIM_TERM),
 "DIMENSIONAMENTO_FV_EOLICO_ACCUMULO_PACK": ("Dimensionamento di fotovoltaico, eolico e accumulo", "FACOLTA_IMPIANTI_ENERGIA", "L2",
   "Le procedure complete per dimensionare FV, stringhe, inverter, batterie, eolico, sistemi ibridi e off-grid, con esempi svolti.", DIM_FV),
}
for nome, (titolo, facolta, livello, desc, data) in NUOVI.items():
    pdir = os.path.join(UNI, nome)
    os.path.join(pdir, "schede") and os.makedirs(os.path.join(pdir, "schede"), exist_ok=True)
    with open(os.path.join(pdir, "schede", "schede.jsonl"), "w", encoding="utf-8") as f:
        for it in data:
            f.write(json.dumps(it, ensure_ascii=False) + "\n")
    with open(os.path.join(pdir, "README.md"), "w", encoding="utf-8") as f:
        f.write(f"# {titolo}\n\n{desc}\n\nSchede: {len(data)}\n")
    with open(os.path.join(pdir, "COURSE.yaml"), "w", encoding="utf-8") as f:
        f.write(f"corso: \"{titolo}\"\nfacolta: \"{facolta}\"\nlivello: \"{livello}\"\n"
                f"schede: {len(data)}\nformato: \"JSONL\"\nlingua: \"it\"\n"
                f"schema_campi: [categoria, nome, descrizione, tecnologia, applicazioni, vantaggi, limiti, costi_e_economia, casi_real_world, normative, note_cantiere]\n")

for fac, nomi in {"FACOLTA_IMPIANTI_ENERGIA": list(NUOVI)}.items():
    with open(os.path.join(UNI, "CURRICULUM", f"{fac}.md"), "a", encoding="utf-8") as f:
        f.write("\n## Corsi del giro impiantistico (2026-10-01)\n")
        for n in nomi:
            f.write(f"- {n}\n")

with open(os.path.join(UNI, "INDEX.md"), "a", encoding="utf-8") as f:
    f.write("\n## Corsi del giro impiantistico (2026-10-01)\n\n")
    for n, (t, fa, li, d, da) in NUOVI.items():
        f.write(f"- {n} ({len(da)} schede)\n")

print("GIRO IMPIANTISTICO:")
for n, (t, fa, li, d, da) in NUOVI.items():
    print(f"  {n}: {len(da)} schede")
