# -*- coding: utf-8 -*-
"""Universita dell'Edilizia - corsi formulario: matematica, strutture, fisica impianti."""
import json, os

ROOT = os.path.abspath(os.path.dirname(__file__))
UNI = os.path.join(ROOT, "UNIVERSITA_EDILIZIA")

def s(cat, nome, descrizione, tecnologia, applicazioni, vantaggi, limiti, costi, casi, normative, note):
    return {"categoria": cat, "nome": nome, "descrizione": descrizione,
            "tecnologia": tecnologia, "applicazioni": applicazioni,
            "vantaggi": vantaggi, "limiti": limiti, "costi_e_economia": costi,
            "casi_real_world": casi, "normative": normative, "note_cantiere": note}

# ===========================================================================
# L0 — MATEMATICA PER COSTRUIRE
# ===========================================================================
MATEMATICA = [
s("Unita di misura","Sistema internazionale e unità di misura in edilizia",
 "Le unità fondamentali e come si combinano nel lavoro quotidiano: senza queste, ogni formula è pericolosa.",
 "SI: lunghezza (m), massa (kg), tempo (s), forza (N = kg·m/s²), pressione (Pa = N/m²), energia (J), potenza (W = J/s), momento (N·m). Multipli: kN (10³ N), MPa (10⁶ Pa = N/mm²), kPa (10³ Pa).",
 "Ogni calcolo: strutture, impianti, estimi, topografia.",
 "Un sistema unico: chi converte bene non sbaglia mai un ordine di grandezza.",
 "Le unità anglosassoni (psi, lb, ft) nei cataloghi esteri: servono tabelle di conversione.",
 "Tavole di conversione gratuite; app per smartphone (ConvertPad).",
 "1 MPa = 10,2 kgf/cm² (la 'pressione atmosferica' storica); 1 bar = 100 kPa.",
 "UNI ISO 80000 (grandezze e unità).",
 "Prima regola di ogni verifica: riscrivere il risultato con l'unità di misura. Un numero senza unità non è un risultato, è un sospetto."),
s("Errori e cifre significative","Gli errori: cifre significative, arrotondamenti, ordini di grandezza",
 "Come trattare i numeri quando i dati non sono perfetti: la matematica del 'quanto basta'.",
 "Cifre significative (il risultato non può avere più cifre significative dei dati); arrotondamento in eccesso/difetto; stima dell'ordine di grandezza (10⁰, 10¹, 10²...); errore relativo = errore/valore.",
 "Ogni calcolo di cantiere e di studio.",
 "Un calcolo con 3 cifre significative finisce lì: promettere il millesimo su dati al decimo è disonestà tecnica.",
 "I software danno 8 decimali: il rischio è fidarsi ciecamente.",
 "Nessun costo: è disciplina mentale.",
 "Il ponte con 'carico calcolato 4.371,28 kN' su dati da norma: le cifre extra sono teatro.",
 "Buona pratica UNI rilievi e misure.",
 "Regola pratica: nel preventivo arrotonda i prezzi unitari all'euro, nei calcoli strutturali conserva un decimale in più e basta."),
s("Algebra","Algebra di base: equazioni, proporzioni, percentuali",
 "Le operazioni che governano computi, scale, dosaggi e rendimenti.",
 "Equazioni di primo grado (ax+b=0); proporzioni (a:b = c:d); percentuali e sconti; regole di tre dirette e inverse; sistemi semplici a 2 incognite.",
 "Computi metrici, dosaggi cls, scale di disegno, contabilità lavori.",
 "La regola di tre risolve il 70% dei problemi di cantiere quotidiani.",
 "Le proporzioni 'inverse' (più operai = meno giorni) vanno riconosciute, non assunte.",
 "Nessun costo: carta e calcolatrice.",
 "Il dosaggio: 350 kg cemento / m³ -> per 4 m³ servono 1.400 kg (regola di tre diretta).",
 "Nessuna norma: competenza di base.",
 "La proporzione è il linguaggio segreto del computo metrico: chi la padroneggia verifica ogni preventivo in secondi."),
s("Geometria piana","Geometria piana: aree e perimetri delle figure del cantiere",
 "Rettangoli, triangoli, cerchi, trapezi: calcolare superfici di lavoro senza software.",
 "Aree: rettangolo b·h; triangolo b·h/2; trapezio (B+b)·h/2; cerchio πr²; corona circolare π(R²-r²); perimetri: 2(b+h); 2πr; ipotenusa √(a²+b²).",
 "Misura pavimenti, coperture, intonaci, terreni, pannelli fotovoltaici.",
 "Le superfici si calcolano a mano in cantiere: chi non le sa calcola sprechi o ordinazioni sbagliate.",
 "Le figure reali non sono mai perfette: aggiungere sempre uno scarto (5-10%).",
 "La calcolatrice tascabile resta lo strumento n.1 del capocantiere.",
 "Il teorema di Pitagora: dati due lati di un angolo retto trova il terzo (il muro che 'taglia' in diagonale).",
 "Nessuna: geometria euclidea.",
 "Regola d'oro cantiere: 'misura due volte, taglia una'. Le formule non perdonano l'errore di lettura del metro."),
s("Geometria solida","Geometria solida: volumi dei corpi della costruzione",
 "Parallelepipedi, cilindri, piramidi, tronchi di cono: quanto materiale serve davvero.",
 "Volumi: parallelepipedo a·b·c; cilindro πr²h; sfera 4/3πr³; tronco di cono πh(R²+Rr+r²)/3; piramide A·h/3.",
 "Calcolo cls da ordinare, scavi, riempimenti, serbatoi, cumuli di materiale.",
 "Il volume giusto evita il doppio trasporto: il cls in eccesso si paga due volte (acquisto + smaltimento).",
 "I cumuli di terreno 'si siedono': il volume sciolto è 1,2-1,4 volte quello in sito.",
 "Il cls si compra a m³: l'errore di volume è l'errore più costoso del cantiere.",
 "Cumulo di sabbia conico: V = πr²h/3 (un terzo del cilindro).",
 "Nessuna.",
 "Trucco da cantiere: il cumulo conico misurato in 10 secondi (raggio e altezza) dà il volume con errore <5%: la geometria solida è un risparmiatore di soldi."),
s("Trigonometria","Trigonometria applicata: pendenza, altezze, triangoli qualsiasi",
 "Sen, cos, tan: lo strumento per misurare ciò che non si può arrivare a toccare.",
 "Rapporti nel triangolo rettangolo (sen = cateto opposto/ipotenusa, cos = adiacente/ipotenusa, tan = opposto/adiacente); teorema dei seni a/sinA = b/sinB = c/sinC; teorema del coseno c² = a²+b²-2ab·cosC; conversione pendenza: % = tan(α)·100, gradi = arctan(%/100).",
 "Tracciamenti, rilievi indiretti, coperture inclinate, scavi, topografia.",
 "Misura altezze e distanze senza salire: la trigometria è il GPS del geometra.",
 "Gli angoli in gradi vs radianti nei software: il settaggio sbagliato rovina il calcolo.",
 "La calcolatrice scientifica (50 €) risolve il 90% dei problemi.",
 "Pendenza 100% = 45°; pendenza 30° = 57,7%: le segnaletiche stradali e le coperture parlano lingue diverse.",
 "Nessuna.",
 "Regola mnemonica: SOH-CAH-TOA (Sen=Opp/Ipo, Cos=Add/Ipo, Tan=Opp/Add). Impararla una volta per sempre."),
s("Vettori e coordinate","Vettori, coordinate e sistema cartesiano in cantiere",
 "Spostamenti, forze e coordinate: la matematica dei 'quanto in quale direzione'.",
 "Vettori: componenti (x,y); modulo √(x²+y²); direzione arctan(y/x); somma per componenti; coordinate cartesiane e polari; distanza tra punti d = √((x₂-x₁)² + (y₂-y₁)²).",
 "Tracciamenti con stazione totale, calcolo risultanti di forze, spostamenti in pianta.",
 "Le forze del vento e del sisma sono vettori: chi non somma i vettoli sbaglia la verifica.",
 "I segni delle componenti: il quadrante sbagliato sposta il punto di 180°.",
 "Nessun costo: è il fondamento di ogni strumento topografico.",
 "La somma di due spinte di 3 kN e 4 kN perpendicolari è 5 kN (terna pitagorica): la verifica immediata.",
 "Nessuna.",
 "Prima di ogni tracciamento: disegnare il sistema di coordinate su carta. Il punto giusto nel sistema sbagliato è un punto sbagliato."),
s("Matrici","Matrici e sistemi di equazioni: il cuore del calcolo strutturale",
 "Perché il metodo degli elementi finiti parla matriciale: cosa succede sotto il software.",
 "Matrice (tabella di numeri); moltiplicazione riga×colonna; matrice di rigidezza K (forze = rigidezza × spostamenti); sistemi lineari (Gauss); autovalori (modi di vibrare).",
 "Comprensione del FEM; verifica dei risultati; errori di modellazione.",
 "Capire che K·u = F è la legge di Hooke per tutta la struttura: chi la capisce non è schiavo del software.",
 "Il calcolo matriciale a mano è lento: serve solo la comprensione, non l'esecuzione.",
 "I corsi di algebra lineare (gratuiti online) bastano.",
 "Il modo di vibrare n.1 di un edificio è il suo 'tono di voce': l'autovalore più basso.",
 "Nessuna norma: metodo matematico.",
 "Per l'LLM: quando un utente carica una relazione FEM, chiedere sempre: mesh, vincoli, carichi? Il controllo delle tre cose trova il 90% degli errori."),
s("Funzioni e grafici","Funzioni e lettura dei grafici tecnici",
 "Diagrammi momento-taglio, curve di carico, andamenti termici: leggere e capire i grafici.",
 "Funzione y = f(x); lettura di pendenza (tangente = derivata); area sotto la curva (integrale = somma continua); diagrammi M, V, N per le travi; scale logaritmiche.",
 "Relazioni di calcolo, prove di laboratorio, monitoraggi, energetica.",
 "Il diagramma del momento flettente 'disegna' la trave: chi lo legge capisce la struttura a colpo d'occhio.",
 "Le scale logaritmiche (spettri sismici) leggono diversamente: i ragazzi si confondono.",
 "I diagrammi si fanno a mano: il metodo delle 'forze' del progettista esperto.",
 "Il diagramma del taglio = derivata del momento: la pendenza del momento è il taglio (sempre vero).",
 "Nessuna.",
 "Verifica rapida: il momento massimo dove il taglio si annulla. Se il software dice altro, il software ha un errore di carico o di vincolo."),
s("Logaritmi e esponenziali","Logaritmi, esponenziali e decadimenti: la matematica del tempo",
 "Crescita e decadimento: carbonatazione del cls, consolidamento dei terreni, ammortamenti.",
 "Logaritmo (l'inverso dell'esponenziale); decadimento esponenziale N(t) = N₀·e^(−kt); tempo caratteristico τ = 1/k; raddoppio (ln2/k) e dimezzamento.",
 "Vita utile delle strutture, consolidamento, fatica, ammortamento economico, crescita demografica.",
 "La carbonatazione del cls (penetrazione ~ √t) e il consolidamento (~ log t) si leggono con questi strumenti.",
 "I modelli reali hanno dispersione: la matematica descrive la tendenza, non predice il singolo caso.",
 "Foglio di calcolo gratuito (regressione esponenziale).",
 "La profondità di carbonatazione cresce con la radice quadrata del tempo: dopo 25 anni non il doppio di 12,5 ma √2 volte (~1,4).",
 "Modelli fib e Eurocodice 2 (durabilità).",
 "Il tempo in edilizia non è lineare: quasi tutti i decadimenti (carbonatazione, consolidamento, usura) seguono radici e logaritmi. Chi pensa lineare sottostima i danni."),
s("Statistica","Statistica per il cantiere: medie, dispersione, affidabilità",
 "La matematica dell'incertezza: cosa dicono davvero 5 prove su 5 campioni.",
 "Media aritmetica; scarto quadratico medio (deviazione standard); caratteristica = media − 1,64σ (5% frattile); distribuzione normale (gaussiana); numero minimo di prove per stima affidabile.",
 "Prove su cls, acciaio, terreni; controllo qualità; collaudi.",
 "La media da sola mente: 5 prove con media 25 MPa e dispersione 2 vs 8 MPa raccontano storie opposte.",
 "La statistica richiede campioni rappresentativi: il campione sbagliato falsifica tutto.",
 "Le tavole statistice (frattili) sono pubbliche nei testi di tecnologia.",
 "Il cls in opera: resistenza caratteristica C25/30 significa media ~33 MPa con 5% di probabilità di trovarne <25.",
 "EN 206 (specificazione cls); UNI EN 12390 (prove).",
 "Regola di controllo: se la deviazione standard delle prove supera il 15% della media, il processo NON è sotto controllo: fermarsi e capire prima di continuare."),
s("Scala e proporzione","Scale di disegno e conversioni: il disegno che parla in metri",
 "Da 1:50 a 1:200: come si converte il disegno in dimensioni reali e viceversa.",
 "Scala = disegno/realtà (1:100 = 1 cm di disegno = 100 cm reali); conversione lineare (×100), di superficie (×100²), di volume (×100³); scale tipiche (1:20 dettaglio, 1:50 appartamento, 1:200 edificio, 1:2000 territorio).",
 "Lettura di progetti, verifica dimensioni, disegno CAD.",
 "La verifica della scala corretta è la prima difesa contro gli errori di lettura del disegno.",
 "Le scale 'non standard' (1:75) confondono: si convertono con la formula, non con la supposizione.",
 "Il righello su carta: lo strumento più usato e più pericoloso (fotocopie ridotte!).",
 "Su una planimetria 1:100 una stanza di 4,2 cm × 5,6 cm = 4,2 m × 5,6 m = 23,5 m².",
 "Norme di rappresentazione UNI (scale consigliate).",
 "Attenzione alla fotocopia: una stampa al 94% su scala 1:100 diventa 1:106. Il righello sul disegno fotocopiato mente: fidarsi solo delle quote scritte."),
s("Calcolo mentale","Il calcolo mentale e le stime rapide: l'arma segreta del professionista",
 "Ordini di grandezza, arrotondamenti intelligenti, verifiche immediate senza calcolatrice.",
 "Stima prima del calcolo (ispezione); tecniche di arrotondamento (29,7 → 30); regole mnemoniche (π≈3, √2≈1,4, g≈10); il 'sanity check' finale.",
 "Ogni interazione tecnica: preventivi, riunioni, verifiche in cantiere.",
 "Chi stima prima non si fa ingannare: riconosce subito il risultato sbagliato di 10 volte.",
 "La stima non sostituisce il calcolo: lo precede e lo controlla.",
 "Nessun costo: è allenamento quotidiano.",
 "Solaio di 5 m × 4 m = 20 m² × 5 kN/m² (carico tipico) = 100 kN ≈ 10 tonnellate: una casa ne regge tante, ma un cassone da 10 t non si appoggia 'alla leggera'.",
 "Nessuna.",
 "Il 'sanity check' professionale: ogni risultato deve passare la prova della verosimiglianza. Se il pilastro da 3 tonnellate regge un grattacielo, qualcosa non torna."),
]

# ===========================================================================
# L2 — FORMULARIO DELLE STRUTTURE
# ===========================================================================
STRUTTURE = [
s("Statica","L'equilibrio: ΣF=0, ΣM=0 e le reazioni vincolari",
 "La legge madre della statica: ogni corpo fermo ha somma di forze e momenti nulla.",
 "ΣFx = 0; ΣFy = 0; ΣM = 0. Reazioni: appoggio semplice (1 reazione verticale); cerniera (2 reazioni); incastro (3 reazioni: V, H, M); per travi appoggiate R_A = R_B = qL/2 (carico uniforme).",
 "Primo passo di OGNI calcolo strutturale, a mano o al computer.",
 "Tre equazioni risolvono tutti i problemi isostatici: il 70% delle strutture reali è verificabile a mano.",
 "Le strutture iperstatiche (incastri multipli) richiedono metodi aggiuntivi (deformazioni).",
 "Il calcolo a mano delle reazioni: 5 minuti e zero software.",
 "Trave 6 m con q = 10 kN/m: reazioni 30 kN ciascuna; chiunque lo verifichi in un minuto.",
 "Statica dei corpi rigidi (testi classici).",
 "La prima verifica di ogni modello FEM: le reazioni devono eguagliare i carichi totali. Se ΣR ≠ Σcarichi, il modello ha un vincolo assente o un carico perso."),
s("Travi","Le travi fondamentali: momenti e tagli delle 4 travi base",
 "Le 4 travi che ogni tecnico deve conoscere a memoria: i numeri della professione.",
 "Mensola con q uniforme: M_max = qL²/2 all'incastro, V_max = qL. Appoggiata: M_max = qL²/8 al centro, V_max = qL/2. Biapoggiata con carico centrale P: M_max = PL/4. Incastro-rottura? no: incastro-appoggio (trave con un incastro e un appoggio): M_inc = qL²/8, M_campo ≈ qL²/14.",
 "Verifiche rapide, predisposizione armature, controlli in cantiere.",
 "Le 4 formule coprono il 80% delle travi reali: la stima a mano è immediata.",
 "Le condizioni reali (vincoli intermedi, carichi variabili) richiedono il calcolo completo.",
 "Tabelle da manuale (gratis nei PDF dei manuali strutturali).",
 "Trave appoggiata 5 m, q = 8 kN/m: M = 8·25/8 = 25 kN·m; V = 20 kN.",
 "EC2 e manuali di tecnica delle costruzioni.",
 "Il momento al centro della trave appoggiata (qL²/8) è il numero più usato del calcolo strutturale: impararlo a memoria come le tabelline."),
s("Sezioni","Le proprietà delle sezioni: area, inerzia, modulo resistente",
 "I tre numeri che descrivono una sezione: quanto regge e quanto si flette.",
 "Area A = ∫dA (resistenza a sforzo normale); momento d'inerzia I = ∫y²dA (resistenza alla flessione); modulo resistente W = I/y_max (tensione massima σ = M/W). Formule: rettangolo I = bh³/12, W = bh²/6; cerchio I = πd⁴/64, W = πd³/32; profili metallici da tabelle (IPE, HE).",
 "Verifica di travi, pilastri, solai in qualsiasi materiale.",
 "I = bh³/12 spiega perché l'altezza della trave vale più del suo spessore: l'inerzia cresce col cubo.",
 "Le sezioni complesse si scompongono (somma/sottrazione di rettangoli).",
 "Le tabelle dei profili acciaio sono pubbliche (free).",
 "Trave rettangolare 30×50: W = 30·50²/6 = 12.500 cm³ = 0,0125 m³.",
 "EC2/EC3; manuali di scienza delle costruzioni.",
 "Regola empirica: raddoppiare l'altezza di una trave ne quadruplica la resistenza a flessione (I cresce col cubo). Per questo i solai sono 'alti' e non 'spessi'."),
s("Sforzi","Sforzo normale, taglio, momento flettente: la trinità del calcolo",
 "Le tre sollecitazioni di base e le loro formule di verifica.",
 "Sforzo normale N (trazione/compressione): σ = N/A. Taglio V: τ = VS/(Ib) ≈ 1,5V/A per sezione rettangolare. Momento M: σ = M/W. Tensioni: acciaio ~235 MPa (S235), cls ~14,2 MPa (C25/30) lato cls armato? no: 'calcolo tensioni'.",
 "Verifica di ogni elemento portante.",
 "Tre formule coprono il primo livello di ogni verifica: la diagnosi immediata.",
 "Le sollecitazioni combinate (N+M, M+V) richiedono interazioni specifiche.",
 "I valori di resistenza sono nelle norme (gratuiti).",
 "Pilastro 30×30 in cls C25/30 (14,2 MPa = 14,2 N/mm²): area 90.000 mm² -> N_max ≈ 1.278 kN ≈ 128 t.",
 "EC2 (cls), EC3 (acciaio).",
 "La 'trinità' N-V-M è il primo filtro: se un elemento passa queste tre verifiche semplici, si passa al calcolo fine; se le fallisce, si cambia subito."),
s("Verifiche SLU","Il metodo degli stati limite: la verifica SLU di base",
 "Come si confronta l'azione con la resistenza: la regola del gioco del progetto moderno.",
 "Stato limite ultimo: E_d ≤ R_d (azione di progetto ≤ resistenza di progetto); valori di progetto = caratteristici / coefficienti parziali (γM: acciaio 1,05-1,25, cls 1,5); combinazioni 1,3G+1,5Q.",
 "Ogni verifica strutturale firmata.",
 "Un metodo unico e trasparente: la sicurezza è nei coefficienti, non nei 'fattori di esperienza'.",
 "I coefficienti cambiano per materiale e per stato limite: le tabelle vanno consultate sempre.",
 "Le NTC2018 riportano tutti i coefficienti (pubbliche).",
 "Verifica pilastro: N_Ed = 900 kN ≤ N_Rd = 1.200 kN -> verificato (margine 25%).",
 "NTC2018; EC0 (EN 1990).",
 "La verifica SLU non è 'passa/non passa': è un rapporto E_d/R_d. Un rapporto 0,98 e 0,50 sono tecnicamente diversi (margine) anche se entrambi 'verificati'."),
s("Instabilita","L'instabilità di Eulero: il pilastro che si piega prima di rompersi",
 "Lo snellezza uccide: la formula che spiega perché i pilatori lunghi falliscono prima del previsto.",
 "Carico critico di Eulero P_cr = π²EI/L₀²; snellezza λ = L₀/i (raggio girazione i = √(I/A)); λ < 50 robusto, λ > 100 critico; acciaio: σ_cr = π²E/λ².",
 "Pilastri, colonne, puntoni, puntoni di ponteggi, strutture snelle.",
 "L'unica verifica che spiega i crolli 'imprevisti' degli elementi snelli.",
 "L'Eulero vale per il carico perfettamente centrato: l'eccentricità reale riduce il carico critico.",
 "La formula si applica con la calcolatrice scientifica.",
 "Pilastro in acciaio S235, λ = 100: σ_cr = π²·210000/10000 ≈ 207 MPa: resiste meno del limite elastico (235)!",
 "EC3 (acciaio); teoria dell'instabilità.",
 "Il messaggio vitale: un pilastro snello in acciaio S355 si piega a una tensione MINORE di uno tozzo in S235. La resistenza del materiale non aiuta gli snelli."),
s("Calcestruzzo armato","Il cls armato in formule: trave e pilastro semplificati",
 "Le formule pratiche del dimensionamento rapido in c.a.",
 "Trave (campo): A_s ≈ M/(0,9·d·f_yd) con f_yd = 391 MPa (B450C); altezza utile d ≈ L/12 (semplicemente appoggiata) a L/15 (continua); armatura minima 0,26·f_ctm/f_yk·b·d; pilastro: N_Rd ≈ 0,9·A_c·f_cd (snellozza bassa); copriferro minimo 2,5-4 cm (ambiente aggressivo).",
 "Predimensionamento immediato in studio e in cantiere.",
 "Il predimensionamento corretto in 2 minuti: il colloquio tecnico si vince qui.",
 "Le formule sono per predimensionare: il progetto esecutivo richiede il calcolo completo.",
 "Le formule del predimensionamento nei manuali (gratuiti).",
 "Trave L=5 m appoggiata: h ≈ 5000/12 ≈ 42 cm (si prende 45); M=25 kN·m -> A_s ≈ 25e6/(0,9·400·391) ≈ 178 mm² (2Ø12 = 226 mm²).",
 "EC2; NTC2018.",
 "Il rapporto L/h (luce/altezza) è la prima verifica di un solaio: sotto 1/12 per appoggiato è sospetto, sopra 1/20 è impossibile."),
s("Acciaio","L'acciaio strutturale in formule: travi e colonne",
 "Le formule rapide per le verifiche in acciaio.",
 "Trazione: N_Ed ≤ A·f_yd (f_yd = 235/1,05 = 224 MPa per S235); flessione: M_Ed ≤ W_pl·f_yd; colonna: verifica di stabilità (curve di instabilità, imprefezioni); collegamenti: bulloni M16-M24 (resistenza a taglio per bullone 8.8: ~90-160 kN).",
 "Capannoni, carpenterie, ponti, prefabbricati metallici.",
 "L'acciaio si calcola velocemente: il predimensionamento è immediato perché le tabelle dei profili danno W e A.",
 "Le verifiche di instabilità (svergolamento laterale delle travi) richiedono attenzione specifica.",
 "Le tabelle dei profili IPE/HE sono gratis (siti dei produttori).",
 "Trave IPE 200: W = 194 cm³; M_Rd = 194e3 mm³ · 224 MPa ≈ 43 kN·m.",
 "EC3.",
 "L'acciaio paga il suo peso: la trave in acciaio pesa 1/3 di quella in cls ma costa 3 volte di più al kg. La scelta nasce dal cantiere (montaggio veloce) più che dal calcolo."),
s("Legno","Il legno strutturale in formule: flessione e taglio",
 "Le formule del legno lamellare: leggero ma esigente.",
 "Flessione: σ_m = M/W ≤ f_m,d (GL24h: f_m,k = 24 MPa, di progetto ~16 MPa); taglio: τ = 1,5V/A ≤ f_v,d; rigidezza: EI con E = 11.600 MPa (GL24h); frecce: w ≤ L/300 (tetti) a L/500 (soffitti).",
 "Tetti, travi di copertura, capannati in legno, X-LAM.",
 "Il legno si calcola come l'acciaio ma con E molto più basso: spesso la freca (deformazione) e non la resistenza comanda la sezione.",
 "L'umidità e il ritiro vanno considerati nella freccia a lungo termine (fattore k_def).",
 "Le formule nell'EC5 (pubblico).",
 "Trave in legno 20×20, L=4 m, q=2 kN/m: M=4 kN·m; W=1333 cm³; σ=3 MPa << 16 MPa: la resistenza avanza; la freccia è il vero dimensionamento.",
 "EC5.",
 "La regola del pollice del legno: 'dimensiona la freccia, non la rottura'. Il 90% delle travi in legno è sovradimensionato a rottura e sottodimensionato a deformazione."),
s("Muratura","La muratura strutturale in formule: verifica semplificata dei setti",
 "La verifica rapida dei muri portanti esistenti.",
 "Resistenza a compressione: N ≤ A·f_d (f_d = f_k/γM, muratura pietra/bricchese f_k = 1-8 MPa); verifica a taglio: τ = V/(L·t) ≤ f_vd; snellezza h/t < 15 (sicura), 15-20 (attenzione), >20 (critica); rinforzo FRP aumenta flessione e taglio del 30-80%.",
 "Diagnosi di edifici esistenti, verifiche pre-intervento, perizie.",
 "La verifica a mano del muro in 10 minuti: chi sa farla riconosce subito il muro pericoloso.",
 "Le murature reali hanno variabilità enorme: serve il livello di conoscenza (LC).",
 "Le formule nelle NTC2018 cap. 7 (pubbliche).",
 "Muro pieno 50 cm, h=3 m, N=100 kN/m: σ = 100e3/(1000·500) = 0,2 MPa << 1-2 MPa tipici: il muro regge la compressione, il problema è il sisma (taglio).",
 "NTC2018 cap. 7.",
 "La verifica del muro portante ha un ordine: 1) snellezza, 2) compressione, 3) taglio (sisma). Il sisma è quasi sempre il vincolo vero in Italia."),
s("Geotecnica","La geotecnica in formule: portanza, spinta, cedimenti",
 "Le formule del terreno: capire cosa regge e cosa spinge.",
 "Tensione verticale efficace σ' = γ·z (sotto falda: γ' = γ_sat − γ_w ≈ 10 kN/m³); capacità portante di Meyerhof/Vesic: q_lim ≈ cN_c + γDN_q + 0,5γBN_γ; spinta attiva di Rankine σ_a = γz·K_a − 2c√K_a con K_a = tan²(45°−φ/2); cedimento con Winkler? no: 'cedimento consolidazione': s = H·C_c/(1+e₀)·log(σ'₁/σ'₀).",
 "Fondazioni, muri di sostegno, verifiche di scavo, consolidamenti.",
 "Le formule della geotecnica sono poche e potenti: la diagnosi del terreno inizia qui.",
 "I parametri (c, φ) vengono dalle indagini: la formula è giusta, i dati possono non esserlo.",
 "Le formule in EC7 e nei manuali di geotecnica.",
 "Sabbia (φ=30°): K_a = tan²(45−15) = 1/3: la spinta è un terzo di quella a riposo: il muro regge.",
 "EC7; NTC2018 cap. 6.",
 "La geotecnica è la scienza dei 'dipende': ogni formula vale per il terreno descritto. Prima delle formule, l'indagine: 5-10k€ di sondaggi valgono più di qualsiasi calcolo."),
s("Sismica formule","Il calcolo sismico in formule: forza, periodo, spettro",
 "Le formule di base dell'ingegneria sismica: quanto trema l'edificio.",
 "Forza sismica F = m·S_a(T); periodo approssimato T = 0,075·H^(3/4) (edifici in cls); spettro elastico S_e(T) = a_g·S·(T_B/T)^0,9 tra T_B e T_C; taglio alla base V = W·S_d(T₁)/g; riduzione q (struttura 3-6).",
 "Verifica sismica preliminare, valutazione esistente, spiegazione ai clienti.",
 "Il periodo è il 'battito cardiaco' dell'edificio: basso e tozzo vs alto e snello rispondono in modo opposto.",
 "Le formule sono semplificate: l'analisi completa è dinamica (spettri di risposta).",
 "Le formule in NTC2018 cap. 7.3 (pubbliche).",
 "Edificio H=12 m in cls: T ≈ 0,075·12^0,75 ≈ 0,47 s (periodo breve: forza alta ma duttilità richiesta moderata).",
 "NTC2018; EC8.",
 "Regola sismica fondamentale: la forza sismica non è una forza esterna, è l'inerzia dell'edificio che accelera. L'edificio si scuote da sé: il progetto governa la risposta, non il terremoto."),
s("Fondazioni formule","Le fondazioni in formule: platea, pali, micropali",
 "Le formule del dimensionamento rapido delle fondazioni.",
 "Platea: portanza q_lim vs tensione di esercizio σ = N/A ≤ q_am (q_am ≈ q_lim/3); palo singolo: Q_lim = Q_p (punta) + Q_s (laterale); palo in sabbia Q_s ≈ 0,5·K_s·γ·D·tanδ·A_lat; gruppo di pali: efficienza η < 1 (interazione); micropali: portanza 200-600 kN caduno.",
 "Predimensionamento fondazioni, verifiche rapide, perizie.",
 "Il predimensionamento corretto della platea è un calcolo di 3 righe: la trattativa con il geotecnico parte da qui.",
 "Le formule cambiano con il tipo di terreno: sabbia, argilla, roccia parlano lingue diverse.",
 "Le formule in EC7 e nei manuali.",
 "Edificio N=2000 kN su platea: A ≥ 2000/150 ≈ 13,3 m² (platea 4×3,5 m a 150 kPa ammissibili).",
 "EC7.",
 "La platea è economica fino a ~150-200 kPa di terreno: oltre, i pali convengono. La soglia di scelta è una formula, non un'opinione."),
s("Fatica","La fatica strutturale: quando le ripetizioni rompono",
 "La matematica del 'mille volte leggero vale una volta forte': ponti, gru, macchine.",
 "Curve S-N (Wöhler): numero di cicli N al livello di tensione Δσ; la legge di Miner per la somma dei danni Σ(n_i/N_i) ≤ 1; dettaglio strutturale e categoria di dettaglio ( FAT 71-160 MPa).",
 "Ponti (traffico), impianti industriali, gru, strutture metalliche cicliche.",
 "La fatica spiega i crolli 'senza sovraccarico': il ponte che regge i camion per 40 anni e poi cede.",
 "Le curve S-N valgono per dettagli standardizzati: la qualità esecutiva (saldature!) decide la vita.",
 "Le curve S-N sono nelle norme (pubbliche).",
 "Dettaglio FAT 90: a Δσ=90 MPa resiste ~2 milioni di cicli; a Δσ=45 MPa (metà) resiste ~16 volte di più (la vita cresce come la potenza -3).",
 "EC3 parte 1-9 (fatica).",
 "La fatica è il massacro delle opere mal saldate: una saldatura discontinua riduce la vita di 10 volte. Il controllo saldature è assicurazione sulla vita dell'opera."),
s("Verifica esistenti","Le verifiche sulle strutture esistenti in formule",
 "Le formule della valutazione: come si 'legge' la capacità di una struttura che esiste.",
 "Resistenza caratteristica da prove: f_k = f_m − 1,64·s (cls e acciaio); resistenza di calcolo esistente: f_d = f_k·(0,85-1,0)/γM; capacità residua dopo degrado: perdita di sezione per corrosione/carbonatazione; valutazione con livelli di conoscenza LC1 (valori da tabelle) a LC3 (prove complete).",
 "Diagnosi, perizie, adeguamenti, compravendite.",
 "Le formule del 'quanto regge ancora' sono le più richieste della professione italiana.",
 "Il valore da tabelle è prudente: può sottostimare il reale del 30-50% (da provare se l'intervento lo merita).",
 "Le formule in NTC2018 cap. 8 e CNR-DT 200/2013 (pubbliche).",
 "Cls con 3 carotaggi: f_m = 28 MPa, s = 3 MPa -> f_k = 28 − 1,64·3 = 23 MPa.",
 "NTC2018 cap. 8.",
 "La regola etica della valutazione: il livello di conoscenza va detto SEMPRE in relazione. Una valutazione LC1 con numeri certi è disonestà tecnica: 'valori assunti da tabelle, conoscenza parziale' va scritto."),
]

# ===========================================================================
# L1-L2 — FORMULARIO FISICA DELL'EDILIZIA E DEGLI IMPIANTI
# ===========================================================================
FISICA = [
s("Termofisica base","La termofisica dell'involucro: conduzione e trasmittanza",
 "Come passa il calore attraverso la parete: la formula che decide l'efficienza energetica.",
 "Flusso termico Φ = λ·S·ΔT/s; resistenza termica R = s/λ; trasmittanza U = 1/(ΣR + R_si + R_se); valori guida: cappotto 10 cm (λ=0,035) → R=2,9 m²K/W; parete attuale U≤0,26 W/m²K (clima E).",
 "Cappotti, verifiche energetiche, leggi 10, certificazione energetica.",
 "Uguale a: il valore U è il 'voto' della parete: chi lo calcola controlla la qualità dell'edilizia.",
 "Le prestazioni reali degradano (umidità, ponti termici): il valore di targa non è eterno.",
 "I valori λ dei materiali nelle tabelle UNI (pubbliche).",
 "Parete: intonaco 0,02/0,7 + cls 0,20/2,3 + cappotto 0,10/0,035 + intonaco 0,02/0,7 → R=3,24 → U=0,30 W/m²K.",
 "UNI EN ISO 6946; UNI/TS 11300.",
 "Il ponte termico tipico del 15-20% di perdita: verificare correnti d'aria e cerniere? no: 'sommando U·A si deve aggiungere il 15% per ponti termici': regola rapida del Legge 10."),
s("Condensazione","La condensazione e il vapore: quando l'acqua si nasconde nella parete",
 "Il vapore acqueo che attraversa la parete e diventa acqua: la fisica della muffa.",
 "Pressione di vapore saturo (tabella); flusso di vapore g = δ·Δp/s; metodo di Glaser (analisi grafica degli strati); regola dello strato di tenuta (lato caldo) lasciando traspirare lato freddo; punto di rugiada.",
 "Diagnosi muffa, progettazione stratigrafie, involucri in legno.",
 "La muffa è quasi sempre condensazione interstiziale o superficiale: la fisica la spiega e la cura.",
 "La realtà è 2D e 3D (ponti termici): il metodo di Glaser è 1D.",
 "Le tabelle del vapore saturo sono pubbliche.",
 "Interno 20°C/55% UR → p=1280 Pa; parete con barriera insufficiente: condensa nel lana? no: 'nella lana' in inverno.",
 "UNI EN ISO 13788 (metodo Glaser).",
 "La muffa in basso a destra della camera nord: non è sfortuna, è fisica. Il progettista che non fa il Glaser scarica la muffa sul cliente."),
s("Massa termica","La massa termica e l'inerzia: la fisica del comfort estivo",
 "Il peso che frena il caldo: capacità termica e fase di sfasamento.",
 "Capacità termica volumica = ρ·c; sfasamento delle onde di calore (parete pesante 10-14 h, leggera 3-6 h); il decremento (riduzione ampiezza); notte ventilata su parete pesante = raffrescamento gratuito.",
 "Case passive, climi mediterranei, edilizia in terra e cls.",
 "L'inerzia è il condizionamento gratuito: la parete pesante carica di fresco la notte e lo restituisce il giorno.",
 "L'inerzia è utile solo con escursione giorno-notte: nei climi umidi e costanti vale meno.",
 "I valori ρ·c nelle tabelle (cls 2400 kg/m³ · 1000 = 2,4 MJ/m³K).",
 "Le case in tufo dell'Etna: interni freschi senza condizionatore; i palazzi storici di pietra.",
 "UNI EN ISO 13786 (inerzia).",
 "La regola mediterranea: 'parete pesante verso sud, isolata all'esterno, ventilata la notte': tre mosse fisiche che sostituiscono metà del condizionatore."),
s("Fabbisogno energetico","Il fabbisogno energetico rapido: kWh/m²·anno in formule",
 "Stimare la bolletta prima di progettare: le formule del conto termico quotidiano.",
 "Dispersione trasmissione Q = U·A·ΔT·t; ventilazione Q_v = 0,34·V·n·ΔT·t (n = ricambi/h); apporti solari = g·A·E; bilancio annuo = dispersioni − apporti; classe energetica da E_ph (kWh/m²·anno).",
 "Legge 10, bollette, scelta impianti, confronto soluzioni.",
 "Il calcolo rapido del bilancio decide l'investimento energetico in 30 minuti.",
 "Il calcolo semplificato non sostituisce la certificazione energetica ufficiale.",
 "I valori U e i gradi-giorno sono pubblici (Enea).",
 "Appartamento 100 m², U medio 0,9, ΔT=20°C, 180 gg riscaldamento: Q_trasm ≈ 0,9·220·20·4320/1000 ≈ 17.100 kWh/anno.",
 "UNI/TS 11300; gradi-giorno ENEA.",
 "La formula più utile del settore: Q = 0,024·GG·(UA + 0,34·V·n) con GG = gradi-giorno. Chi la usa stima la bolletta di qualsiasi edificio in 10 minuti."),
s("VMC calcoli","La ventilazione in formule: portate, ricambi e CO2",
 "Quanta aria serve davvero: il calcolo della VMC e del comfort degli interni.",
 "Portata per persona: 25-30 m³/h (residenze), 36 m³/h (uffici); ricambi minimi (cucina 20-40, bagno 15-25 ricambi/h); portata di progetto Q = n·V; bilancio CO2: produzione 20 l/h persona → concentrazione = produzione/portata; rendimento scambiatore 80-92%.",
 "Progetto VMC, verifica qualità aria, scelta centraline.",
 "Il calcolo della portata decide il dimensionamento della VMC: la salute si calcola, non si promette.",
 "I ricambi minimi di legge sono il minimo legale, non il comfort ottimale.",
 "Le tabelle UNI 10339 (pubbliche).",
 "Camera da letto 2 persone, 30 m³/h ciascuno = 60 m³/h: una centralina da 100 m³/h copre la zona notte.",
 "UNI 10339; UNI EN 13779.",
 "La regola del CO2: sotto i 800 ppm la testa funziona, sopra i 1200 ppm il sonno e la concentrazione calano. Il sensore CO2 (60 €) è il termometro del comfort moderno."),
s("Acustica formule","L'acustica in formule: riverbero, isolamento, assorbimento",
 "Le formule del suono negli edifici: il comfort che si misura.",
 "Tempo di riverbero di Sabine: T = 0,161·V/A (A = ΣS·α); il criterio di Ottavo? no: 'valutazione': T ottimale uffici 0,6-0,8 s, ristoranti 0,8-1,2 s, chiese 2-3 s; isolamento: R = L1 − L2 + 10·log(S/A); rumore = 10·log(Σ10^(Li/10)).",
 "Progetto acustico, risarcimenti da rumore, ristrutturazioni.",
 "La formula di Sabine (1898!) è ancora lo strumento n.1: una stanza si descrive con un numero.",
 "Le formule valgono per campi diffusi: le prime riflessioni e il parlato ravvicinato richiedono modelli più fini.",
 "Le tabelle di assorbimento α dei materiali sono pubbliche.",
 "Studio 60 m³, A=12 m² sa → T=0,161·60/12 = 0,8 s (perfetto per riunioni).",
 "UNI EN ISO 3382; UNI 11367.",
 "Il trucco rapido: contare i 'metri quadri equivalenti di assorbimento' di una stanza (tappeto, tende, persone) dà la stima di T in 2 minuti."),
s("Illuminotecnica","L'illuminotecnica in formule: lux, lumen, resa",
 "La luce misurata: come si progetta l'illuminazione senza tentativi.",
 "Flusso luminoso Φ (lumen); illuminamento E = Φ/S (lux); i livelli guida (ufficio 500 lux scrivania, corridoio 100, officina 300); il metodo del flusso: Φ_tot = E·S/(η·fu); resa cromatica IRC>80 (90 per musei/retail moda); abbagliamento UGR<19 uffici.",
 "Progetto luci, verifiche lux in cantiere, scelta apparecchi.",
 "E = Φ/S: con una calcolatrice si verifica se una stanza è ben illuminata PRIMA di montare.",
 "Il metodo del flusso ignora le riflessioni complesse: la simulazione (Dialux, gratis) affina.",
 "Il software Dialux evo è gratuito.",
 "Ufficio 20 m² a 500 lux: Φ = 500·20/(0,6·0,8) ≈ 20.800 lm (8-10 apparecchi da 2000 lm).",
 "UNI EN 12464-1; UNI EN 15193.",
 "La verifica di cantiere: il luxmetro (30 €) misura la realtà. La norma dice 500 lux sulla scrivania: misurare dopo la posa, non fidarsi del catalogo."),
s("Idraulica formule","L'idraulica degli impianti in formule: portata, perdite, pressione",
 "Le formule del fluire dell'acqua negli edifici: pressione, portata, perdite di carico.",
 "Portata Q = v·A (l/s); perdite distribuite J = λ·(v²/2g)·(1/D); perdite localizzate ζ·v²/2g; pressione residua al punto: p = p₀ − ΣJ (minimo 0,5 bar agli apparecchi); velocità guida: 1-2 m/s (adduzione), 0,6-1,5 m/s (interne).",
 "Dimensionamento tubazioni, verifica pressioni, diagnosi di impianti deboli.",
 "Le perdite di carico spiegano il 90% dei problemi: 'l'acqua non arriva' = le perdite superano la pressione.",
 "I calcoli sono per regime permanente: i transitori richiedono studi dedicati.",
 "Le formule in UNI EN 806 e nei manuali.",
 "Doccia al 3° piano con p=0,8 bar: ok (min 0,5); con p=0,3 bar: insufficiente → servono perdite ridotte o pressurizzazione.",
 "UNI EN 806; UNI EN 1717.",
 "La regola del pollice: a parità di portata, raddoppiare il diametro riduce le perdite di 30 volte (J ∝ 1/D⁵ approssimato). Il diametro corretto è il miglior investimento invisibile dell'impianto."),
s("Elettrica formule","L'impianto elettrico in formule: potenza, corrente, caduta di tensione",
 "Le formule elettriche del cantiere e dello studio.",
 "Potenza monofase P = V·I·cosφ (230 V); trifase P = √3·V·I·cosφ (400 V); corrente I = P/(V·cosφ); caduta di tensione ΔV% = (√3·I·L·(R cosφ + X sinφ))/V ·100 (max 4%); la protezione: I_n ≥ I_b e I_2 ≤ 1,45·I_z; messa a terra: U_L ≤ 50 V.",
 "Dimensionamento linee, verifica quadri, scelta protezioni, diagnostica guasti.",
 "P=V·I basta per non bruciare un impianto: chi la ignora sottodimensiona i cavi.",
 "Le formule sono a regime: i picchi di avviamento (motori) richiedono sovradimensionamento coordinato.",
 "Le tabelle sezione-corrente sono nella CEI 64-8 (pubblica).",
 "Forno 3 kW a 230 V: I = 3000/230 = 13 A → linea 2,5 mm² con magnetotermico 16 A.",
 "CEI 64-8; IEC 60364.",
 "Il test del professionista: chiedere sempre la corrente di impiego prima di parlare di sezioni. Il cavo si sceglie dalla corrente, non dal colore o dall'abitudine."),
s("Prevalenza pompe","Le pompe in formule: prevalenza, portata, potenza",
 "Come si sceglie una pompa: la fisica del sollevamento dell'acqua.",
 "Prevalenza H = H_geo + H_perdite + H_residua; potenza assorbita P = ρ·g·Q·H/η (η = 0,4-0,8); punto di lavoro = intersezione curva pompa/rete; NPSH disponibile vs richiesto (cavitazione).",
 "Circolatori di riscaldamento, pompe di sollevamento, idranti, irrigazione.",
 "La prevalenza corretta evita pompe sottodimensionate (che non arrivano) o sovradimensionate (che consumano e roncano).",
 "Le curve pompa/rete si intersecano: il punto reale di lavoro va verificato, non assunto.",
 "Le formule nei manuali di macchine idrauliche.",
 "Sollevamento 10 m, portata 2 l/s, η=0,6: P = 1000·9,81·0,002·10/0,6 ≈ 327 W (un circolatore da 370 W basta).",
 "Nessuna norma: teoria delle macchine.",
 "La regola della pompa: la curva della rete (perdite) sale con il quadrato della portata: chiudere una valvola aumenta la prevalenza a disposizione. L'equilibrio tra pompa e rete è la fisica quotidiana del circolatore."),
s("Fotovoltaico formule","Il fotovoltaico in formule: produzione, inclinazione, ombreggiamento",
 "Quanta energia produce un pannello: le formule della resa solare.",
 "Produzione E = P_inst × HSP × PR (HSP = ore di sole di picco, 3-5 in Italia; PR = performance ratio 0,75-0,85); perdita da orientamento: sud 100%, est/ovest 85-90%, nord 60-70%; perdita da inclinazione: ottimale = latitudine (45° in Italia); perdita da ombra: un 10% di ombra = −30% di resa (stringhe in serie).",
 "Preventivi FV, verifica installatori, scelta della potenza.",
 "E = P×HSP×PR stima la produzione annua di qualsiasi tetto in 2 minuti.",
 "I valori locali (HSP) variano: servono le mappe ENEA/PVGIS.",
 "Il simulatore PVGIS (gratuito, Enea) dà i dati locali precisi.",
 "6 kWp a Roma (HSP 3,6, PR 0,8): E ≈ 6·3,6·0,8·365 ≈ 6.300 kWh/anno.",
 "Nessuna norma: fisica solare.",
 "La verità del FV: il peggior nemico è l'ombra parziale, non il cattivo orientamento. Un camino che ombreggia mezzo pannello può distruggere il 25% della produzione: l'ispezione prima della firma del contratto è obbligatoria."),
s("Pompe di calore formule","La pompa di calore in formule: COP, energia, risparmio",
 "La macchina che moltiplica l'energia: come si calcola il vantaggio reale.",
 "COP = energia termica prodotta / energia elettrica assorbita (3-5 aria-acqua a 35°C mandata); energia annua = fabbisogno termico / COP; il SCOP stagionale tiene conto del clima; risparmio vs caldaia gas = 1 − (costo elettrico/COP)/(costo gas/0,9); integrazione a −10°C: resistenza o ibrido.",
 "Scelta PDC, verifica preventivi, confronto con caldaia.",
 "Il COP trasforma il dibattito 'elettrico vs gas' in un calcolo di 3 righe.",
 "Il COP crolla con le temperature esterne basse e le mandate alte: il dato di targa è ottimistico.",
 "I dati climatici ENEA e i cataloghi (COP a condizioni note).",
 "Fabbisogno 12.000 kWh/anno, COP 3,5: energia elettrica = 3.430 kWh/anno ≈ 1.000 € a 0,30 €/kWh vs 1.350 € di gas: risparmio ~25-30%.",
 "UNI EN 14825; UNI/TS 11300.",
 "La regola della PDC: 'la PDC ama le mandate basse': chi ha radianti (35°C) ha COP 4; chi ha termosifoni vecchi (70°C) ha COP 2,5. Il risparmio si decide a monte, con l'impianto di emissione."),
s("Costruzione calcoli","Le formule economiche: interesse, ammortamento, valore attuale",
 "La matematica del denaro nell'edilizia: investimenti, mutui, valori.",
 "Interesse semplice I = C·r·t; interesse composto M = C·(1+r)^t; rata mutuo R = C·r/(1−(1+r)^−n); ammortamento annuo = costo/vita utile; valore attuale VA = F/(1+r)^t; TCO = costo iniziale + Σ costi esercizio (attualizzati).",
 "Mutui, valutazioni investimenti immobiliari, confronto tecnologie, leasing.",
 "Il TCO (costo totale di proprietà) svela la verità: la caldaia 'economica' costa più della PDC in 10 anni.",
 "I tassi reali includono inflazione e rischio: le formule semplici sono la base, il giudizio fa il resto.",
 "Le formule sono gratuite: foglio di calcolo basta.",
 "Mutuo 100k€, 3%, 20 anni: rata = 100.000·0,0025/(1−1,0025^−240) ≈ 555 €/mese.",
 "Nessuna norma: matematica finanziaria.",
 "L'edilizia moderna si giudica sul TCO a 20 anni, non sul prezzo iniziale. Chi vende solo il prezzo sta nascondendo qualcosa."),
]

# ===========================================================================
# GENERAZIONE
# ===========================================================================
NUOVI = {
 "MATEMATICA_PER_COSTRUIRE_PACK": ("Matematica per costruire", "FACOLTA_SCIENZE_DI_BASE", "L0",
   "La matematica applicata dell'ingegnere e del progettista: unità di misura, geometria, trigonometria, statistica, stime rapide.", MATEMATICA),
 "FORMULARIO_STRUTTURE_PACK": ("Formulario di calcolo strutturale", "FACOLTA_INGEGNERIA", "L2",
   "Le formule del calcolo strutturale con variabili, unità ed esempi numerici svolti: statica, sezioni, verifiche, sismica, geotecnica.", STRUTTURE),
 "FORMULARIO_FISICA_IMPIANTI_PACK": ("Formulario di fisica dell'edilizia e degli impianti", "FACOLTA_IMPIANTI_ENERGIA", "L1-L2",
   "Le formule della termofisica, acustica, illuminotecnica, idraulica, elettrica, solare e della matematica finanziaria edile.", FISICA),
}
for nome, (titolo, facolta, livello, desc, data) in NUOVI.items():
    pdir = os.path.join(UNI, nome)
    os.makedirs(os.path.join(pdir, "schede"), exist_ok=True)
    with open(os.path.join(pdir, "schede", "schede.jsonl"), "w", encoding="utf-8") as f:
        for it in data:
            f.write(json.dumps(it, ensure_ascii=False) + "\n")
    with open(os.path.join(pdir, "README.md"), "w", encoding="utf-8") as f:
        f.write(f"# {titolo}\n\n{desc}\n\nSchede: {len(data)}\n")
    with open(os.path.join(pdir, "COURSE.yaml"), "w", encoding="utf-8") as f:
        f.write(f"corso: \"{titolo}\"\nfacolta: \"{facolta}\"\nlivello: \"{livello}\"\n"
                f"schede: {len(data)}\nformato: \"JSONL\"\nlingua: \"it\"\n"
                f"schema_campi: [categoria, nome, descrizione, tecnologia, applicazioni, vantaggi, limiti, costi_e_economia, casi_real_world, normative, note_cantiere]\n")

# aggiorna manifest facolta e INDEX
for fac, nomi in {
 "FACOLTA_SCIENZE_DI_BASE": ["MATEMATICA_PER_COSTRUIRE_PACK"],
 "FACOLTA_INGEGNERIA": ["FORMULARIO_STRUTTURE_PACK"],
 "FACOLTA_IMPIANTI_ENERGIA": ["FORMULARIO_FISICA_IMPIANTI_PACK"],
}.items():
    mp = os.path.join(UNI, "CURRICULUM", f"{fac}.md")
    with open(mp, "a", encoding="utf-8") as f:
        for n in nomi:
            f.write(f"- {n}\n")

idx_p = os.path.join(UNI, "INDEX.md")
with open(idx_p, "a", encoding="utf-8") as f:
    f.write("\n## Corsi del giro 'formulario' (2026-10-01)\n\n")
    for n, (t, fa, li, d, da) in NUOVI.items():
        f.write(f"- {n} ({len(da)} schede)\n")

print("GIRO FORMULARIO:")
for n, (t, fa, li, d, da) in NUOVI.items():
    print(f"  {n}: {len(da)} schede [{fa} {li}]")
