# -*- coding: utf-8 -*-
"""Costruisce CAPPOTTO_ETICS_PACK: isolamento termico a cappotto (sistemi, materiali, posa, dettagli).

Norme citate solo se reali e identificabili: serie UNI EN 13162-13166 (prodotti
isolanti), UNI EN 13501-1 (reazione al fuoco), EAD 040083-00-0404 (sistemi ETICS,
ex ETAG 004), UNI EN 998-1/1015 (malte). Costi = ordini di grandezza indicativi.
"""
import json, os, io

ROOT = os.path.dirname(os.path.abspath(__file__))

def s(cat, nome, desc, tec, app, van, lim, cos, casi, norm, note):
    return dict(categoria=cat, nome=nome, descrizione=desc, tecnologia=tec,
                applicazioni=app, vantaggi=van, limiti=lim, costi_e_economia=cos,
                casi_real_world=casi, normative=norm, note_cantiere=note)

DATA = [
s("Materiali isolanti", "I materiali isolanti: EPS, lana di roccia, XPS, sughero, fibra di legno, aerogel",
 "L'isolante scelto decide prestazione, incendio, spessore e prezzo. Famiglie principali: EPS (polistirene espanso: economico, idrofobo trattato, Euroclasse E o migliore con fiamma ritardante), lana di roccia e lana di vetro (minerali: incombustibili Euroclasse A1/A2, traspiranti, piú costose), XPS (estruse: compressione elevata, idrofobo, per sottosuolo e sottopavimento), sughero espanso (naturale, traspirante, costoso), fibre di legno (traspiranti, buone inerzia), aerogel e pannelli sottili ad alta prestazione per spazi di pregio.",
 "Conduttività termica tipica λ (W/(mK), valori di catalogo indicativi): EPS 0,036-0,040; lana di roccia 0,034-0,042; XPS 0,030-0,036; sughero 0,037-0,050; fibre di legno 0,038-0,045; aerogel 0,014-0,018; pannelli isolanti sottili a vuoto (VIP) 0,004-0,008. Spessori abituali cappotto: 8-16 cm residenziale (fino a 20+ su edifici in muratura pesante antica). Densità e compressione: XPS 300-500 kPa per carichi.",
 "Scelta dell'isolante in progetto in funzione di λ (spessore), reazione al fuoco (classe edificio), traspirabilità (muro esistente), budget e disponibilità locale.",
 "Lana di roccia: sicurezza incendio e acustica al top; EPS: il miglior costo per prestazione; XPS: insensibile all'acqua per basi e fondazioni; sughero e fibre: muri storici traspiranti; aerogel: ristrutturazioni di pregio con spessori minimi.",
 "EPS: Euroclasse E (limiti in altezza e vicino fuochi), degrada con UV e solventi; XPS non traspira (attenzione all'interstiziale); lana minerale: richiede protezione dagli schizzi e compressione controllata; aerogel e VIP: costo altissimo e VIP sensibile a forature (perde prestazione se forato).",
 "Ordini di grandezza indicativi (solo isolante, 10 cm, 2024-2026): EPS 8-15 €/m², lana di roccia 14-24 €/m², XPS 16-28 €/m², sughero 30-55 €/m², fibra di legno 25-45 €/m², aerogel 80-150 €/m².",
 "Palazzina in centro storico con facciata cieca da 45 cm: il cappotto esterno in fibra di legno 10 cm scelse traspirabilità e finitura a calce (coerente con il borgo), rinunciando al risparmio dell'EPS: nessun problema di interstiziale nei successivi 5 inverni di monitoraggio.",
 "UNI EN 13162 (prodotti isolanti: lana minerale); UNI EN 13163 (EPS); UNI EN 13164 (XPS); UNI EN 13165 (PUR/PIR); UNI EN 13501-1 (classificazione reazione al fuoco); dichiarazioni di prestazione (DoP) dei prodotti isolanti.",
 "Verità da insegnare: il λ di catalogo vale in laboratorio: in opera contano anche posa, umidità e ponti di installazione. Il classico guadagno reale rispetto al progetto teorico è del 10-20% in peggio se la posa è disattenta."),
s("Sistemi ETICS", "Il sistema ETICS a colla: gli strati e il funzionamento d'insieme",
 "Il cappotto ETICS (External Thermal Insulation Composite System) è un sistema a strati composto: collante di fissaggio, pannello isolante, tasselli meccanici di ancoraggio, rete di rinforzo armata con rasante, finitura (civile, vernice, rivestimento). È un KIT certificato: le componenti devono stare insieme come da valutazione tecnica europea (EAD 040083-00-0404, ex ETAG 004), non si miscelano a piacere.",
 "Strati funzionali: collante applicato a striscie perimetrali e schiacciotti centrali su superficie regolare; tasselli con chiodo in acciaio/plastica a passo indicativo 4-6/m² in zona ordinaria e di più ai bordi (passo tipico: 4-6/m² zona campo, rinforzato sotto 2/m² ai bordi, angoli e controtelai — sempre secondo valutazione del sistema); rete incollata su tutta la superficie con giunti scoperti o sovrapposti secondo scheda tecnica (mai pezzi scomposti); rasante 3-5 mm; finitura dopo maturazione (giorni, non ore).",
 "Nuove costruzioni, ristrutturazioni di edifici residenziali e terziario, recupero del patrimonio con risanamento energetico.",
 "Il sistema a strati pesa 25-40 kg/m² in meno di un muro equivalente; interrompe i ponti termici in modo continuo; la finitura protegge l'isolante da UV e urti; i tempi di cantiere sono rapidi (giorni per facciata).",
 "È un sistema 'meticoloso': ogni strato dipende dal precedente; la garanzia decade se si usano componenti non previsti dalla valutazione; le facciate esposte a nord o con salsedine richiedono finiture dedicate; l'incendio in facciata è il limite strutturale (vedi scheda antincendio).",
 "Ordini di grandezza indicativi (materiale+posa): 60-100 €/m² EPS 10 cm; 80-130 €/m² lana di roccia; sovrapprezzo finitura silossanica o rivestimento +10-30 €/m².",
 "Cantiere con rete posata 'a pezzi' sopra il rasante (pratica scorretta): dopo due inverni la facciata mostrava mappe di fessure in corrispondenza dei giunti. Il rifacimento rasante+rete integrale costò 18 €/m² contro i 4 €/m² di posa corretta originaria.",
 "EAD 040083-00-0404 (ex ETAG 004: sistemi ETICS, valutazione tecnica europea); marcatura CE dei sistemi ETICS; schede tecniche dei produttori di sistemi (componenti vincolate alla valutazione).",
 "Regola d'oro: il cappotto non si compone al momento dal ferramenta sotto casa: si specifica un SISTEMA con valutazione tecnica e si posa con le sue componenti. Il tassello giusto è quello del sistema (chiodo, lunghezza, testa), non quello 'simile'."),
s("Posa", "La posa del cappotto: superficie, colla, tasselli, rete, rasante",
 "La posa vale il 70% del cappotto: gli errori di posa sono la prima causa di crepe, distacchi e muffa. Sequenza professionale: verifica piano di posa (tolleranze della facciata), guida a filo o profili, spessore minimo e regolarità, applicazione collante, posa pannelli incrociando i giunti, attesa di maturazione (giorni), rasante+rete, finitura. Condizioni: superficie asciutta, temperature tipiche tra +5 °C e +30 °C senza gelo né sole diretto violento, protezione da pioggia e vento.",
 "Tecnica: collante a striscie perimetrali con schiacciotto centrale (camera d'aria contro i vuoti); pannelli incollati a incastro con giunti sfalsati; tassellazione dopo 2-3 giorni di maturazione (se prevista dal sistema); rasante con rete premessa o applicata durante la rasatura; bordi e spigoli con profili a goccia e profili di protezione; giunzioni tra fasi lavorative con rete a sovrapposizione e profili di giunzione.",
 "Cantieri di ristrutturazione residenziale, edilizia terziaria, capannoni e strutture industriali di medi/piccola scala.",
 "La posa a regola d'arte elimina il 90% delle patologie: la rete integrale e i profili perimetrali sono il costo più basso e il beneficio più alto dell'intero cappotto; la verifica intermedia (controllo colla, passo tasselli) prima del rasante evita il ripristino a opera finita.",
 "Dipende fortemente dalla manodopera: la stessa sacca di colla dà risultati opposti; il caldo secco estivo fa ritirare il rasante in fessure; la pioggia su pannelli freschi degrada la tenuta; i ponteggi sporchi e il maltrattamento post-posa causano danni locali.",
 "Costo posa (manodopera) indicativo: 30-60 €/m² comprensivo di ponteggio (il ponteggio da solo vale 12-25 €/m²).",
 "Cantiere estivo a 35 °C: rasature a mezzogiorno su facciata sud: fessurazione diffusa entro luglio. Il rifacimento delle rasature in fascia oraria controllata (mattina/sera) con protezione solare risolse: la lezione entra in cantiere come regola di programmazione.",
 "Istruzioni di posa dei sistemi ETICS (documento vincolante); requisiti delle malte: UNI EN 998-1 (malte per intonaci e cappotti); regole dell'arte ETICS (valutazione tecnica del sistema applicata).",
 "Per il LLM: le tre domande di collaudo visivo prima del rasante sono: 1) la colla copre ≥ il 40% della superficie del pannello senza vuoti? 2) i tasselli sono a passo di scheda tecnica (bordi rinforzati)? 3) la rete è integrale senza pezzi a martello? Se una delle tre è no, il difetto va corretto PRIMA del rasante."),
s("Dettagli", "I dettagli che fanno fallire il cappotto: zoccolo, davanzali, cappelli, giunzioni",
 "Le patologie del cappotto nascono quasi sempre nei dettagli, non nel campo: zoccolo (spessori, protezione da urti e pioggia battente), davanzali e soglie di finestre (taglio termico e tenuta), cappello di coronamento (protezione dall'acqua), giunzioni tra fasi lavorative e tra corpi di fabbrica, controtelai, attraversamenti di tubi e cassonetti, parapetti. Ogni passaggio va risolto con profili, sigillature coerenti e continuità dello strato isolante.",
 "Dettaglio tipo: profilo zoccolo con spessore crescente o taglio a 45°; davanzale con sporgenza, ritorno protetto e sigillatura perimetrale elastica; cappello con profilo gocciolatoio e coronamento; giunzione verticale con profilo e rete a sovrapposizione ≥ 10 cm; controtelai ancorati al telaio isolato o interrotti dall'isolante; passaggi tubi con collare e sigillatura; parapetti con taglio termico o isolamento continuo.",
 "Progettazione esecutiva, preventivi con computo dei particolari, collaudi e diagnostica delle patologie in garanzia.",
 "Un dettaglio risolto bene vale più di 2 cm di isolante in più: la continuità dello strato è la vera prestazione; i profili metallici costano pochi euro al metro e salvano la facciata; la sigillatura elastica ai davanzali elimina le infiltrazioni estetiche e strutturali.",
 "I dettagli richiedono progetto e non improvvisazione di cantiere; i pezzi speciali costano e rallentano; la manutenzione futura (rifacimento sigillature ogni 8-15 anni) va dichiarata al committente; l'errore di dettaglio si paga caro (sostituzione localizzata ma esteticamente visibile).",
 "Ordini di grandezza indicativi: profili perimetrali 2-6 €/m; sigillatura perimetrale professionale 3-8 €/m; rifacimento locale di un dettaglio compromesso 60-150 €/punto.",
 "Villa con muffa persistente sotto i davanzali dopo il cappotto: la diagnostica mostrava davanzali non ripassati e giunti di sigillatura assenti: l'acqua di risalita capillare e pioggia batteva il davanzale freddo. Rifacimento dei dettagli con profilo, ritorno isolato e sigillatura: problema risolto in 3 giorni di lavoro.",
 "Linee guida dei sistemi ETICS per i particolari costruttivi; regole dell'arte per sigillature elastiche (EN 15651 per i prodotti sigillanti facciate).",
 "Domanda guida per il LLM: 'dove finisce il cappotto?' — Se la risposta è 'al davanzale e basta', il progetto è incompleto. La continuità dello strato isolante si verifica disegno per disegno: zoccolo, davanzali, cappelli, giunzioni, controtelai, attraversamenti."),
s("Posizione isolamento", "Dove isolare: esterno, interno, intercapedine e il rischio muffa interstiziale",
 "La posizione dell'isolamento decide funzionamento igrometrico e prezzo. Isolamento esterno (ETICS o ventilato): la struttura resta calda e traspira verso l'interno, il rischio interstiziale è basso se il muro esistente è asciutto. Isolamento interno: più economico e possibile su facciate vincolate, ma sposta il punto di rugiada verso l'interno: richiede materiali specifici (perm-selectivi, fibre), attenzione a ponti termici e mobili appoggiati. Cappotto intercapedine: possibile in alcune murature a doppia parete.",
 "Criteri di scelta: esposizione e rischio muffa (interno solo con calcolo igrometrico), facciate vincolate (esterno non ammissibile: interno con materiali ad altra diffusione al vapore), igiene (mobili appoggiati sulle pareti nord: correnti fredde e muffa), ventilazione dell'ambiente (cappa e VMC incidono), tenuta all'aria dell'involucro.",
 "Ristrutturazioni di edifici vincolati, interni di locali tecnici, torri e corpi non raggiungibili dall'esterno.",
 "L'esterno protegge la struttura e aumenta l'inerzia termica estiva; l'interno è rapido e non tocca la facciata (vantaggio estetico e amministrativo); l'intercapedine recupera spazi vuoti esistenti.",
 "L'interno mal fatto è la prima causa di muffa post-ristrutturazione; l'esterno costa di più e richiede ponteggio; l'intercapedine dipende dalla geometria esistente; in ogni caso serve la verifica igrometrica (software o nomogrammi) prima di decidere.",
 "Costi comparativi indicativi: cappotto esterno completo 60-130 €/m² (con ponteggio), isolamento interno con materiali igrometrici 45-90 €/m², intercapedine a insufflaggio 25-60 €/m² (solo se la geometria lo consente).",
 "Appartamento anni '60 con muffa ricorrente sulle pareti nord interne dopo un 'cappotto interno economico' in EPS: il calcolo igrometrico mostrava il punto di rugiada dentro il muro umido. Soluzione: rimozione, essiccazione della parete e rifacimento in fibra di legno con barriera sagomata: nessuna muffa nei successivi inverni.",
 "UNI EN ISO 13788 (progettazione contro la condensa interstiziale: metodo del Glaser); requisiti igrometrici per materiali interni nelle linee guida dei sistemi; ventilazione UNI EN 15665 (criteri generali ventilazione residenziale).",
 "Regola per il LLM: consigliare l'isolamento interno su parete perimetrale senza aver visto l'igrometro del muro e calcolato il rischio di rugiada è un errore professionale: la muffa post-intervento è la contestazione più comune e la più costosa in garanzia."),
s("Ponti termici", "Il cappotto come cura dei ponti termici: angoli, pilastri, balconi",
 "Il ponteggio termico localizzato (Ψ, W/mK) brucia il beneficio dell'isolamento: angoli, pilastri in cemento a vista, travi di balcone, cornicioni, pilastrini di cantina. Il cappotto continuo esterno è la cura più efficace: copre gli elementi sporgenti e uniforma la superficie. Il punto critico tipico è il balcone: la trave che taglia il cappotto è un ponte termico seriale.",
 "Strategie: cappotto continuo anche sulle spalle dei balconi dove possibile; coibentazione del capitello del balcone (lato superiore o inferiore della trave) con sistemi a piastra; interruzione termica strutturale del nuovo balcone (connettori termoisolanti certificati); correzione degli angoli interni con isolamento rinforzato; verifica pre-intervento con termografia o calcolo dei Ψ.",
 "Ristrutturazioni di edifici con balconi sporgenti, torri in cemento, edifici industriali con pilastri a vista.",
 "Il cappotto cura i ponti termici esistenti senza demolire: balconi, angoli e pilastri coperti migliorano subito temperatura superficiale (niente muffa e condensa); la termografia prima/dopo documenta il miglioramento per Legge 10 e garanzie.",
 "Il balcone incastrato resta il punto debole: la cura perfetta richiede demolizione e ricostruzione con interruzione (costo alto) o accettazione di un ponte residuo; i dettagli di interruzione sono delicati in facciata a vento; le finiture sui profili metallici vanno coordinate.",
 "Ordini di grandezza indicativi: coibentazione capitello balcone 150-400 €/punto; balcone nuovo con interruzione termica +800-2.000 € rispetto al tradizionale; termografia pre/post 250-600 €.",
 "Condominio con muffa sui soffitti dei balconi al piano rialzato: la termografia mostrava ponti termici alle travi dei balconi coperte solo parzialmente. Il rifacimento dei capitelli coibentati e la chiusura continua del cappotto sui fianchi risolsero la muffa in una stagione.",
 "UNI EN ISO 10211 (calcolo dei ponti termici); UNI EN ISO 14683 (valori Ψ tabellari); cataloghi Ψ dei produttori per i dettagli tipo; linee guida nazionali per la correzione dei ponti termici.",
 "Per il LLM: quando un cliente chiede 'il cappotto mi toglie la muffa?', la risposta professionale dipende dai ponti termici: la termografia pre-intervento li trova; la strategia balconi/angoli/pilastri si decide PRIMA del contratto, non sul ponteggio."),
s("Antincendio", "Reazione al fuoco e vincoli in altezza: EPS vs lana minerale",
 "La reazione al fuoco dell'isolante vincola il progetto: lana minerale Euroclasse A1/A2 (non contribuisce), EPS con fiamma ritardante Euroclasse E (contribuisce ma si autoestinguerebbe? no: E = combustibile con gocciolamento), finiture e strati di collante/rasante determinano la classe del sistema completo (classificazione UNI EN 13501-1). Edifici alti, vicini a confini, ospedali e scuole spingono verso soluzioni A2 o migliori.",
 "Criteri: classe di reazione del sistema ETICS completo (non del solo pannello); vincoli per altezza e destinazione d'uso secondo normativa antincendio e regolamenti locali; soluzioni in lana minerale con finiture intonaco per classe migliore; barriere antincendio orizzontali tra piani secondo valutazione del sistema; distanze da confini, grondaie e aree esterne.",
 "Progettazione di edifici >4 piani, strutture sanitarie e scolastiche, condomìni in zona densificata.",
 "La lana minerale elimina il rischio propagazione: le facciate in classe A2 danno tranquillità assicurativa e amministrativa; i costi extra rispetto a EPS sono contenuti se confrontati con il rischio; la scelta 'sicura' facilita i permessi.",
 "Il costo della lana minerale è +30-60% rispetto all'EPS; i sistemi ad alta classe richiedono componenti certificate e posa più rigida; le verifiche di conformità aumentano i tempi; un errore di miscelazione componenti può abbassare la classe certificata.",
 "Ordini di grandezza indicativi: supplemento lana di roccia vs EPS +20-40 €/m²; sistema ETICS in classe A2 completo: +30-60 €/m² rispetto al sistema EPS base.",
 "Residenza per anziani con vincolo di classe A2: il progetto base in EPS sarebbe stato rifiutato in istruttoria. La conversione a sistema in lana di roccia con finitura minerale passò la verifica al primo giro: il sovrapprezzo (≈45 €/m² su 1.200 m²) era inferiore al costo di un fermo istruttorio.",
 "UNI EN 13501-1 (classificazione reazione al fuoco); valutazioni tecniche europee dei sistemi ETICS (reazione al fuoco come caratteristica del sistema); normativa antincendio per altezza e destinazione d'uso (DM interni e regolamenti locali).",
 "Regola per il LLM: la classe di reazione al fuoco si dichiara per il SISTEMA completo (pannello+collante+rasante+finitura): dire 'EPS classe E' non basta a certificare la facciata. Ogni progetto superiore ai 4 piani va verificato con il classificatore antincendio prima della scelta dell'isolante."),
s("Patologie", "Patologie del cappotto: crepe, alghe, distacchi, riparazioni",
 "Le patologie tipiche del cappotto: fessurazione del rasante (posa, movimenti del supporto, caldo), macchie biologiche (alghe su finiture a nord, condensa), distacchi localizzati (colla insufficiente o supporto sporco), danni meccanici (urti, giochi), scolorimento e degrado UV (finiture scadenti). La diagnosi corretta distingue la causa strutturale da quella di finitura: la cura cambia.",
 "Diagnostica: termografia (ponti termici e distacchi pieni/vuoti), percussione per distacchi, anamnesi del cantiere (componenti usati, stagione, giunzioni), campionatura rasante; riparazioni: taglio della zona malata fino a pannello sano, ricollaggio con rasante dello stesso sistema, rete di ripresa con sovrapposizione, rasatura e finitura; protezione degli spigoli con profili.",
 "Diagnostica pre-acquisto di immobili ristrutturati, manutenzione programmata del patrimonio, gestione garanzie.",
 "La riparazione localizzata ben eseguità è invisibile e durevole se usa le componenti del sistema originario; la termografia trova i distacchi prima che cadano; la finitura di qualità (silossanica, quarzo) riduce alghe e sporco del 50-70%.",
 "Le riparazioni con materiali non compatibili danno il classico 'pezzo' visibile; l'intervento su metà facciata espone la differenza cromatica; l'attesa di maturazione tra rasature rallenta il cantiere; la garanzia del sistema richiede riparazioni con componenti originali.",
 "Ordini di grandezza indicativi: riparazione localizzata 40-120 €/punto; lavaggio finitura e trattamento anti-alghe 4-10 €/m²; rifacimento rasante di una zona 15-35 €/m².",
 "Condominio con 'bolle' sul cappotto a 3 anni dal collaudo: la percussione mappò distacchi pieni su 60 m²; la causa era colla stesa su intonaco non decerato e bagnato. Il rifacimento della zona con preparazione corretta costò 25 €/m² e non ha dato più problemi in 6 anni.",
 "Linee guida dei sistemi per le riparazioni; UNI EN 998-1 (malte); UNI EN 15824 (intonaci organici: requisiti).",
 "Per il LLM: la domanda 'perché si è rotto?' si risponde con DIAGNOSI, non con stucco: la causa prima (colla, giunto, ponte termico, urto) determina la cura. La riparazione a stucco senza rete di ripresa è una pezza che si rivede in un inverno."),
s("Cantieri", "Cantieri di cappotto: organizzazione, ponteggi, tempi, sicurezza",
 "Il cantiere del cappotto è logistica: ponteggio a servizio continuo della facciata, protezione dal vento e pioggia, stoccaggio dei pannelli (al riparo da sole e pioggia), gestione dei giunti di fase, coordinamento con altri lavori (finestre, lattoneria, tinteggiatura). Il ponteggio vale 12-25 €/m²: incide più della scelta tra EPS e lana di roccia in molti appalti.",
 "Organizzazione tipo: verifica supporto e segnalazione difetti, posa pannelli (giorni per facciata di palazzina), maturazione, rasatura+rete, finitura; protezione di pioggia e vento forte (il vento sopra i 10-15 m/s ferma la posa dei pannelli leggeri); coordinamento dei passaggi (tubi, gronde, condizionatori) PRIMA del rasante; pulizia continua (i pannelli tagliati lasciano palline EPS che il vento sparge).",
 "Appalti di ristrutturazione di condomìni e edilizia terziaria; coordinamento tra imprese (cappotto, serramenti, lattoneria, tinteggi).",
 "La buona organizzazione dimezza i tempi: i dettagli e i passaggi risolti prima del rasante evitano forature e rattoppi; la protezione dalle intemperie salva il risultato; la pulizia del cantiere è il primo biglietto da visita (e il primo controllo qualità).",
 "Il ponteggio dipende da terzi (ritardi bloccano tutto); il maltempo ferma la posa e dilata i tempi; il coordinamento con altre imprese richiede un direttore lavori presente; i vicinati lamentano polvere e palline EPS (gestione del cantiere inclusa).",
 "Costi accessori indicativi: ponteggio 12-25 €/m² (noleggio+montaggio), protezioni e reti 2-5 €/m², trasporto e smaltimento 1-3 €/m².",
 "Cantiere di condominio con cappotto e sostituzione serramenti sovrapposti: le finestre sono arrivate dopo il rasante: i fori per i cassonetti hanno bucato il cappotto fresco in 14 punti. Il coordinamento sequenziale (serramenti PRIMA del rasante) sarebbe costato zero in più: le riparazioni costarono 3.200 €.",
 "Requisiti ponteggi: UNI EN 12810 e UNI EN 12811 (ponteggi di accesso e di servizio); sicurezza cantieri D.Lgs 81/2008 (Titolo IV); istruzioni di posa dei sistemi ETICS (sospensione per vento/pioggia).",
 "Domanda guida per il LLM: 'cosa arriva prima, il cappotto o gli altri lavori?' — la sequenza corretta per i lavori di facciata è: struttura e tetti, impianti di facciata, serramenti, cappotto, finiture esterne. Ogni inversione si paga in riparazioni."),
s("Economia", "Costi e benefici del cappotto: il conto professionale",
 "Il cappotto è l'intervento di riqualificazione con il miglior rapporto costo/beneficio disponibile in Italia: il costo completo si misura in €/m² di parete trattata e il beneficio in kWh/anno risparmiati e in comfort (temperatura superficiale, niente muffa). Il conto professionale include: isolante, colla/tasselli/rete/rasante/finitura, ponteggio, manodopera, dettagli, oneri di cantiere.",
 "Struttura del costo tipica (percentuali indicative su totale posato): materiali sistema 25-35%, manodopera 30-40%, ponteggio 15-25%, dettagli e profili 5-10%, oneri e trasporti 5-10%. Benefici tipici: su muratura antica non isolata il risparmio invernale varia dal 20 al 40% del fabbisogno di riscaldamento (in funzione di zona, spessore, ponte termici); il comfort estivo migliora con l'inerzia protetta.",
 "Preventivi, analisi di fattibilità, confronto tra offerte (stesso sistema e stesso spessore), detrazioni e Conto Termico 3.0 (per l'isolamento delle superfici opache: percentuali e soglie da verificare sulle Regole Applicative GSE vigenti).",
 "L'investimento si ripaga in 5-12 anni tipicamente (in funzione del clima e del costo dell'energia); il valore immobiliare aumenta (classe energetica e assenza di muffa); l'intervento è il più rapido per migliorare una classe energetica di un livello intero.",
 "Il risparmio reale può deludere se ponti termici e finestre restano cattivi (il cappotto da solo non basta); il payback dipende dal prezzo dell'energia; il bonus fiscale cambia nel tempo e va verificato all'anno di intervento; la qualità del cantiere sposta il risultato più dello spessore.",
 "Ordini di grandezza indicativi: cappotto EPS 10 cm completo 60-100 €/m²; cappotto in lana di roccia 80-130 €/m²; payback tipico 5-12 anni; incentivo Conto Termico 3.0 per superfici opache: percentuali e massimali da verificare sulle Regole Applicative GSE vigenti (l'edizione 2025 riporta 40% base, 50% zone climatiche E e F, 55% in combinazione con altri interventi ammissibili).",
 "Confronto di due preventivi per la stessa palazzina: offerta A 62 €/m² (sistema completo, ponteggio incluso) vs offerta B 54 €/m² (materiale sconosciuto, ponteggio escluso, dettagli non quotati). Il conto corretto portò B a 71 €/m²: la 'convenienza' era un miraggio. L'offerta A fu scelta: lavori finiti in 6 settimane con zero pezze.",
 "D.Lgs 192/2005 (requisiti energetici); Conto Termico 3.0 (D.M. 7/8/2025 e Regole Applicative GSE per percentuali e massimali); UNI EN ISO 13790 (calcolo fabbisogno energetico).",
 "Per il LLM: il confronto tra preventivi di cappotto si fa a parità di SISTEMA (stesso EAD, stesso spessore, stesso ponte), altrimenti è un confronto tra cose diverse. La voce 'materiale isolante €/m²' da sola non dice il prezzo dell'opera: mancano ponteggio, manodopera, dettagli e oneri."),
]

os.makedirs(os.path.join(ROOT, "schede"), exist_ok=True)
with io.open(os.path.join(ROOT, "schede", "schede.jsonl"), "w", encoding="utf-8") as f:
    for d in DATA:
        f.write(json.dumps(d, ensure_ascii=False) + "\n")

COURSE = """corso: "Isolamento termico a cappotto (ETICS): materiali, sistemi, posa e patologie"
facolta: "FACOLTA_TECNOLOGIA_E_COSTRUZIONE"
livello: "L2"
schede: {n}
formato: "JSONL"
lingua: "it"
schema_campi: [categoria, nome, descrizione, tecnologia, applicazioni, vantaggi, limiti, costi_e_economia, casi_real_world, normative, note_cantiere]
""".format(n=len(DATA))
io.open(os.path.join(ROOT, "COURSE.yaml"), "w", encoding="utf-8").write(COURSE)
print("CAPPOTTO_ETICS:", len(DATA), "schede")
