# -*- coding: utf-8 -*-
"""Genera parsed/conto_termico_3_0.jsonl — sintesi tecnica strutturata sul Conto Termico 3.0
e gli incentivi energetici italiani, redatta su atto pubblico (DM 7/8/2025, GU 224/2025)
e fonti ufficiali GSE verificate. Licenza: pubblico dominio / sintesi originale."""
import json, os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "parsed", "conto_termico_3_0.jsonl")

GU = "https://www.gazzettaufficiale.it/eli/id/2025/09/26/25A05263/sg"
ATTR = "Sintesi redatta da Kimi su D.M. 7 agosto 2025 (GU n. 224 del 26-9-2025), Regole Applicative GSE approvate il 19-12-2025 e fonti istituzionali - atto pubblico"
LIC = "Pubblico dominio (atto pubblico italiano) + sintesi originale"
SRC = "sintesi_kimi_conto_termico_3_0"

RECIPES = [
("Conto Termico 3.0 - Inquadramento generale",
"""Il Conto Termico 3.0 e' il meccanismo di incentivazione nazionale per interventi di piccole dimensioni di incremento dell'efficienza energetica e di produzione di energia termica da fonti rinnovabili, istituito dal D.M. 7 agosto 2025 del Ministero dell'Ambiente e della Sicurezza Energetica (MASE), pubblicato nella Gazzetta Ufficiale n. 224 del 26 settembre 2025 e in vigore dal 25 dicembre 2025. E' la terza versione dello strumento: la prima (Conto Termico 1.0) fu istituita dal D.M. 28 dicembre 2012, la seconda (Conto Termico 2.0) dal D.M. 16 febbraio 2016. La base normativa e' l'articolo 28 del D.Lgs. 3 marzo 2011, n. 28 (attuazione direttiva 2009/28/CE), che impone l'aggiornamento periodico del meccanismo. A differenza delle detrazioni fiscali, il Conto Termico e' un contributo diretto a fondo perduto erogato dal GSE (Gestore dei Servizi Energetici) sul conto corrente del beneficiario a fine lavori, mediante bonifico. Le risorse disponibili sono complessivamente pari a 900 milioni di euro annui: 400 milioni destinati agli interventi delle amministrazioni pubbliche e 500 milioni agli interventi dei soggetti privati (di cui una quota riservata alle imprese). La misura concorre agli obiettivi del Piano Nazionale Integrato per l'Energia e il Clima (PNIEC) e alle politiche di riqualificazione energetica del patrimonio edilizio, in coerenza con la direttiva EPBD (case verdi) e con l'articolo 10 del D.Lgs. 199/2021."""),

("Conto Termico 3.0 - Beneficiari ammessi",
"""La platea dei beneficiari del Conto Termico 3.0 e' ampliata rispetto alla versione 2.0. Possono accedere agli incentivi: (1) le pubbliche amministrazioni, incluse scuole, ospedali, universita', enti locali, societa' in house e concessionari di servizi pubblici; (2) i soggetti privati - persone fisiche, condomini e imprese - proprietari, possessori o detentori (anche affittuari e comodatari) di edifici esistenti; (3) gli enti del Terzo Settore, le cooperative sociali e di abitanti; (4) le comunita' energetiche rinnovabili (CER) e le configurazioni di autoconsumo collettivo, per specifiche tipologie di intervento. Gli interventi su edifici residenziali riguardano le categorie catastali del gruppo A ad esclusione di A/8 (ville e villini di lusso?), A/9 e A/10; l'ambito terziario privato e' ammesso per la prima volta agli interventi di efficienza energetica e comprende anche edifici industriali (gruppi B, C esclusi C/6 e C/7, D escluso D/9, E esclusi E/2, E/4 ed E/6). Le imprese di ogni dimensione possono realizzare interventi su immobili a uso produttivo o terziario. Requisito essenziale: l'edificio deve essere esistente e dotato di impianto di climatizzazione invernale gia' funzionante; non sono ammessi interventi su edifici di nuova costruzione ne' su pertinenze senza generatore termico esistente."""),

("Conto Termico 3.0 - Interventi di efficienza energetica ammessi",
"""Gli interventi di incremento dell'efficienza energetica incentivati dal Conto Termico 3.0 sono: (a) isolamento termico di superfici opache delimitanti il volume climatizzato, anche unitamente all'installazione di sistemi di ventilazione meccanica, ammissibile - secondo i criteri gia' usati per l'Ecobonus - quando sia l'unica soluzione tecnica o la piu' conveniente per risolvere problemi di muffe e condensazioni interstiziali calcolati secondo la UNI EN ISO 13788; (b) sostituzione di chiusure trasparenti comprensive di infissi delimitanti il volume climatizzato; (c) installazione di sistemi di schermatura e/o ombreggiamento e/o di filtrazione solare esterni per chiusure trasparenti con esposizione da est-sud-est a ovest, fissi o mobili, non trasportabili; (d) trasformazione degli edifici esistenti in edifici a energia quasi zero (NZEB); (e) sostituzione di sistemi per l'illuminazione di interni e pertinenze esterne con sistemi efficienti; (f) installazione di tecnologie di gestione e controllo automatico (building automation) degli impianti termici ed elettrici, ivi comprese termoregolazione e contabilizzazione del calore; (g) installazione di elementi infrastrutturali per la ricarica privata di veicoli elettrici, anche aperta al pubblico, presso l'edificio, le pertinenze o i parcheggi adiacenti, a condizione che l'intervento sia realizzato congiuntamente alla sostituzione di impianti di climatizzazione invernale con impianti dotati di pompe di calore elettriche; (h) installazione di impianti solari fotovoltaici e relativi sistemi di accumulo, presso l'edificio o le pertinenze, nella stessa condizione di contestualita' con la pompa di calore elettrica. Novita' rispetto al 2.0: sono stati RIMOSSI gli interventi di sostituzione con generatori di calore a condensazione (in coerenza con la direttiva EPBD 2024/1275 e con l'orientamento all'elettrificazione dei consumi) e sono stati aggiunti fotovoltaico 'trainato', accumuli, colonnine di ricarica e building automation."""),

("Conto Termico 3.0 - Interventi di produzione di energia termica da FER",
"""Gli interventi di produzione di energia termica da fonti rinnovabili incentivati comprendono: (1) sostituzione di impianti di climatizzazione invernale esistenti con impianti dotati di pompe di calore elettriche o a gas, anche in combinazione con scaldacqua elettrici; (2) sostituzione con sistemi ibridi factory made a pompa di calore; (3) sostituzione con pompe di calore 'add on' (generatore a pompa di calore installato ad integrazione di una caldaia a condensazione a gas preesistente) e sistemi bivalenti (pompa di calore come generatore principale abbinata a caldaia a condensazione a gas o a generatore a biomassa come secondario, non assemblati in fabbrica) - queste due configurazioni sono una novita' assoluta del panorama legislativo nazionale; (4) installazione di impianti solari termici, anche per solar cooling; (5) sostituzione di impianti esistenti con generatori di calore alimentati a biomassa (caldaie, stufe, termocamini a legna o pellet), nel rispetto dei requisiti di emissione; (6) sostituzione di scaldacqua elettrici e a gas con scaldacqua a pompa di calore. Per i sistemi ibridi e bivalenti le Regole Applicative definiscono le potenze di riferimento per le annualita' di incentivo, l'accesso al catalogo degli apparecchi idonei e il vincolo di non sovradimensionamento oltre il 10% rispetto alla potenza del generatore sostituito. Sono ammessi sia apparecchiature nuove sia apparecchi e componenti ricondizionati, questi ultimi conformi ai requisiti minimi di ecoprogettazione vigenti (economia circolare)."""),

("Conto Termico 3.0 - Percentuali di contributo e massimali",
"""Le percentuali di contributo del Conto Termico 3.0 sono modulate per tipologia di beneficiario e intervento. Per privati e pubbliche amministrazioni il contributo arriva complessivamente fino al 65% delle spese ammissibili per la produzione di calore da FER e fino al 40-50% per gli interventi di efficienza energetica sull'involucro; il decreto fissa aliquote per singola tipologia (si rinviene nel testo valori quali 65%, 50%, 40%, 30%, 25%, 20%, 15% e 5%). Per le amministrazioni pubbliche e gli enti del Terzo Settore che intervengono su edifici pubblici situati in comuni con meno di 15.000 abitanti, oppure su scuole, strutture sanitarie e RSA, l'incentivo puo' arrivare fino al 100% delle spese ammissibili. Per le imprese gli incentivi sono piu' contenuti - indicativamente fino al 25% per l'efficienza energetica e fino al 45% per le rinnovabili termiche - con maggiorazioni previste per le PMI, per gli interventi realizzati in zone assistite (aree crisi industriale, zone terremotate) e per gli interventi che riducono i consumi di energia primaria di almeno il 40%. Per i pacchetti fotovoltaico piu' accumulo installati congiuntamente alla pompa di calore il contributo e' fissato al 20% della spesa con un tetto massimo di 100.000 euro per progetto. Erogazione: per importi fino a 15.000 euro (soglia elevata rispetto ai 5.000 del 2.0) l'incentivo e' erogato in un'unica soluzione; oltre tale soglia in rate annuali costanti, da 2 a 5 anni a seconda della potenza/tipologia. Le spese ammissibili includono IVA (se a costo), trasporto, prestazioni professionali connesse; sono fissati costi massimi ammissibili per singola tipologia."""),

("Conto Termico 3.0 - Iter procedurale e PortalTermico",
"""L'accesso agli incentivi avviene tramite il PortalTermico 3.0 del GSE, attivo dal 2 febbraio 2026. Per i soggetti privati l'accesso e' diretto: la domanda va presentata entro 90 giorni dalla conclusione dei lavori, con modalita' semplificata per gli apparecchi prequalificati nel catalogo GSE. Per le pubbliche amministrazioni e' prevista la modalita' di prenotazione dell'incentivo (richiesta preliminare prima dell'avvio dei lavori), con possibilita' di richiedere un anticipo (fino al 50%) sui costi di diagnosi energetica e APE. La domanda deve essere corredata di: documentazione tecnica dell'intervento, fotografie prima/dopo, computo metrico estimativo, fatture, dichiarazioni di conformita' dell'impianto secondo il D.M. 37/2008, asseverazione del tecnico abilitato (ingegnere, architetto, geometra, perito) che certifica il rispetto dei requisiti del decreto. Il pagamento avviene tramite bonifico sul conto corrente indicato, con causale che riporti il riferimento al D.M. 7 agosto 2025. Il GSE effettua controlli a campione e a posteriori; la dichiarazione mendace comporta revoca dell'incentivo e sanzioni. Il GSE ha pubblicato le Regole Applicative (approvate dal MASE il 19 dicembre 2025), lo schema di convenzione per l'accesso tramite ESCO e il catalogo degli apparecchi prequalificati. Storico operativo 2026: il portale e' stato attivato il 2 febbraio 2026, sospeso il 3 marzo 2026 per esubero di domande (circa 1,3 miliardi di euro di richieste contro la dotazione annua), e riaperto il 13 aprile 2026 in accesso diretto solo per lavori gia' conclusi; successivamente la dotazione e' stata rimodulata (450 milioni per i privati e 450 milioni per la PA) con decreto direttoriale."""),

("Conto Termico 3.0 - Catalogo apparecchi prequalificati GSE",
"""Il Conto Termico 3.0 introduce il catalogo degli apparecchi prequalificati gestito dal GSE, pubblicato nell'aprile 2026: apparecchiature gia' verificate dal GSE come conformi ai requisiti del decreto, per le quali la domanda di incentivo segue una procedura documentale semplificata (il richiedente seleziona l'apparecchio dal catalogo anziche' documentare integralmente i requisiti tecnici). Il catalogo e' articolato in categorie: III.A pompe di calore elettriche e a gas per climatizzazione invernale e produzione di acqua calda sanitaria; III.B sistemi ibridi factory made e sistemi bivalenti; III.C generatori di calore a biomassa; III.D impianti solari termici; III.E scaldacqua a pompa di calore. L'apparecchio deve rispondere ai requisiti di ecoprogettazione ed etichettatura energetica UE richiamati dal decreto; per le pompe di calore sono rilevanti la classe energetica stagionale (SCOP per riscaldamento, SEER per raffrescamento) e le specifiche per unita' idroniche, aria-aria, aria-acqua, geotermiche e ibridate. L'uso del catalogo e' fortemente raccomandato agli operatori per snellire la pratica; le apparecchiature non in catalogo restano ammissibili con documentazione tecnica completa."""),

("Conto Termico 3.0 - Cumulabilita' e incompatibilita'",
"""Il Conto Termico 3.0 non e' cumulabile con altre agevolazioni pubbliche per la medesima spesa: per lo stesso intervento e lo stesso importo non si possono cumulare detrazioni fiscali (Ecobonus, Bonus ristrutturazioni, Superbonus residuo), altri contributi statali o regionali o incentivi tariffari a carico delle tariffe elettriche e del gas. Il GSE richiede espressa rinuncia alle altre forme di incentivazione per la stessa spesa. Resta ferma la possibilita' di cumulo 'orizzontale' tra interventi diversi dello stesso edifico finanziati ciascuno con lo strumento piu' conveniente (ad esempio Conto Termico per la pompa di calore e detrazione fiscale per i serramenti, su fatture separate e lavori distinti). Per gli edifici pubblici il decreto consente integrazioni fino al 100% delle spese tramite combinazione con altre fonti di finanziamento ammesse. La scelta tra Conto Termico e detrazione fiscale va fatta per ogni intervento confrontando: percentuale di copertura, tempi di erogazione (bonifico diretto vs detrazione in 10 rate annuali), vincoli di pratica (asseverazione, catalogo apparecchi) e disponibilita' di fondi (Conto Termico a sportello con plafond annuo)."""),

("Conto Termico 3.0 - Passaggio dal 2.0 al 3.0: regole transitorie",
"""Le regole di transizione dal Conto Termico 2.0 (D.M. 16 febbraio 2016) al 3.0: (1) le istanze trasmesse prima del 25 dicembre 2025 restano disciplinate dal 2.0; (2) gli interventi 2.0 conclusi dal 26 dicembre 2025 devono essere caricati entro 60 giorni dalla conclusione dei lavori; (3) per gli interventi delle pubbliche amministrazioni con prenotazione 2.0 gia' accolta e lavori non conclusi alla data di entrata in vigore, il 2.0 continua ad applicarsi fino al completamento; (4) per le PA restano ammessi ai requisiti 2.0 gli interventi di sostituzione con generatori a condensazione se coperti da contratto di prestazione energetica o di approvvigionamento stipulato prima del 1 gennaio 2025, con istanza entro un anno dall'entrata in vigore (25 dicembre 2026); (5) per gli interventi realizzati da imprese ed enti del Terzo Settore i cui lavori fossero stati avviati dal 7 agosto 2025 e non ancora conclusi al 25 dicembre 2025 e' stato consentito l'invio di una richiesta preliminare tramite PEC (preliminareimpreseCT3@pec.gse.it) in attesa dell'attivazione del PortalTermico 3.0. Gli interventi conclusi dal 26 dicembre 2025 rientrano nel Conto Termico 3.0 con richiesta entro 90 giorni."""),

("Conto Termico 3.0 - Requisiti tecnici e documentazione",
"""Requisiti tecnici generali del Conto Termico 3.0: l'edificio deve essere esistente, con impianto di climatizzazione invernale funzionante; le tecnologie installate (pompe di calore, biomassa, solare termico, sistemi ibridi, building automation) devono rispettare i requisiti minimi di efficienza e le prescrizioni degli allegati tecnici del D.M. 7 agosto 2025 e le schede tecniche GSE. Per le opere piu' complesse - isolamento termico, trasformazione NZEB, impianti di potenza superiore a 200 kW, solare termico oltre 100 m2 - e' obbligatoria la diagnosi energetica pre-intervento e l'Attestato di Prestazione Energetica (APE) post-intervento. Documentazione tipica della pratica: relazione tecnica descrittiva con dati dell'edificio (zona climatica, gradi giorno, destinazione d'uso, categorie catastali), documentazione fotografica prima/dopo, computo metrico, fatture con bonifico ordinario con causale che riporti il riferimento al D.M. 7 agosto 2025 e i dati fiscali di richiedente ed esecutore, dichiarazione di conformita' dell'impianto (D.M. 37/2008), certificazioni energetiche degli apparecchi (etichette ecoprogettazione), asseverazione del tecnico abilitato. Per l'accesso tramite ESCO: contratto di prestazione energetica (PA) o di servizio energetico, con la ESCO che puo' acquisire la qualifica di soggetto responsabile, e convenzione tipo GSE."""),

("Conto Termico 3.0 - Confronto sintetico Conto Termico 2.0 vs 3.0",
"""Confronto sintetico: BENEFICIARI - 2.0: PA e privati; 3.0: aggiunti Terzo Settore, cooperative di abitanti, societa' in house, CER e autoconsumo collettivo, terziario privato (anche industriale) per l'efficienza energetica. INTERVENTI - 2.0: isolamento, serramenti, caldaie a condensazione, schermature, illuminazione, building automation, FER termiche; 3.0: rimosse le caldaie a condensazione, aggiunti pompe di calore add-on e sistemi bivalenti, fotovoltaico piu' accumulo e colonnine 'trainate' dalla pompa di calore, ventilazione meccanica con l'isolamento, filtrazione solare esterna. MASSIMALI - 2.0: contributi calcolati su formule con costi specifici e coefficienti di valorizzazione; 3.0: percentuali di spesa fino al 65% (100% per PA piccoli comuni e scuole/sanita'), erogazione in unica soluzione fino a 15.000 euro. PROCEDURA - 2.0: accesso diretto con richiesta entro 60 giorni dalla fine lavori; 3.0: richiesta entro 90 giorni, catalogo apparecchi prequalificati con procedura semplificata, prenotazione PA con anticipo del 50% su diagnosi/APE. DOTAZIONE - entrambi 900 milioni annui (3.0: 400 PA + 500 privati). APPROCCIO - 3.0 piu' prestazionale, orientato all'elettrificazione, all'integrazione impianto-involucro-FV e alla semplificazione digitale."""),

("Conto Termico 3.0 - Cronologia normativa e operativa",
"""Cronologia: D.Lgs. 28/2011 (art. 28: base normativa del Conto Termico) - D.M. 28 dicembre 2012 (Conto Termico 1.0) - D.M. 16 febbraio 2016 (Conto Termico 2.0) - D.Lgs. 199/2021 (obbligo di aggiornamento entro giugno 2022) - D.M. 7 agosto 2025 (Conto Termico 3.0) - approvazione Conferenza Unificata 4 agosto 2025 - pubblicazione GU n. 224 del 26 settembre 2025 - entrata in vigore 25 dicembre 2025 - approvazione Regole Applicative GSE da parte del MASE il 19 dicembre 2025 - attivazione PortalTermico 3.0 il 2 febbraio 2026 - sospensione del portale il 3 marzo 2026 per esubero di domande (circa 1,3 miliardi di euro richiesti) - riapertura il 13 aprile 2026 in accesso diretto solo per lavori conclusi - rimodulazione della dotazione con decreto direttoriale (450 milioni privati / 450 milioni PA) - pubblicazione del catalogo apparecchi prequalificati nell'aprile 2026. La misura e' sottoposta ad aggiornamento periodico con decreto del Ministro, previa intesa con la Conferenza unificata, secondo l'art. 28, comma 2, lettera g), del D.Lgs. 28/2011."""),

("Incentivi energetici italiani - Mappa completa degli strumenti",
"""Mappa degli strumenti di incentivazione energetica italiana per l'edilizia: (1) CONTO TERMICO 3.0 - contributo a fondo perduto GSE per piccoli interventi di efficienza e FER termiche (edifici esistenti), fino al 65%, non cumulabile con detrazioni; (2) ECObONUS - detrazione fiscale dal 50% al 65% per riqualificazione energetica (isolamento, serramenti, pompe di calore, solare termico, caldaie a biomassa), prorogata nel 2026 al 50% per abitazione principale e 36% per altri immobili (Legge di Bilancio); (3) BONUS RISTRUTTRAZIONI - detrazione 50% per manutenzione straordinaria; (4) BONUS FACCIATE - detrazione al 90% per il ripristino della facciata esterna (condomini, zona A o omogenea, max 60.000 euro); (5) SUPERBONUS - storico 110% per cappotto, caldaie, FV, antisismico (chiuso), residui in corso; (6) DETRAZIONE FISCALE FOTOVOLTAICO - detrazione 50% per impianti FV su edifici esistenti, cumulabile con batterie di accumulo; (7) REGIMI ELETTRICI - Ritiro Dedicato, Ritiro Semi-obbligatorio (RID semplicato), Scambio sul Posto (chiuso alle nuove adesioni), CER e autoconsumo collettivo con incentivazione tariffaria sulla quota di energia condivisa (D.Lgs. 199/2021); (8) TEE (Titoli di Efficienza Energetica o Certificati Bianchi) - obblighi di risparmio energetico sui grandi consumatori, valorizzazione dei progetti di riqualificazione (D.Lgs. 102/2014); (9) BANDI PNRR - riqualificazione degli edifici pubblici (scuole, PA centrali) a sportello; (10) DETRAZIONI FISCALI IMPRESE - iperammortamento beni strumentali 4.0, credito d'imposta energia. La scelta dello strumento ottimale dipende da: natura del soggetto (privato/impresa/PA), tipologia di intervento, tempi di erogazione richiesti, capacita' di anticipare la spesa, cumulabilita'."""),

("Comunita' energetiche e autoconsumo - Quadro normativo italiano",
"""Il quadro italiano di autoconsumo e comunita' energetiche: la direttiva RED II (UE) 2018/2001 e' stata recepita dal D.Lgs. 8 novembre 2021, n. 199 e dal D.Lgs. 210/2021. L'autoconsumatore di energia rinnovabile puo' produrre, consumare, immagazzinare e vendere l'energia autoprodotta; l'energia autoconsumata non e' soggetta agli oneri di sistema. L'autoconsumo collettivo consente la condivisione tra utenze connesse sotto la stessa cabina primaria. La Comunita' Energetica Rinnovabile (CER) e' un soggetto giuridico autonomo (cooperativa, associazione, fondazione) con l'obiettivo principale di fornire benefici ambientali, economici o sociali ai membri o al territorio, a partecipazione aperta e volontaria; possono partecipare persone fisiche, PMI, enti territoriali e autorita' locali, enti religiosi, terzo settore, enti di ricerca; la partecipazione di imprese non puo' costituire l'attivita' commerciale principale. Requisiti impianti: entrata in esercizio successiva al 15 dicembre 2021, potenza non superiore a 1 MW per impianto, quota massima del 30% di potenza da impianti preesistenti. Incentivo: tariffa incentivante (configurazione 1) o tariffa incentivante con prezzo zonale orario (configurazione 2), erogata dal GSE sulla sola quota di energia condivisa, in un unico conguaglio con la restituzione delle componenti tariffarie (ARERA Delibera 318/2020/R/eel e successivi provvedimenti). Le CER possono accedere al Conto Termico 3.0 per specifiche tipologie di intervento."""),
]

with open(OUT, "w", encoding="utf-8") as f:
    for title, text in RECIPES:
        rec = {
            "source": SRC, "license": LIC, "commercial_ok": True,
            "attribution": ATTR, "url": GU, "title": title, "text": text,
        }
        f.write(json.dumps(rec, ensure_ascii=False) + "\n")
print("scritti", len(RECIPES), "record in", OUT)
