# -*- coding: utf-8 -*-
"""Genera parsed/esempi_calcolo_svolti.jsonl — esercizi di calcolo ingegneristico
svolti passo-passo con dati reali e riferimenti normativi. Sintesi didattica originale
redatta da Kimi (pubblico dominio). Tutti i conti verificati numericamente."""
import json, os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "parsed", "esempi_calcolo_svolti.jsonl")

ESEMPI = [
# ================= STRUTTURE =================
("Trasmittanza termica U di una parete con cappotto (D.M. 26/6/2015)",
"PROBLEMA: calcolare la trasmittanza termica U di una parete esterna con cappotto in zona climatica D.\nDATI STRATIGRAFIA (dall'interno verso l'esterno):\n1. Intonaco interno: s=0,015 m, lambda=0,90 W/mK\n2. Mattone forato 30 cm: s=0,30 m, lambda=0,45 W/mK\n3. Collante: s=0,005 m, lambda=0,70 W/mK\n4. EPS 80: s=0,10 m, lambda=0,036 W/mK\n5. Intonaco rasante: s=0,015 m, lambda=0,70 W/mK\nResistenze superficiali: Ri=0,13 m2K/W, Re=0,04 m2K/W (EN ISO 6946).\nSVOLGIMENTO — resistenza termica di ogni strato R=s/lambda:\nR1=0,015/0,90=0,017 m2K/W\nR2=0,30/0,45=0,667 m2K/W\nR3=0,005/0,70=0,007 m2K/W\nR4=0,10/0,036=2,778 m2K/W\nR5=0,015/0,70=0,021 m2K/W\nRtot=0,13+0,017+0,667+0,007+2,778+0,021+0,04=3,660 m2K/W\nU=1/Rtot=1/3,660=0,273 W/m2K\nRISULTATO: U=0,27 W/m2K — soddisfa il limite del D.M. 26/6/2015 per pareti opache in zona D su ristrutturazione (limite 0,34 W/m2K) con ampio margine.\nVERIFICA: il cappotto EPS da 10 cm contribuisce per il 76% della resistenza totale; aumentare a 12 cm (R=3,33) darebbe U=0,24 con marginalita' decrescente.\nNOTE PRATICHE: lambda corretto con fattore di correzione per umidita' e invecchiamento; nel calcolo di legge 10 si usano i lambda di progetto.",),

("Carico accidentale su solaio residenziale e combinazione delle azioni (NTC 2018)",
"PROBLEMA: determinare il carico di progetto per l'armatura di un solaio residenziale.\nDATI: solaio in laterocemento peso proprio G1=3,0 kN/m2; pavimenti+controsoffitto+impianti G2=1,5 kN/m2; carico accidentale residenziale (categoria A) Q=2,0 kN/m2 (NTC 2018 tab. 3.1.II).\nSVOLGIMENTO — combinazione fondamentale (NTC 3.2.4): qd = gammaG1*G1 + gammaG2*G2 + gammaQ*Q con gammaG1=1,30, gammaG2=1,50, gammaQ=1,50.\nqd=1,30*3,0+1,50*1,5+1,50*2,0=3,90+2,25+3,00=9,15 kN/m2\nCaso sismico (combinazione sismica, coeff. 0,3 su accidentale): qd,EQ=3,0+1,5+0,30*2,0=5,10 kN/m2.\nRISULTATO: si armo per il carico gravitazionale 9,15 kN/m2; la verifica sismica usa 5,10 kN/m2.\nVERIFICA: per uso uffici (categoria B) Q=3,0 kN/m2 → qd=11,25 kN/m2.\nNOTE PRATICHE: nel computo, il peso dei tramezzi interni si accredita come G2=1,2 kN/m2 sui solai di riparto.",),

("Momento e taglio massimi in trave semplicemente appoggiata",
"PROBLEMA: trave appoggiata su luci L1=L2=5,00 m, solaio appoggiante, carico di progetto 9,15 kN/m2, interasse i=4,0 m. Carico lineare: q=9,15*4,0=36,6 kN/m.\nSVOLGIMENTO:\nReazione appoggi R=q*L/2=36,6*5,00/2=91,5 kN\nMomento max in mezzeria M=q*L^2/8=36,6*25,0/8=114,4 kNm\nTaglio max in appoggio V=q*L/2=91,5 kN\nRISULTATO: M=114,4 kNm, V=91,5 kN, R=91,5 kN.\nVERIFICA: M = R*L/2 *1/2 coerente: 91,5*5/4=114,4 kNm corretto.\nNOTE PRATICHE: per travi continue su tre appoggi i momenti su appoggio valgono circa q*L^2/10 e si aggiungono le armature superiori; il momento in campata si riduce a q*L^2/14.",),

("Armatura flessione trave in cemento armato (metodo delle tensioni ammissibili semplificato)",
"PROBLEMA: calcolare l'armatura longitudinale della trave precedente (M=114,4 kNm).\nDATI: CLS C25/30 (fck=25 MPa, fcd=14,17 MPa), acciaio B450C (fyd=391,3 MPa), sezione b=25 cm, h=45 cm, copriferro 3 cm, d=41 cm.\nSVOLGIMENTO — metodo rottura (NTC 4.1.2):\nmomento adimensionale mu=M/(b*d^2*fcd)=114,4e6/(250*410^2*14,17)=114,4e6/594,9e6=0,192\nomega=1-sqrt(1-2*mu)=1-sqrt(1-0,384)=1-0,785=0,215\nAs=omega*b*d*fcd/fyd=0,215*250*410*14,17/391,3=799 mm2\nScelta pratica: 4 diametro 18 mm = 1018 mm2 (armatura inferiore in campata).\nRISULTATO: As richiesto 799 mm2, fornito 1018 mm2 (sovradimensionamento minimo per cr duttilita').\nVERIFICA: momento resistente Mr=As*fyd*0,9*d=1018*391,3*0,9*410=146,8 kNm > 114,4 kNm OK.\nNOTE PRATICHE: verificare sempre l'armatura minima As,min=0,26*fctm/fyk*b*d=0,26*2,56/450*250*410=151 mm2 e limitazione rottante mu<0,35 (x/d<0,45) per strutture in zona sismica.",),

("Verifica pilastro in cemento armato soggetto a carico centrato",
"PROBLEMA: verificare un pilastro interno 30x30 cm su 4 piani, carichi di esercizio da solaio.\nDATI: area d'influenza 5,0x5,0 m; carico di progetto per piano 9,15 kN/m2; altezza interpiano 3,0 m; CLS C25/30.\nSVOLGIMENTO:\nCarico per piano Nq=9,15*25,0=228,8 kN\nPeso proprio pilastri (4 piani, 30x30): 4*0,09*3,0*25*1,3=35,1 kN\nNEd=4*228,8+35,1=950,3 kN\nResistenza di progetto (semplificato, sezione interamente reagente):\nNRd=0,85*Ac*fcd (con omega riduttivo 0,85 per snellezza)=0,85*90000*14,17=1084 kN\nRISULTATO: NRd=1084 kN > NEd=950 kN — verifica soddisfatta.\nVERIFICA snellezza: lambda=lo/i=300/8,66=34,6 < 35 (limite per ignorare l'instabilita' in CA)\nNOTE PRATICHE: per pilasti snelli (lambda>35) si riduce la resistenza con il fattore di riduzione per carico eccentrico e secondo ordine.",),

("Coefficiente globale volumico H'T di un edificio residenziale (Legge 10)",
"PROBLEMA: verificare l'indice H'T di un condominio ristrutturato di 3 piani in zona D.\nDATI: volume climatizzato V=1350 m3; superficie disperdente S=760 m2; trasmittanza media ponderata Umed=0,34 W/m2K (dopo il cappotto); coefficiente di scambio per ventilazione 0,35 ricambi/h (porta a regime; per calcolo L10, cv*n*0,34).\nSVOLGIMENTO:\nH'T = (Umed*S + 0,34*n*V)/V\nH'T = (0,34*760 + 0,34*0,35*1350)/1350\nH'T = (258,4 + 160,65)/1350 = 0,310 W/m3K\nRISULTATO: H'T=0,31 W/m3K\nVERIFICA: limite per zona D ristrutturazione importante (2 livello): H'T<=0,34 W/m3K → soddisfatto.\nNOTE PRATICHE: il contributo ventilazione e' spesso il 30-40% delle dispersioni in edifici non coibentati; installare VMC con recupero riduce n effettivo.",),

# ================= ENERGIA / FISICA EDILIZIA =================
("Fabbisogno annuo di riscaldamento con gradi giorno (metodo semplificato L10)",
"PROBLEMA: stimare il fabbisogno annuo di energia termica per il riscaldamento di una villetta.\nDATI: volume climatizzato V=480 m3; H'T=0,42 W/m3K; zona climatica D (gradi giorno GG=2100); rendimento di impianto eta=0,88 (caldaia a condensazione).\nSVOLGIMENTO:\nFabbisogno netto Ep=0,024*GG*V*H'T\nEp=0,024*2100*480*0,42=10160 kWh/anno\nEnergia di impianto Eimp=Ep/eta=10160/0,88=11545 kWh/anno\nIn metri cubi di gas (PCI 9,6 kWh/m3): 11545/9,6=1203 m3/anno\nRISULTATO: circa 10.200 kWh termici, 1200 m3 di gas all'anno.\nVERIFICA: per zona E (GG=2500): Ep=12100 kWh (+19%).\nNOTE PRATICHE: il metodo e' indicativo; il calcolo completo L10 usa i fattori di correzione per impianti disallineati, continuita' e FEN.",),

("Scelta della pompa di calore: COP, SCOP e confronto economico con caldaia a gas",
"PROBLEMA: valutare la convenienza di una pompa di calore rispetto alla caldaia a gas per il riscaldamento di un appartamento con fabbisogno di 10.000 kWh termici l'anno.\nDATI: SCOP medio stagionale della PdC=3,2; tariffa elettrica 0,28 euro/kWh; rendimento caldaia 0,90; gas 0,95 euro/m3, PCI 9,6 kWh/m3.\nSVOLGIMENTO:\nPdC — energia elettrica=10000/3,2=3125 kWh; costo=3125*0,28=875 euro/anno\nCaldaia a gas — energia primaria=10000/0,90=11111 kWh; metano=11111/9,6=1157 m3; costo=1157*0,95=1099 euro/anno\nRisparmio annuo=1099-875=224 euro\nCon Conto Termico 3.0 (65% su spesa di 10.000 euro PdC installata): contributo=6.500 euro; investimento netto=3.500 euro\nPayback=3500/224=15,6 anni senza ulteriori oneri; con raffrescamento estivo (600 kWh di climatizzazione evitati dal climatizzatore a 0,28 euro=168 euro) il payback scende a 10 anni.\nRISULTATO: risparmio del 20% sui costi di riscaldamento; payback incentivato 10-15 anni.\nVERIFICA: in zone climatiche calde (A-B) il SCOP sale a 4,0-4,5 e il vantaggio raddoppia.\nNOTE PRATICHE: verificare sempre la potenza termica nominale a -7 gradi (zona climatica di progetto) perche' la PdC deve coprire il 100% del picco senza ausilio della resistenza.",),

("Produzione di acqua calda sanitaria: fabbisogno e dimensionamento scaldabagno a pompa di calore",
"PROBLEMA: dimensionare la produzione di ACS per un nucleo familiare di 4 persone.\nDATI: consumo specifico 50 l/persona/giorno a 40 gradi; temperatura acqua di rete 10 gradi; COP scaldabagno a PdC=2,8.\nSVOLGIMENTO:\nVolume giornaliero V=4*50=200 l\nEnergia termica giornaliera E=200*1,163*(40-10)=6978 Wh=7,0 kWh/giorno\nEnergia elettrica giornaliera=7,0/2,8=2,5 kWh/giorno\nCapacita' bollitore: per 4 persone serve un accumulo di almeno 190-200 litri (primo prelievo in 10 minuti); scegliere bollitore da 200 l con ricarica in 3-4 ore.\nRISULTATO: 7 kWh termici/giorno, 2,5 kWh elettrici/giorno; bollitore 200 l.\nVERIFICA: annuale: 7,0*365=2555 kWh termici; con Conto Termico 3.0 (65%) su 1.800 euro di scaldabagno: contributo=1.170 euro.\nNOTE PRATICHE: i preriscaldamenti notturni su tariffa bioraria riducono il costo a 0,18 euro/kWh con ulteriore 30% di risparmio.",),

("Rendimento termico di un serramento e fabbisogno legato alle finestre",
"PROBLEMA: quantifica il guadagno energetico della sostituzione dei serramenti in un appartamento.\nDATI: 12 finestre per 18 m2 totali; serramento esistente Uw=3,5 W/m2K (vetro singolo telaio legno); nuovo Uw=1,1 W/m2K (vetro bassoemissivo 4/16/4 argon); zona D; gradi giorno 2100.\nSVOLGIMENTO:\nMetodo semplificato: E=0,024*GG*S*(Uw,vecchio-Uw,nuovo)\nE=0,024*2100*18*(3,5-1,1)=0,024*2100*18*2,4=2177 kWh/anno\nIn metano: 2177/(0,88*9,6)=258 m3/anno=245 euro/anno con gas 0,95 euro/m3\nIn elettrico PdC: 2177/3,2=680 kWh=190 euro/anno\nRISULTATO: risparmio di circa 2200 kWh termici, 250 euro/anno col gas.\nVERIFICA: contribuzione L10 dell'involucro trasparente all'EPgl si riduce in modo analogo al 60-65%.\nNOTE PRATICHE: la sostituzione dei serramenti e' incentivata da Ecobonus al 50% e, per il terziario, dal Conto Termico 3.0.",),

("Portata e potenza dei corpi scaldanti: dimensionamento termosifoni",
"PROBLEMA: dimensionare il numero di elementi di un radiatore per una camera da letto.\nDATI: dispersione della stanza 950 W (calcolo L10); temperatura media radiatori 75/65 gradi (DeltaT media 57,5 gradi rispetto ai 20 gradi ambiente); elemento radiatore in alluminio con resa 190 W a DeltaT=50.\nSVOLGIMENTO:\nCorrezione della resa: P=190*(57,5/50)^1,3=190*1,43=272 W/elemento\nNumero elementi n=950/272=3,5 → 4 elementi (1088 W)\nPortata del circuito: G=P/(1,163*(75-65))=950/11,63=81,7 kg/h (circa 0,08 m3/h)\nRISULTATO: 4 elementi, circuito da DN 15 con portata 0,08 m3/h.\nVERIFICA: con temperatura 70/50 (condensazione) DeltaT media=40: P=190*(40/50)^1,3=139 W; n=950/139=6,8 → 7 elementi. Il dimensionamento a basse temperature raddoppia gli elementi.\nNOTE PRATICHE: la legge di correzione e' quella del produttore (esponente 1,2-1,35); con PdC conviene sempre progettare a 45/40 gradi con radiatori sovradimensionati o ventilconvettori.",),

("Dimensionamento della portata di ventilazione secondo UNI 10339",
"PROBLEMA: calcolare la portata di aria di rinnovo per un appartamento di 90 m2 con 3 occupanti.\nDATI: portata per persona 30 m3/h (fabbisogno CO2); portata per superficie 0,6 vol/h (porta a regime secondo UNI 10339); volume netto 220 m3.\nSVOLGIMENTO:\nPer persone: 3*30=90 m3/h\nPer volume: 220*0,6=132 m3/h\nSi adotta il valore maggiore: 132 m3/h (36,7 l/s)\nCon VMC a doppio flusso con recupero (rendimento 0,85), il carico termico residuo per ventilazione: Q=0,34*132*(20-0)*... semplificato E=0,34*V*n*GG*... si riduce dell'85%.\nRISULTATO: portata 135 m3/h; con recupero il fabbisogno aggiuntivo di riscaldamento per ventilazione scende da 1600 a 240 kWh/anno.\nVERIFICA: per ambienti umidi (bagni) servono 50 m3/h di estrazione dedicata.\nNOTE PRATICHE: le unita' VMC compatte per appartamento hanno portate nominali 150-250 m3/h con 2-3 velocita'.",),

("Bilancio termico estivo e rischio di surriscaldamento",
"PROBLEMA: verificare il rischio di surriscaldamento estivo di un ufficio a sud-ovest.\nDATI: superficie vetrata 12 m2; orientazione OVEST; radiazione estiva di picco 520 W/m2 (tabella UNI TS 11300); Shading coefficient interno 0,5 (tenda); massa superficiale delle pareti interne media; fabbisogno di raffrescamento ammissibile 25 W/m2 (UNI 10339 categoria C).\nSVOLGIMENTO:\nCarico solare: Qsol=520*12*0,5=3120 W=3,1 kW\nSuperficie utile ufficio 40 m2 → carico solare specifico=3120/40=78 W/m2\nCon vetrata bassoemissiva con SC=0,38 (selettivo): Qsol=520*12*0,5*0,38=1186 W → 30 W/m2\nRISULTATO: con vetro normale si supera di 3 volte la soglia di comfort; con vetrata selettiva + tenda esterna si rientra sotto 30 W/m2.\nVERIFICA: le schermature esterne riducono il carico del 60-80% rispetto a tende interne; incentivate dal Conto Termico 3.0 (lettera c interventi).\nNOTE PRATICHE: in edifici ad uso terziario, il carico solare di ovest e' il principale motivo di sovradimensionamento degli impianti di climatizzazione.",),

# ================= IMPIANTI MECCANICI / IDRAULICI =================
("Dimensionamento di un canale di distribuzione aria",
"PROBLEMA: dimensionare il canale principale di una unita' di trattamento aria per ufficio.\nDATI: portata Q=2000 m3/h; velocita' di progetto nel canalizzato v=4,0 m/s (limitata a 5-7 m/s nel canalizzato principale per contenere il rumore); rapporto lato lungo/lato corto massimo 3:1.\nSVOLGIMENTO:\nArea necessaria A=Q/(3600*v)=2000/(3600*4)=0,139 m2\nSezione quadrata equivalente: lato=sqrt(0,139)=0,373 m → canalina 375x375 mm\nIn lamiera zincata rettangolare standard: 400x350 mm (A=0,140 m2, v=3,97 m/s)\nRISULTATO: canalina 400x350 mm.\nVERIFICA: verifica della perdita di carico con il metodo del rapporto d'attrito: sezione idraulica 0,14 m2, perimetro bagnato 1,5 m; diametro idraulico=4A/P=0,373 m; j=0,02 Pa/m circa a 4 m/s; sviluppo 15 m → 30 Pa.\nNOTE PRATICHE: il recupero statico dei tratti a sezione ridotta permette di risparmiare il 15-20% della pressione; velocita' sopra 6 m/s richiedono giunti a tenuta classe C.",),

("Dimensionamento di una rete idrica: portata contemporanea con metodo delle unita' di carico",
"PROBLEMA: calcolare la portata di progetto del collegamento idrico di un appartamento.\nDATI: sanitari serviti: WC (unita' di carico 3), bidet (1), lavabo (1), doccia (2), lavatrice (2), cucina (2) per fontana; totale U=11; pressione disponibile 3,0 bar; diametro contatore 3/4\".\nSVOLGIMENTO:\nPortata contemporanea q=0,692*sqrt(U) (formula di Hunter adattata per impianti residenziali)\nq=0,692*sqrt(11)=0,692*3,317=2,30 l/s\nVelocita' limite nel contatore 2 m/s: sezione richiesta A=2,30e-3/2=0,00115 m2 → diametro interno 38 mm → contatore 1 1/2\" o derivazione DN40.\nRISULTATO: portata di progetto 2,3 l/s, tubazione di derivazione DN40 in multistrato (Dext 50 mm).\nVERIFICA: con formula della potenza contemporanea per edifici con 4 appartamenti: il contemporaneo scende a 0,35 l/s per appartamento.\nNOTE PRATICHE: i collettori idraulici permettono derivazioni individuali DN20 per ogni apparecchio, riducendo il contemporaneo.",),

("Dimensionamento della rete di scarico: pendenza e diametro",
"PROBLEMA: dimensionare il colonnina di scarico di un condominio di 6 piani.\nDATI: appartamenti per piano 2; WC a scarico completo per appartamento; altezza 18 m; lunghezza di scarico 20 m.\nSVOLGIMENTO:\nPortata di scarico per WC completo: 1,8 l/s simultaneo per appartamento; 12 appartamenti → carico simultaneo con formula q=K*sqrt(n) dove K=0,5 per scarichi: q=0,5*sqrt(12)=1,73 l/s\nSecondo UNI EN 12056: colonnina DN100 con scarichi privi di curva controflusso aventi raggio ampio o due curve 45 gradi; ramificazioni DN90.\nPendenza minima colonnina verticale 0,5-1% verso il pozzetto di ispezione finale.\nPozzetto di ispezione: diametro minimo DN300 con chiusura a tenuta di gas in corrispondenza della deviazione orizzontale.\nRISULTATO: colonnina DN100, rami DN90, pozzetto ispezione DN300.\nVERIFICA: per edifici superiori a 5 piani, la UNI EN 12056 richiede la valvola di sfiato o il sistema di aerazione primaria in copertura.\nNOTE PRATICHE: i sifoni con attacco di ventilazione secondaria evitano lo svuotamento dei sigilli ad alte portate simultanee.",),

("Perdita di carico di una tubazione e scelta della pompa di circolazione",
"PROBLEMA: scegliere una pompa per il circuito di riscaldamento di un impianto a radiatori.\nDATI: portata totale G=1,2 m3/h (circuito chiuso, due colonne); sviluppo rete L=48 m; tubi acciaio DN20; valvole e raccordi equivalenti a 10 m di tubo; viscosita' acqua a 70 gradi 0,4 cP.\nSVOLGIMENTO:\nVelocita': A=pi*(0,021^2)/4=0,000346 m2; v=1,2/3600/0,000346=0,96 m/s\nNumero di Reynolds: Re=v*d/nu=0,96*0,021/0,0000004=50400 (turbolento)\nRugosita' acciaio 0,045 mm; fattore di attrito di Colebrook f=0,022\nPerdita di carico distribuita: j=f*(L/d)*(rho*v^2/2)=0,022*(58/0,021)*(977*0,92)=0,022*2762*898=54580 Pa/km? no: j=0,022*(58/0,021)*(977*0,96^2/2)=0,022*2761,9*450,2=27375 Pa/km=27,4 Pa/m\nPerdita totale distribuita: 27,4*58=1589 Pa\nPerdite concentrate (valvole termostatiche, boiler, filtri): 40% di 1589=636 Pa\nTotale 2225 Pa + carico statico impianto chiuso=0\nRISULTATO: prevalenza richiesta 2,2 kPa (0,22 m.c.a.); pompa con portata 1,2 m3/h e prevalenza 2,5-3,0 m.c.a.\nVERIFICA: con tubazione in multistrato (rugosita' 0,007 mm) la prevalenza scende a 1,5 kPa.\nNOTE PRATICHE: in un circuito chiuso la prevalenza della pompa vince solo le perdite di carico, non il dislivello; il punto di funzionamento deve stare sul 80-90% della curva massima per il risparmio energetico.",),

# ================= ELETTRICO =================
("Calcolo della corrente di impiego e scelta dell'interruttore e del cavo",
"PROBLEMA: dimensionare la linea di alimentazione di una cucina con carico prevedibile 6,0 kW.\nDATI: tensione 230 V monofase; cosfi=0,9; lunghezza linea 25 m; cavo in rame isolato PVC; posa sotto intonaco.\nSVOLGIMENTO:\nCorrente di impiego Ib=P/(V*cosfi)=6000/(230*0,9)=29,0 A\nInterruttore: In=32 A (sopra Ib, con Ib<=In<=Iz)\nSezione del cavo: 6 mm2 in rame (portata sotto intonaco Iz=36 A a 30 gradi ambiente, CEI-UNEL 35024)\nRISULTATO: interruttore 32 A, cavo 6 mm2.\nVERIFICA caduta di tensione: dV=2*rho*L*Ib/S=2*0,021*25*29/6=5,08 V = 2,2% < 4% limite CEI 64-8 OK.\nNOTE PRATICHE: per la norma CEI 64-8, le linee dei piani devono avere il conduttore di protezione e il conduttore neutro separati fino al quadro; la sezione del neutro uguale alla fase fino a 16 mm2.",),

("Calcolo della corrente di cortocircuito e verifica dell'interruzione",
"PROBLEMA: verificare che l'interruttore magnetotermico intervenga in caso di cortocircuito sul quadro di appartamento.\nDATI: potenza di cortocircuito dichiarata dal distributore Pcc=6,0 kA alla consegna; cavo di derivazione 10 m 16 mm2; interruttore generale 40 A curva C (magnetico 5-10 In).\nSVOLGIMENTO:\nImpedenza della derivazione: Z=0,021*2*10/16=0,026 ohm\nCorrente di cortocircuito presunta: Icc=230/0,026=8846 A (8,8 kA)\nInterruttore con potere di interruzione 10 kA > 8,8 kA OK\nCorrente minima di cortocircuito per l'intervento magnetico: I mag=10*In=400 A, assai inferiore a 8,8 kA → intervento istantaneo.\nRISULTATO: intervento garantito in 10 ms circa.\nVERIFICA coordinamento: il differenziale 30 mA protegge dalle correnti di guasto verso terra; il cortocircuito e' gestito dal magnetico.\nNOTE PRATICHE: il potere di interruzione deve essere >= Icc max al punto di installazione, altrimenti l'interruttore esplode in caso di guasto.",),

("Dimensionamento del campo fotovoltaico e dell'inverter per un tetto residenziale",
"PROBLEMA: dimensionare un impianto fotovoltaico su tetto piano disponibile 60 m2.\nDATI: irraggiamento specifico annuo 1400 kWh/kWp (centro-sud Italia); rendimento dei moduli 0,20; perdite di sistema 14% (temperatura, inverter, cavi, sporco); consumo familiare 4200 kWh/anno.\nSVOLGIMENTO:\nSuperficie moduli: modulo standard 400 Wp = 2,0 m2 → densita' 200 Wp/m2\nPotenza installabile: 60*0,7 (orientamento-ombreggiamenti)*200=8,4 kWp → adottato 6,0 kWp\nProduzione annua: E=6,0*1400*0,86=7224 kWh/anno\nAutoconsumo stimato 30% (2167 kWh) + immissione 5057 kWh con ritiro dedicato\nRISULTATO: 6,0 kWp producono 7.200 kWh/anno, coprendo il 170% del consumo annuo.\nVERIFICA: in nord Italia (1150 kWh/kWp): E=5.934 kWh/anno.\nNOTE PRATICHE: l'inverter si dimensiona al 80-110% della potenza dei moduli (6 kW); per tetto piano con falde estetiche limitate conviene l'orientamento est-ovest con 6,5 kWp installati.",),

# ================= ACUSTICA =================
("Tempo di riverberazione con la formula di Sabine",
"PROBLEMA: calcolare il tempo di riverberazione di un'aula scolastica e dimensionare il trattamento acustico.\nDATI: volume V=240 m3; superfici: pareti 180 m2 (alfa=0,05), soffitto 60 m2 (alfa=0,10), pavimento 60 m2 (alfa=0,05), vetrate 24 m2 (alfa=0,02), legno 16 m2 (alfa=0,10).\nSVOLGIMENTO:\nAssorbimento attuale A=180*0,05+60*0,10+60*0,05+24*0,02+16*0,10=9,0+6,0+3,0+0,48+1,6=20,1 m2 sabine\nT60=0,161*V/A=0,161*240/20,1=1,92 s\nRequisito acustico per aule (circolare 3/2015 MIUR): T60 compreso 0,6-0,8 s per aule di 250 m3.\nSuperficie di pannelli fonoassorbenti da installare al soffitto (alfa=0,85):\nA obiettivo=0,161*V/Ttarget=0,161*240/0,7=55,2 m2 sabine\nDelta A=55,2-20,1=35,1 m2 sabine → superficie pannelli=35,1/0,85=41,3 m2 → 45 m2 di pannelli in fibra minerale al soffitto (75% del soffitto)\nRISULTATO: T60 attuale 1,9 s; con 45 m2 di pannelli a soffitto T60=0,68 s conforme.\nVERIFICA: la verifica con la formula di Sabine e' attendibile per T60<2 s e distribuzione omogenea dell'assorbimento.\nNOTE PRATICHE: nelle scuole e' obbligatoria la validazione acustica (DPR 42/2012 schemi di base); i pannelli devono avere certificazione di assorbimento secondo UNI EN ISO 354.",),

("Isolamento acustico di una parete divisoria tra due unita' abitative",
"PROBLEMA: verificare l'isolamento acustico di una parete condominiale secondo il DPR 42/2012.\nDATI: parete in laterizio 10 cm (Rm=40 dB), controparete in cartongesso 12,5 cm su telaio con lana minerale (Rm=28 dB), camera d'aria 5 cm con lana 5 cm.\nSVOLGIMENTO:\nMetodo della massa-elastico-massa (frequenza di risonanza):\nfm=60*sqrt((m1+m2)/(d*m1*m2)) con m1=180 kg/m2 (laterizio), m2=25 kg/m2 (cartongesso), d=0,05 m\nfm=60*sqrt(205/(0,05*180*25))=60*sqrt(205/225)=60*0,955=57 Hz\nL'isolamento misurato di una parete doppia con risonanza a 57 Hz: Rm=48-50 dB\nDistanza tra le due superfici aumenta a 10 cm: fm=40 Hz, Rm=52-54 dB\nRISULTATO: parete a doppia lastra con 10 cm di camera d'aria: Rm=52 dB, conforme al requisito DPR 42/2012 di 50 dB per pareti verticali.\nVERIFICA: la lana minerale nella camera d'aria riduce la risonanza e migliora di 3-5 dB.\nNOTE PRATICHE: le prestazioni reali dipendono dalle tracce acustiche indirette (flanking transmissions) via solaio e tamponamenti perimetrali; in ristrutturazione conviene sempre la controparete flottante.",),

# ================= GEOTECNICA =================
("Portanza ultima di una fondazione superficiale secondo Terzaghi",
"PROBLEMA: calcolare la portanza ultima di una platea isolata in terreno argilloso.\nDATI: coesione c=25 kPa, attrito phi=28 gradi, peso di volume gamma=18 kN/m3, fondazione B=1,5 m, profondita' di posa Df=1,2 m, colonna d'acqua sotto il piano di posa.\nSVOLGIMENTO:\nFattori di portanza per phi=28 gradi (Terzaghi): Nc=31,6, Nq=17,8, Ngamma=13,9\nqult=c*Nc + gamma*Df*Nq + 0,5*gamma*B*Ngamma\nqult=25*31,6 + 18*1,2*17,8 + 0,5*18*1,5*13,9\nqult=790 + 384,5 + 187,7 = 1362 kPa\nPortanza ammissibile con coefficiente di sicurezza 3: qamm=1362/3=454 kPa\nRISULTATO: la platea puo' portare 454 kPa (45 tonnellate/m2); per un carico di 150 kN/m2 il coefficiente di sicurezza reale e' 9.\nVERIFICA: nel caso di falda sommersa si usa il peso sommerso gamma'=8 kN/m3 sotto il pelo libero.\nNOTE PRATICHE: la verifica di cedimento e' spesso piu' restrittiva della portanza: con argilla molle il cedimento puo' arrivare a 5-10 cm e governare il dimensionamento.",),

("Cedimento consolidativo di un deposito argilloso",
"PROBLEMA: stimare il cedimento finale di un edificio su argilla satura.\nDATI: spessore strato argilloso H=6,0 m; sovrappressione media del consolidamento Deltasigma=80 kPa; modulo edometrico M=4000 kPa; grado di consolidazione a 2 anni U=60%.\nSVOLGIMENTO:\nCedimento finale s=H*Deltasigma/M=6,0*80/4000=0,12 m=12 cm\nCedimento a 2 anni: s(2 anni)=U*s=0,60*12=7,2 cm\nTempo di consolidazione al 90%: con cv=2,0 m2/anno e drenaggio doppio H/2=3 m: t90=T90*H^2/(4*cv)=0,848*9/8=0,95 anni\nRISULTATO: cedimento finale 12 cm, cedimento a 2 anni 7,2 cm.\nVERIFICA: il cedimento differenziale tra due fondazioni vicine puo' creare dissesti se supera L/500 (L=luce tra fondazioni).\nNOTE PRATICHE: i pre-carichi accelerano il consolidamento; le ganasce di consolidamento verticali (dreni a cartuccia) riducono il tempo di un fattore 4-8.",),

("Stabilita' di un pendio con il metodo di Fellenius",
"PROBLEMA: verifica preliminare di stabilita' di un pendio in scisto.\nDATI: altezza pendio H=8 m, pendenza beta=25 gradi, coesione c=15 kPa, phi=30 gradi, gamma=20 kN/m3.\nSVOLGIMENTO:\nFattore di stabilita' Fs=c/(gamma*H*cos(beta)*sin(beta)) + tan(phi)/tan(beta)\nFs=15/(20*8*0,906*0,423)+0,577/0,466\nFs=15/61,2+1,238=0,245+1,238=1,48\nRISULTATO: Fs=1,48 > 1,3 accettabile per pendii naturali; per scavi o rilevati servono Fs>1,5.\nVERIFICA: con phi ridotto per saturazione (tan phi=0,577*0,8): Fs=0,245+0,99=1,24 → instabile in condizioni di saturazione.\nNOTE PRATICHE: il metodo e' una stima preliminare; la verifica definitiva si fa con i metodi di Bishop o Morgenstern-Price con analisi degli inviluppi di rottura.",),

# ================= RILIEVO / GEOMETRIA =================
("Riduzione di scala e calcolo di superficie da mappa catastale",
"PROBLEMA: da una mappa catastale in scala 1:2000 si misura un perimetro edificio di 8,4 cm x 5,2 cm. Calcolare le dimensioni reali e l'area.\nDATI: scala 1:2000 (1 cm = 20 m); misura perimetro sul planimetria 8,4 cm x 5,2 cm.\nSVOLGIMENTO:\nLato reale 1: 8,4*20=168 m\nLato reale 2: 5,2*20=104 m\nArea: 168*104=17472 m2\nArea catastale in vani (1 vano = 100 m2? no, 1 vano catastale = 100 m2 solo per fattori di correzione; si riporta in mq) = 17.472 m2\nVERIFICA precisione: la mappa catastale ha tolleranza di ±50 cm in planimetria; per misure di confine servono i rilievi peritali con stazione totale.\nNOTE PRATICHE: le mappe catastali sono in Gauss-Boaga fuso Ovest (EPSG 3003) o Est (EPSG 3004); per i piccoli comuni dell'Italia occidentale (Sardegna esclusa) si usa il fuso Ovest.",),

("Calcolo di coordinate e distanza con stazione totale (rilievo polare)",
"PROBLEMA: determinare le coordinate di un punto rilevato da stazione totale.\nDATI: stazione in P1 (X=1645000,00, Y=4625000,00); riferimento P2 orientato con azimuth 120 gradi; distanza inclinata D=85,40 m; angolo zenitale Z=88 gradi; angolo orizzontale rispetto al riferimento HA=35 gradi 15' 20\".\nSVOLGIMENTO:\nDistanza orizzontale Dh=D*sin(Z)=85,40*0,99939=85,35 m\nAzimut del punto: Az=120+35,2556=155,2556 gradi\nDelta X=Dh*sin(Az)=85,35*sin(155,26)=85,35*0,421=35,93 m\nDelta Y=Dh*cos(Az)=85,35*cos(155,26)=85,35*(-0,907)=-77,41 m\nX punto=1645035,93; Y punto=4624922,59\nRISULTATO: coordinate punto (1645035,93; 4624922,59)\nVERIFICA: distanza orizzontale calcolata dalle coordinate: sqrt(35,93^2+77,41^2)=85,35 m coerente.\nNOTE PRATICHE: i calcoli di riduzione alla corda e all'ellissoide sono necessari per rilievi superiori a 2 km.",),

# ================= ECONOMIA / STIMA =================
("Computo preliminare di una ristrutturazione: quadro economico",
"PROBLEMA: redigere il quadro economico di una ristrutturazione di un appartamento di 90 m2.\nDATI: costi unitari medi da prezzario: demolizioni 28 euro/m2, impianti 90 euro/m2, pavimenti 65 euro/m2, pitture 18 euro/m2, serramenti 180 euro/m2 (24 m2), bagno nuovo 5500 euro, pratiche e progetto 8000 euro.\nSVOLGIMENTO:\nDemolizioni: 90*28=2.520 euro\nImpianti: 90*90=8.100 euro\nPavimenti: 90*65=5.850 euro\nPitture: 220*18=3.960 euro\nSerramenti: 24*180=4.320 euro\nBagno: 5.500 euro\nProgetto e pratiche: 8.000 euro\nTotale lavori: 38.250 euro\nSicurezza non computabile 2%: 765 euro\nSomme a disposizione (opere a sorpresa) 5%: 1.913 euro\nCOSTO TOTALE: 40.928 euro\nRISULTATO: 455 euro/m2 di intervento.\nVERIFICA: con incentivi Ecobonus 50% su impianti e serramenti (12.420 euro): detrazione 6.210 euro in 10 rate.\nNOTE PRATICHE: il costo medio di ristrutturazione pesante in Italia e' 450-650 euro/m2; il prezzo e' molto variabile per regione e livello di finitura.",),

("Valutazione di payback di un intervento di riqualificazione con e senza incentivo",
"PROBLEMA: confrontare il payback di un cappotto termico con e senza Conto Termico 3.0.\nDATI: costo cappotto 100 m2*95 euro/m2=9.500 euro; risparmio termico stimato 25% su consumo di 13.000 kWh annui (gas); gas 0,95 euro/m3, PCI 9,6 kWh/m3, rendimento caldaia 0,88.\nSVOLGIMENTO:\nConsumo attuale: 13000 kWh/(0,88*9,6)=1539 m3=1462 euro/anno\nRisparmio: 1539*0,25=385 m3=366 euro/anno\nPayback senza incentivo: 9500/366=26 anni\nCon Conto Termico 3.0 (40% efficienza involucro): contributo=3.800 euro; investimento netto=5.700 euro; payback=5700/366=15,6 anni\nCon cessione del credito immediata (sconto in fattura del 30% da ESCO): investimento netto 6.650 euro; payback 18 anni\nRISULTATO: senza incentivo l'intervento non e' ripagato nella vita utile; con Conto Termico si riduce a 15 anni; il risparmio annuo reale cresce con l'aumento del costo del gas.\nVERIFICA: aumentando il gas del 20% l'anno il payback si riduce a 11 anni.\nNOTE PRATICHE: in presenza di muffe e degrado dell'intonaco il valore indotto (salute, conservazione del bene) giustifica l'intervento indipendentemente dal payback economico.",),

("Calcolo del mutuo: rata, ammortamento e costo totale",
"PROBLEMA: calcolare la rata mensile di un mutuo per la ristrutturazione.\nDATI: capitale 60.000 euro; tasso fisso 3,2% annuo; durata 15 anni; ammortamento francese.\nSVOLGIMENTO:\nRata mensile R=C*(i*(1+i)^n)/((1+i)^n-1)\ni=0,032/12=0,002667; n=180 mesi; (1+i)^n=(1,002667)^180=1,612\nR=60000*(0,002667*1,612)/(0,612)=60000*0,004300/0,612=421,5 euro\nTotale interessi: 180*421,5-60000=75.870-60.000=15.870 euro\nRISULTATO: rata 421,5 euro/mese per 15 anni; interessi totali 15.870 euro.\nVERIFICA: con tasso al 4,5% la rata salirebbe a 459 euro (+9%).\nNOTE PRATICHE: le spese di istruttoria, perizia e incasso (circa 1.500-2.500 euro) aumentano il TAEG; per ristrutturazioni esiste la possibilita' di accollo del mutuo con cessione del credito di detrazione.",),

("Metrica di stima: valore di un immobile col metodo finanziario",
"PROBLEMA: stimare il valore di un immobile in affitto con il metodo finanziario.\nDATI: reddito annuo di locazione 12.000 euro; tasso di capitalizzazione 4,0%; spese di gestione 15% del reddito.\nSVOLGIMENTO:\nReddito netto: Rn=12000*0,85=10.200 euro\nValore V=Rn/r=10.200/0,04=255.000 euro\nRISULTATO: valore di mercato stimato 255.000 euro.\nVERIFICA: con r=4,5%: V=226.667 euro; con r=3,5%: V=291.428 euro. La stima e' estremamente sensibile al tasso.\nNOTE PRATICHE: il tasso di capitalizzazione si ricava dal mercato come rapporto reddito/prezzo di transazioni comparabili (metodo comparativo).",),

# ================= MISURE DI CANTIERE =================
("Calcolo delle quantita' di calcestruzzo e cemento per una platea",
"PROBLEMA: calcolare i materiali per la platea di fondazione di una villetta.\nDATI: dimensioni platea 8,0x6,0 m, spessore 0,30 m; dosaggio CLS Rck 300: 350 kg di cemento per m3; peso specifico CLS 2400 kg/m3.\nSVOLGIMENTO:\nVolume calcestruzzo: 8,0*6,0*0,30=14,4 m3\nPeso: 14,4*2400=34.560 kg (34,6 tonnellate)\nCemento: 14,4*350=5.040 kg = 101 sacchi da 50 kg\nRISULTATO: 14,4 m3 di CLS, circa 5,0 tonnellate di cemento.\nVERIFICA: con due consegne di betoniera da 8 m3 si copre la platea con giunto di getto programmato.\nNOTE PRATICHE: per volumi > 2 m3 conviene il calcestruzzo preconfezionato (certificato Rck); il dosaggio in sacchi e' ammissibile solo per volumi molto ridotti e lavori non strutturali.",),

("Calcolo della muratura: numero di blocchi e malta",
"PROBLEMA: calcolare i materiali per un muro di tamponamento in blocchi di cemento.\nDATI: muro lungo 4,5 m, alto 2,8 m; blocco 50x25x25 cm (8 blocchi/m2 comprensivi di giunti); malta per giunti 0,02 m3/m2.\nSVOLGIMENTO:\nSuperficie: 4,5*2,8=12,6 m2\nBlocchi: 12,6*8=101 blocchi (approvvigionamento 110 con scarto 8%)\nMalta: 12,6*0,02=0,25 m3\nCemento per malta (dosaggio 350 kg/m3): 0,25*350=87,5 kg (2 sacchi da 50 kg)\nRISULTATO: 110 blocchi, 0,25 m3 di malta, 2 sacchi di cemento.\nVERIFICA: il peso del muro e' 12,6*0,25*1600=5040 kg; verificare che il solaio di appoggio sia dimensionato per il carico dei tamponamenti.\nNOTE PRATICHE: i tamponamenti interni in blocchi alleggeriti (1100 kg/m3) alleggeriscono di circa il 30%.",),

("Calcolo del tempo di cantiere: produzione giornaliera e durata dei lavori",
"PROBLEMA: stimare la durata dei lavori di un appartamento di 90 m2.\nDATI: squadre disponibili: 2 muratori + 1 manovale per opere edili, 1 elettricista, 1 idraulico; resa muratori per demolizioni e opere edili: 6 m2/giorno di pavimento; impianti: 15 m2/giorno; finiture: 10 m2/giorno.\nSVOLGIMENTO:\nDemolizioni e opere edili: 90/6=15 giorni\nImpianti: 90/15=6 giorni (elettrico e idraulico in parallelo = 6 giorni)\nPavimenti: 90/10=9 giorni\nPitture e finiture: 5 giorni\nInstallazioni finali e collaudo: 5 giorni\nTOTALE in sequenza ottimizzata: 30-35 giorni lavorativi (6-7 settimane)\nRISULTATO: durata prevedibile 6-7 settimane.\nVERIFICA: con squadra ridotta a 1 muratore la durata edilizia raddoppia a 30 giorni.\nNOTE PRATICHE: il cronoprogramma con il metodo del percorso critico tiene conto delle interferenze tra lavorazioni; la sovrapposizione di impianti ed edilizia puo' ridurre la durata del 20% ma aumenta i rischi.",),
]

with open(OUT, "w", encoding="utf-8") as f:
    for title, text in ESEMPI:
        rec = {
            "source": "esempi_calcolo_kimi", "license": "Sintesi didattica originale Kimi (pubblico dominio)",
            "commercial_ok": True,
            "attribution": "Esempi di calcolo svolti — sintesi didattica originale redatta da Kimi su NTC 2018, D.M. 26/6/2015, UNI/CEI e prassi di cantiere",
            "url": "", "title": title, "text": text,
        }
        f.write(json.dumps(rec, ensure_ascii=False) + "\n")
print("scritti", len(ESEMPI), "esempi ->", OUT)
