# -*- coding: utf-8 -*-
"""Genera il corpus FAQ: domande tipiche dei clienti privati con risposta da professionista."""
import json, os

F = []

# ---------------- AMPLIAMENTI E VOLUMI (8) ----------------
F.append(("ampliamenti","Posso chiudere il balcone per fare una veranda abitabile?",
"Chiudere un balcone e renderlo abitabile e' in genere una 'modifica alla destinazione d'uso' che comporta aumento del volume riscaldato: serve il permesso di costruire (art. 10 DPR 380/2001), non la semplice SCIA. Inoltre verifica il regolamento condominiale: il balcone e' spesso di proprieta' esclusiva ma la facciata e' comune, quindi serve il consenso dell'assemblea. In molti comuni la veranda vetrata e' comunque ammessa in deroga se non altera la facciata (c.d. chiusura 'trasparente' conservativa): devo verificare il regolamento edilizio comunale prima di proporle una soluzione."))
F.append(("ampliamenti","Voglio alzare il tetto di un piano per fare una mansarda: cosa serve?",
"L'elevazione di un piano e' sempre una nuova costruzione: richiede permesso di costruire, progetto strutturale completo, verifica sismica e spesso accertamento di compatibilita' idraulica e paesaggistica. Attenzione ai limiti del PRG: altezza massima, distanze dai confini, rapporti di copertura. Se il fabbricato e' in zona sismica e' probabile che la sopraelevazione richieda anche il miglioramento antisismico dell'esistente secondo le NTC 2018 (criteri di riduzione del rischio). Il primo passo e' acquisire il PRG vigente e fare un sopralluogo tecnico."))
F.append(("ampliamenti","Posso costruire un pergolato o una tettoia nel giardino senza permesso?",
"Dipende da dimensioni, altezza e vincoli: molti comuni ammettono i pergolati aperti (non chiusi) su terreni privati entro i limiti del regolamento edilizio (tipicamente sotto i 20-30 m² e con altezza limitata), ma in area vincolata (paesaggistica, Soprintendenza) serve sempre l'autorizzazione. Una tettoia chiusa ai lati o con superficie superiore alla soglia comunale e' invece assimilata a una costruzione e richiede titolo edilizio. Le consiglio di verificare il regolamento edilizio comunale e, se c'e' un vincolo paesaggistico, di fare una CILA comunque per essere coperto."))
F.append(("ampliamenti","Quanto posso ampliare la casa con il bonus prima casa o le detrazioni?",
"Le detrazioni fiscali non aumentano i volumi ammessi: il diritto di costruire lo decide il PRG e il regolamento edilizio. Le detrazioni ristrutturazioni (50%) coprono gli ampliamenti regolarmente autorizzati; per gli ampliamenti fino a 40 m² esistono agevolazioni specifiche nel codice dei contratti pubblici per il Sismabonus, ma i requisiti sono tecnici (miglioramento antisismico di tutto l'edificio). Quindi: prima si verifica cosa si puo' costruire, poi si valutano gli sgravi. Possiamo fare entrambe le verifiche in un unico sopralluogo."))
F.append(("ampliamenti","Il mio comune dice che sono in zona sismica: posso comunque sopraelevare?",
"Si', ma con vincoli maggiori: in zona sismica le sopraelevazioni devono rispettare i criteri di riduzione del rischio delle NTC 2018, il che spesso significa interventi sull'esistente (catene, rinforzi, collegamenti solai-muri). Il progettista deve dimostrare che dopo l'intervento il rischio sismico non aumenta; in pratica molti comuni chiedono un'assicurazione o un parere di compatibilita'. Inoltre sopraelevare un edificio esente da vincoli strutturali puo' richiedere la ricostruzione di fondazioni: il costo strutturale e' quasi sempre la voce che decide la convenienza."))
F.append(("ampliamenti","Ho ricevuto una diffida dal comune per un pergolato gia' costruito: cosa posso fare?",
"Le strade sono due: la sanatoria (condono edilizio ex art. 34-37 DPR 380/2001) se l'opera rientra nei casi previsti per opere realizzate in epoche passate, oppure la regolarizzazione tramite nuovo titolo se il manufatto e' conforme al PRG. Un opuscolo amministrativo regolarizzabile puo' essere presentato in corso di sanatoria. In entrambi i casi serve un tecnico abilitato che valuti l'opera, la confronti con la normativa vigente e presenti la pratica. Mi faccia vedere la diffida e la documentazione catastale: definisco la strategia migliore."))
F.append(("ampliamenti","Posso trasformare il garage in una camera da letto?",
"Il garage ha in genere destinazione d'uso diversa dall'abitazione: cambiare uso da 'accessorio' a 'residenziale' e' una modifica della destinazione d'uso che richiede pratica edilizia (SCIA o permesso a seconda del comune). Inoltre servono requisiti igienico-sanitari: apertura finestrata con rapporti aeroilluminanti, altezza minima (tipicamente 2,70 m), e spesso un posto auto sostitutivo se il regolamento edilizio lo prevede. Se il box e' in condominio serve anche l'assenso dell'assemblea. E' un intervento fattibile nella maggior parte dei casi, ma va fatto con la pratica corretta."))
F.append(("ampliamenti","Quanto costa fare una veranda chiusa di 20 m²?",
"Indicativamente, per una veranda in alluminio a taglio termico con vetrocamera, comprensiva di fondazioni, pratica e smaltimento: 1.200-1.800 €/m², quindi 24.000-36.000 € IVA esclusa, a seconda della qualita' dei serramenti e delle finiture. Aggiungere eventuale riscaldamento elettrico a pavimento (1.500-3.000 €) e burocrazia (2.000-4.000 € tra pratica, strutturale e direzione lavori). Per un preventivo serio serve il sopralluogo: le misure e le condizioni del balcone cambiano molto i costi."))

# ---------------- BONUS E DETRAZIONI (10) ----------------
F.append(("bonus","La detrazione del 50% ristrutturazioni copre anche le spese professionali?",
"Si': rientrano nella detrazione del 50% le spese per lavori edilizi, impianti e onorari professionali direttamente legati all'intervento (progettazione, direzione lavori, collaudi). Non rientrano invece le spese di arredamento, le pratiche puramente amministrative non tecniche e le spese di mediazione. Il pagamento deve avvenire con bonifico 'parlante' intestato a chi esegue i lavori, e la detrazione si ripartisce in 10 quote annuali. Conservi fatture, bonifici e contratti: l'Agenzia delle Entrate puo' verificare fino a 5 anni."))
F.append(("bonus","Posso avere il bonus per la pompa di calore se cambio la caldaia?",
"Si': la sostituzione di un impianto a gas con pompa di calore rientra nelle detrazioni efficientamento (65% o 70% seconda fascia) con massimale dedicato, oppure nel Conto Termico 3.0 come incentivo a fondo perduto. I requisiti: sostituzione di un generatore esistente a combustibile fossile, rispetto dei requisiti minimi (SCOP dichiarato), e documentazione dello stato ante. La pompa di calore ibrida (gas + elettrico) e' incentivata a condizioni diverse: verifichiamo insieme quale misura conviene nel suo caso specifico."))
F.append(("bonus","Il fotovoltaico e' ancora incentivato nel 2026?",
"Il fotovoltaico residenziale gode della detrazione del 50% (ripartita in 10 anni) o, in alternativa, del Conto Termico 3.0; inoltre l'energia immessa in rete puo' essere remunerata tramite Ritiro Dedicato o Scambio sul Posto residuale. La scelta dipende da consumo, produzione stimata e se c'e' accumulo: per un'utenza che consuma di sera l'accumulo aumenta molto la convenienza. Il mio consiglio: fare un bilancio energetico preliminare prima di scegliere la configurazione."))
F.append(("bonus","Come funziona il Conto Termico 3.0 e chi puo' accedervi?",
"E' l'incentivo del GSE (ente gestore servizi energetici) per interventi di efficienza energetica e rinnovabili su edifici esistenti: invece della detrazione fiscale (sconto Irpef), si ottiene un contributo a fondo perduto erogato dall'GSE dopo il collaudo. Possono accedere privati, condomini e imprese; i requisiti prevedono un miglioramento minimo delle prestazioni (tipicamente salto di classe energetica o superamento di un miglioramento minimo percentuale) e lavori eseguiti da imprese qualificate. La domanda va presentata PRIMA dell'inizio lavori: e' l'errore piu' comune, quindi contatti un tecnico prima di firmare il contratto."))
F.append(("bonus","Conviene piu' il 50% in detrazione o il Conto Termico?",
"Dipende dalla sua situazione fiscale: il 50% conviene se ha un'Irpef sufficiente da assorbire le quote annuali (reddito e aliquota marginali), perche' resta suo il beneficio pieno; il Conto Termico conviene se paga poche tasse, se non vuole aspettare 10 anni, o se interviene su parti comuni di un condominio. Il Conto Termico richiede pero' requisiti tecnici piu' stringenti e lavori piu' corposi. Faccio sempre il confronto economico sui due scenari prima di consigliare una strada."))
F.append(("bonus","Il bonus facciate copre anche la tinteggiatura interna?",
"No: il bonus facciate e' dedicato esclusivamente alle opere esterne (recupero o restauro della facciata, incluse pulizia, tinteggiatura esterna e opere sugli elementi appartenenti alla facciata). La tinteggiatura interna rientra nella detrazione ordinaria del 50% ristrutturazioni. Inoltre il bonus facciate richiede che l'edificio sia in zona omogenea A o B (centri storici o consolidati) o condomini in tutte le zone, ed e' stato riformato piu' volte: verifichiamo le regole vigenti all'atto della pratica."))
F.append(("bonus","Ho fatto lavori senza pratica: posso comunque avere la detrazione?",
"No: la detrazione richiede la pratica edilizia regolare (permesso, SCIA o CILA secondo i casi) e il pagamento tracciabile. Lavori abusivi non danno diritto a incentivi e peggiorano la situazione patrimoniale (impossibilita' di vendere, sanzioni). La prima cosa da fare e' regolarizzare con un tecnico: valutiamo se l'intervento e' sanabile con una pratica in sanatoria o va rimodulato. Solo dopo possiamo parlare di detrazioni."))
F.append(("bonus","Il mio commercialista dice che il bonus non si applica a me perche' non ho reddito: e' vero?",
"Se il reddito e' molto basso, la detrazione in 10 anni puo' risultare di difficile utilizzo (quote annuali che non trovano Irpef sufficiente). Le alternative sono il Conto Termico 3.0 (contributo a fondo perduto, non dipende dal reddito) oppure cedere il credito a un istituto di credito (sconto in fattura), se la misura lo prevede. Il mio ruolo e' quello del tecnico: per la parte fiscale si affidi a un commercialista, ma per la scelta tecnica dell'intervento che massimizza l'incentivo posso darle un quadro completo."))
F.append(("bonus","Il Superbonus e' finito: cosa resta per la ristrutturazione completa?",
"Dal 2025 in poi il Superbonus al 110% e' concluso; restano la detrazione del 50% ristrutturazioni e le detrazioni efficientamento (65-75%), piu' il Conto Termico 3.0 e le detrazioni per specifiche categorie (barriere architettoniche, fotovoltaico, bonifica amianto). Inoltre alcune regioni hanno bandi a fondo perduto per l'efficientamento. Per una ristrutturazione completa conviene costruire un 'pacchetto lavori' che massimizzi gli incentivi cumulabili: e' il tipo di analisi che faccio di routine prima di avviare il progetto."))
F.append(("bonus","Le detrazioni valgono anche se pago un amico che fa i lavori?",
"No: i lavori devono essere eseguiti da imprese o artigiani regolarmente attivi (partita IVA) e pagati con bonifico identificato; i versamenti vanno documentati. Il 'fai da te' puo' essere ammesso solo per materiali in casi limitati e con requisiti specifici, mentre la manodopera non professionalizzata esclude la detrazione e pone problemi di sicurezza e garanzia. Le consiglio di non rischiare: l'eventuale accertamento le richiede il rimborso con sanzioni."))

# ---------------- CONFINI E MURI (8) ----------------
F.append(("confini","Il muro di cinta e' sul confine: di chi e' e chi paga la manutenzione?",
"Secondo l'art. 892 c.c., se il muro e' costruito sul confine di due proprietadi e' comune per meta', a meno che non vi siano titoli o segni contrari (coperture, scarichi, camino, lavori eseguiti a spese di uno solo). La manutenzione ordinaria e' a carico dei comproprietari in misura proporzionale, mentre l'altezza non puo' essere aumentata senza consenso di entrambi. In caso di contestazione serve il rilievo del confine da parte di un tecnico (geometra o perito) con documentazione catastale. Per il suo caso specifico: guardiamo prima le carte e le evidenze murarie."))
F.append(("confini","Il vicino ha costruito a meno di tre metri dal confine: e' lecito?",
"Dipende dal regolamento edilizio comunale: la distanza minima dalle proprietadi confinanti (tipicamente 3 metri, ma varia) si misura tra il muro esterno dell'edificio e il confine, e serve a garantire aeroilluminazione e manovre. Alcuni comuni prevedono deroghe per edifici a schiera o distanze ridotte con consenso del vicino. Se il regolamento e' stato violato, il comune puo' intervenire; il vicino puo' agire per diffondere l'ombra o i pregiudizi arrecati. Verifico il PRG e la licenza edilizia del vicino prima di dirle se ha un ricorso fondato."))
F.append(("confini","Posso costruire il muro di cinta direttamente sul confine?",
"Il muretto di cinta fino a una certa altezza (tipicamente 2,20-2,50 m secondo regolamento edilizio) puo' essere costruito sul confine senza distacco, perche' non richiede distanze di rispetto aeroilluminanti: e' l'eccezione all'obbligo generale delle distanze. L'altezza massima e' comunque fissata dal regolamento edilizio; oltre quella soglia serve distanza o consenso del vicino. Consiglio sempre un sopralluogo di comune accordo col vicino: il muro comune costruito senza tensioni evita decenni di lite."))
F.append(("confini","L'albero del vicino sporge nel mio giardino: posso tagliare i rami?",
"Secondo gli artt. 892 e 910 c.c., il proprietario puo' esigere che i rami e le radici che sporgono sulla sua proprieta' siano tagliati a spese del proprietario dell'albero, sempre nel rispetto delle norme sulla tutela del verde comunale: spesso per tagli consistenti serve la segnalazione al comune, e il taglio deve avvenire in modo da non compromettere la stabilita' dell'albero. Il frutto raccolto sul suo terreno e' suo, ma la pianta resta del vicino. Se il vicino non interviene, puo' chiedere al giudice: in genere basta una lettera del tecnico per risolvere."))
F.append(("confini","Il confine catastale non coincide con il muro: chi ha ragione?",
"Catasto e confine reale sono due cose diverse: il catastale e' di tipo fiscale e non vincolante rispetto al confine legale, che si determina con i titoli, le mappe di gara e le evidenze sul terreno (muri, recinzioni antiche). La verifica corretta passa da un rilievo integrato con documentazione storica e, se serve, dalla ricostruzione della 'mappa di gara'. Come tecnico posso fare un accertamento tecnico preventivo che chiarisca la situazione: e' la base per qualsiasi trattativa o, in ultima istanza, ricorso."))
F.append(("confini","Il vicino scarica l'acqua piovana sul mio terreno: e' lecito?",
"No: l'art. 913 c.c. vieta di prosciugare le acque piovane sul fondo del vicino, salvo usi consuetudinari e particolari situazioni di luogo. La gronda deve scaricare nel proprio fondo, in modo comune (pozzetto o rete fognaria), o con diritto di stillicidio (la sola caduta naturale sulla proprietadi confinante, senza gronda diretta). Se l'acqua danneggia il suo muro o giardino, puo' richiedere la rimozione del danno e l'adozione dei dispositivi corretti. Documenti con foto e relazione tecnica rafforzano molto la sua posizione."))
F.append(("confini","Voglio mettere la recinzione: devo rispettare qualche distanza?",
"La recinzione ordinaria (rete, muretto basso) puo' essere posta sul confine; le recinzioni continue e alte (muri pieni o recinti di sicurezza con filo spinato) seguono le regole del regolamento edilizio e talvolta richiedono CILA o SCIA. Nei centri storici e nelle zone vincolate valgono regole piu' severe su materiali e altezze. Inoltre, se la recinzione fa da supporto a impianti (illuminazione, videosorveglianza) o crea un vero e proprio ambiente chiuso, si allontana dalla semplice recinzione. Verifichiamo il regolamento prima dell'acquisto del materiale."))
F.append(("confini","Il vicino ha murato la finestra che dava sul mio cortile: posso farla riaprire?",
"Dipende dalla data della muratura e dalla situazione preesistente: le prescrizioni civili sull'azione diretta di luce proteggono i lucernari e le finestre 'con imposta a giorno' (c.d. azione diretta, art. 903 c.c. come modificato), cioe' aperture vetrate. Se la finestra e' stata chiusa da meno di 40 anni e la distanza era insufficiente, esiste un'azione giudiziale per ottenerne la riapertura o il risarcimento. Serve documentazione storica: foto, planimetrie, testimonianze. Le conviene subito acquisire le prove, perche' il tempo indebolisce la posizione."))

# ---------------- PRATICHE E TEMPI (8) ----------------
F.append(("pratiche","CILA, SCIA o permesso di costruire: quale serve per la mia ristrutturazione?",
"La regola generale del DPR 380/2001: il permesso di costruire serve per opere nuove o ampliamenti che modificano volumi e destinazione; la SCIA per ristrutturazioni e restauro conservativo che mantengono volumi e destinazione; la CILA per interventi interni piu' leggeri (come tinteggiature, massetti, sostituzione infissi interni). Il confine tra SCIA e permesso e' spesso oggetto di interpretazione: lo decide il regolamento edilizio comunale. Il mio lavoro parte proprio da questa classificazione: un errore qui costa mesi di pratica."))
F.append(("pratiche","Quanto tempo ci vuole per il permesso di costruire?",
"Nei comuni medi: 60-120 giorni di istruttoria per il rilascio, a cui si aggiungono i tempi per la redazione del progetto (4-8 settimane per un preliminare, 8-16 per l'esecutivo con varianti). I termini possono sospendersi per integrazioni documentali (richieste del comune), pareri della Soprintendenza nei centri storici, accertamenti idraulici o paesaggistici. In totale, dal sopralluogo al cantiere, e' realistico stimare 6-12 mesi per un'opera nuova. Le fornisco un cronoprogramma dettagliato dopo il primo sopralluogo."))
F.append(("pratiche","La SCIA e' immediata oppure il comune puo' bloccare i lavori?",
"La SCIA consente l'inizio lavori alla presentazione (silenzio-assenso), ma il comune puo' verificare a posteriori la regolarita' e ordinare la sospensione se l'intervento non e' conforme. Inoltre alcuni comuni richiedono preventivamente controlli (verifica della SCIA) prima di rilasciare il nullaosta a sportello ai fini catastali. Quindi la SCIA e' 'rapida' ma non immune da contestazioni: serve che il progetto sia corretto fin dalla classificazione dell'intervento."))
F.append(("pratiche","Devo fare l'aggiornamento catastale dopo i lavori?",
"Si': ogni variazione che modifica la consistenza dell'immobile (nuovi locali, cambio di destinazione, variazioni di superficie) va denunciata al Catasto Fabbricati con tipo di mappa o DOCFA, a cura di un geometra o professionista abilitato. La sanzione per omessa o tardiva denuncia e' una irregolarita' formale sanabile, ma rende difficoltosa la vendita o il passaggio ipotecario. Di regola il tecnico che segue il cantiere presenta la pratica catastale a fine lavori: e' parte standard del mio incarico."))
F.append(("pratiche","Ho un immobile con abusi: conviene comprarlo?",
"Dipende dalla tipologia e dalla data: gli abusi realizzati dopo il 1968, con particolare riguardo a quelli non sanabili (fuori sagoma, violazione distanze, destinazione d'uso), possono non sanabili e quindi il compratore si trova con un immobile di fatto non vendibile o demolibile. Gli abusi interni o chiusi in sagoma sono spesso sanabili con condono (se realizzati entro il 2003) o, dopo tale data, solo con il c.d. 'condono edilizio' piu' complesso. Prima di comprare faccia fare una perizia urbanistica e catastale completa: costa poco e le evita investimenti sbagliati."))
F.append(("pratiche","La SCIA presentata dal vecchio proprietario copre i miei lavori?",
"No: la SCIA vincola l'intervento descritto e il committente che l'ha presentata. Se lei vuole fare lavori diversi o ulteriori, serve una nuova pratica. Inoltre la SCIA si 'porta appresso' le responsabilita' del committente originario: se l'intervento era difforme, la responsabilita' resta sul soggetto che ha realizzato. Prima di acquistare faccia verificare da un tecnico la conformita' degli elaborati allo stato di fatto."))
F.append(("pratiche","Cosa serve per fare il cambio di destinazione d'uso da ufficio ad abitazione?",
"Il cambio di destinazione d'uso e' un intervento urbanisticamente rilevante: in genere serve permesso di costruire (o SCIA con parere tecnico, secondo il comune) e il rispetto dei requisiti igienico-sanitari dell'abitazione (aeroilluminazione, altezze, bagni, cucina, posti auto se previsti). Serve anche la verifica che il PRG consenta la destinazione residenziale in quella zona. E' uno degli interventi piu' delicati: le consiglio un sopralluogo tecnico prima di qualsiasi acquisto o investimento."))
F.append(("pratiche","Il comune chiede il nullaosta della Soprintendenza: cosa significa?",
"Significa che l'immobile e' sottoposto a vincolo culturale (vincolo diretto ex D.Lgs 42/2004) o si trova in zona tutelata (centro storico, area archeologica, paesaggio): qualsiasi modifica, anche interna, richiede l'autorizzazione del Ministero, che valuta la compatibilita' dell'intervento con la tutela. I tempi si allungano di 60-120 giorni e le soluzioni tecniche possono essere vincolate (materiali, colori, tecniche). Chi compra immobili vincolati deve saperlo prima: le incidenze progettuali e di costo sono reali. Verifico sempre la presenza di vincoli nella prima fase di due diligence."))

# ---------------- PREVENTIVI E COSTI (8) ----------------
F.append(("costi","Quanto costa ristrutturare una casa di 100 m²?",
"Una ristrutturazione completa chiavi in mano (impianti, massetti, bagni, cucina, infissi, tinteggiatura) costa indicativamente 900-1.400 €/m² per standard medio, quindi 90.000-140.000 € per 100 m²; per un livello medio-alto con materiali di pregio si sale a 1.600-2.200 €/m². La voce piu' variabile e' l'impiantistica (25-35% del totale), seguita da bagni e finiture. Per un preventivo attendibile serve il rilievo e un computo metrico: il prezzo 'a metro quadro' e' solo una stima di massima."))
F.append(("costi","Quanto costa ristrutturare un bagno completo?",
"Un bagno completo con sanitari sospesi, box doccia, rifacimento impianti e piastrelle di fascia media costa indicativamente 4.500-7.000 €; con doccia in muratura, sanitari di design e rivestimenti di pregio si arriva a 8.000-12.000 €. Le voci decisive sono: impianti idraulici (30-40%), piastrellatura (25-30%), sanitari e arredo (20-25%). Il rilievo iniziale e' gratuito nella maggior parte dei casi: facciamolo prima di decidere."))
F.append(("costi","Come faccio a capire se un preventivo e' troppo basso o troppo alto?",
"Il metodo professionale e' il computo metrico estimativo: chieda all'impresa un preventivo con voci dettagliate (unita' di misura, quantita', prezzo unitario), non solo un prezzo globale. Confronti almeno 3 offerte sulle stesse voci e verifichi le esclusioni (smaltimento, pratiche, sicurezza). Un prezzo nettamente sotto la media di mercato e' un campanello d'allarme: potrebbe nascondere voci mancanti o manodopera non qualificata. Posso aiutarla a leggere i preventivi delle imprese."))
F.append(("costi","Quanto costa la pratica edilizia (progettista, pratiche)?",
"Gli onorari professionali seguono i parametrini o le tariffe professionali (DM 137/2012) o sono liberamente concordati. Indicativamente: pratica SCIA per ristrutturazione 2.500-5.000 €, progetto strutturale 3.000-6.000 €, direzione lavori 5-8% dell'importo lavori, pratica catastale 400-800 €. Le spese vive (diritti comunali, bolli, pareri) sono a parte e indicativamente 1.000-3.000 € secondo il comune. Tutti questi costi danno diritto alla detrazione del 50%."))
F.append(("costi","Cosa succede se durante i lavori emergono lavori extra non previsti?",
"Nei contratti di appalto si usano le 'varianti in corso d'opera': lavorazioni non preventivate che si rendono necessarie per cause non imputabili alle parti (es. umidita' occulte, reti impiantistiche sconosciute). La corretta gestione prevede: sopralluogo congiunto, preventivo scritto della variante, ordine firmato, poi esecuzione. Chi non documenta le varianti per iscritto si espone a contestazioni sul saldo. Il mio incarico di direzione lavori include esattamente questo controllo."))
F.append(("costi","Quanto costa alzare la casa di un piano rispetto a comprare una casa nuova?",
"Sopraelevare costa in genere 1.200-1.800 €/m² costruito (struttura, copertura, facciata, impianti, interni finiti), cui si aggiungono progetto, pratica, eventuale rinforzo strutturale e accatastamento: per 60 m² nuovi si parla spesso di 90.000-140.000 € totali. Il vantaggio e' il rinnovo dell'esistente con incentivi; lo svantaggio e' il cantiere prolungato. Comprare una casa nuova o piu' grande ha costi di compravendita (9-15%) ma tempi piu' brevi. Faccio volentieri il confronto economico per il suo caso specifico."))
F.append(("costi","Il preventivo 'chiavi in mano' include anche le pratiche?",
"Dipende dal contratto: nel 'chiavi in mano' il costruttore si fa carico di tutto, pratiche comprese, ma e' indispensabile che il contratto lo specifichi. Spesso invece il prezzo esclude pratiche, accatastamento e oneri comunali: sono voci da verificare riga per riga. Nel mio modo di lavorare, il computo metrico separa esplicitamente le voci a corpo dell'impresa dalle spese di pratica: la trasparenza evita il 90% delle controversie."))
F.append(("costi","Quanto costa un sopralluogo tecnico per un acquisto immobiliare?",
"Un sopralluogo di due diligence tecnica (verifica strutturale, impianti, stato di conservazione, rischi) costa indicativamente 300-800 € a seconda della complessita' e della localizzazione; la perizia urbanistico-catastale completa 500-1.500 €. E' un investimento minimo rispetto al costo di un immobile: scoprire un difetto strutturale prima dell'acquisto vale decine di migliaia di euro. Molti miei clienti la richiedono come condizione all'offerta di acquisto."))

# ---------------- RISTRUTTURAZIONE E IMPIANTI (10) ----------------
F.append(("ristrutturazione","Conviene rifare tutto l'impianto elettrico o aggiustare quello esistente?",
"Se la casa ha piu' di 30-40 anni e l'impianto e' originale, il rifacimento completo e' quasi sempre la scelta migliore: le norme di sicurezza sono cambiate (salvavita, sezioni cavi, quadri con barre), i carichi moderni (induzione, climatizzazione, ricarica auto) richiedono linee dedicate e un quadro moderno costa relativamente poco rispetto al valore della casa. Il rifacimento parziale conviene solo se l'impianto e' recente e dimensionato. Faccio sempre una verifica con strumenti prima di consigliare."))
F.append(("ristrutturazione","Il pavimento scricchiola: e' pericoloso o e' solo il legno?",
"Lo scricchiolio in un solaio e' spesso innocuo: nel legno e' tipico per assestamenti stagionali; nel laterocemento puo' essere il gioco delle fughe di battiscopa o l'aderenza del pavimento. Diventa un segnale di allarme se e' accompagnato da flessioni visibili, lesioni alle pareti, umidita' o scricchiolio ritmico (possibile cedimento di un appoggio). Un sopralluogo strutturale con misura delle frecce (± mm) chiarisce in un'ora se c'e' un problema da monitorare o se e' tutto fisiologico."))
F.append(("ristrutturazione","Ho la muffa negli angoli: e' colpa dell'isolamento che manca?",
"Nella maggior parte dei casi si': gli angoli esterni sono ponti termici e le superfici scendono sotto la temperatura di rugiada (circa 9,3 °C con 20 °C e 50% di umidita' interna), formando condensa che alimenta la muffa. Le cause meno comuni ma da non sottovalutare sono: umidita' di risalita dal terreno, infiltrazioni, ponti termici da pilastri/scalini e scarsa ventilazione. La diagnosi corretta distingue le cause: solo dopo si decide tra cappotto, deumidificazione, VMC o barriera chimica. Una diagnosi sbagliata spreca i soldi dell'intervento."))
F.append(("ristrutturazione","Posso togliere un muro portante? Quanto costa?",
"Si puo', ma serve un progetto strutturale: si valuta il carico che scarica il muro, si progetta un'intelaiatura di sostegno (trave in acciaio o in legno, pilastri), si calcola la fondazione e si esegue con cantiere controllato (puntellamento progressivo). Il costo dipende dalla luce e dal carico: indicativamente 2.500-6.000 € per un muro di 4-5 metri con fondazione rinforzata, pratica inclusa. E' uno degli interventi dove risparmiare sul progettista costa piu' caro della struttura stessa."))
F.append(("ristrutturazione","Il bagno ha l'umidita' sul soffitto del vicino di sotto: chi paga?",
"Se l'umidita' arriva dal tuo bagno (perdita da scarichi, sanitari o piatto doccia) la responsabilita' e' del proprietario dell'unita' da cui trae origine il danno, secondo gli artt. 2043 e 2055 c.c. e la giurisprudenza condominiale. In genere si interviene con la ricerca della perdita (termografia, misure umidita'), il rifacimento del bagno e il risarcimento del vicino. Le assicurazioni RC casa coprono spesso il danno a terzi: segnali subito alla sua assicurazione e faccia fare una relazione tecnica."))
F.append(("ristrutturazione","Conviene la VMC anche in un appartamento piccolo?",
"Dipende da come vivete: se cucinate spesso, ci sono bambini, o l'appartamento e' molto sigillato dopo la ristrutturazione, la VMC (anche in versione deumidificante o con solo due unita' scambio) migliora nettamente qualita' dell'aria e salute delle pareti. Il costo per un appartamento di 80-100 m² e' indicativamente 3.000-5.500 € installata. Se invece arieggiate regolarmente e non avete problemi di condensa, puo' bastare l'aerazione controllata con griglie e ventilazione assiale. Valutiamolo insieme alla diagnosi energetica."))
F.append(("ristrutturazione","Riscaldamento a pavimento o termosifoni: cosa conviene?",
"Il pavimento radiante conviene in costruzioni nuove o con massetti da rifare: comfort superiore, energia fino al 15-20% in meno con pompa di calore, nessun ingombro. I termosifoni conviene mantenere in ristrutturazioni leggere dove non si toccano i massetti: costo quasi nullo, risposta rapida. La scelta sbagliata piu' costosa e' fare il pavimento radiante sopra un massetto esistente con sottorilievi: compromessi tecnici e costi lievitano. La decisione corretta si prende guardando massetti, altezze e generatore di calore previsto."))
F.append(("ristrutturazione","Quanto costa sostituire la caldaia con una pompa di calore?",
"Per un appartamento o una casa unifamiliare piccola: pompa di calore aria-acqua da 6-10 kW installata con circolatore e integrazione 3.000-7.000 €, piu' eventuale adeguamento dei radiatori (se servono temperature piu' basse) o distribuzione nuova. La detrazione 65% o il Conto Termico riducono molto il costo effettivo. Attenzione alla rumorosita' (unita' esterna) e alla potenza elettrica contrattuale: verifichiamo entrambe in sopralluogo."))
F.append(("ristrutturazione","Il fotovoltaico sul condominio: si puo' fare?",
"Si': le convenzioni di condominio ammettono l'installazione su parti comuni con il rispetto delle regole sull'uso del tetto e le esigenze energetiche; in genere serve l'autorizzazione dell'assemblea e l'accordo tra condomini per la ripartizione dei costi e dei benefici. Le agevolazioni (detrazione 50% o Conto Termico) sono cumulabili per le spese comuni. La configurazione tipica e' il 'condominio energetico' con contabilizzazione delle quote: serve un tecnico per la parte comunitaria e la stima dei consumi condominiali."))
F.append(("ristrutturazione","Ho solo umidita' in cantina: serve l'intervento sulla casa?",
"Dipende dalla causa: se l'umidita' e' di risalita (pavimento senza barriera) o da condensa (cantina fredda e non ventilata), l'intervento puo' limitarsi alla cantina (barriera chimica, intonaco deumidificante, ventilazione). Se invece c'e' infiltrazione da falda alta o reti fognarie, serve l'individuazione della perdita e la riparazione. Il sopralluogo con misura dell'umidita' dei muri e della temperatura superficiale distingue le due cause in un'ora."))

# ---------------- CATASTO E FRAZIONAMENTI (7) ----------------
F.append(("catasto","Che differenza c'e' tra catastale e planimetria catastale?",
"Il catastale e' l'insieme dei dati fiscali (foglio, particella, subalterno, categoria, classe, vani, superficie); la planimetria catastale e' la rappresentazione grafica dei locali. La legge di riferimento e' il DPR 138/1998 e le planimetrie vanno aggiornate a ogni variazione della distribuzione interna (il famoso tipo mappa per le variazioni di consistenza). La visura catastale NON attesta la regolarita' urbanistica: e' solo un dato fiscale. Per la compravendita servono entrambe verificate."))
F.append(("catasto","Posso frazionare un appartamento in due unita'?",
"Si', ma serve un duplice passaggio: urbanistico (SCIA o permesso secondo il comune per la variazione della distribuzione interna) e catastale (nuovi subalterni con tipo mappa). Inoltre i due appartamenti risultanti devono essere entrambi conformi ai requisiti igienico-sanitari (finestre, altezze, servizi). Se l'immobile e' vincolato, serve anche il parere della Soprintendenza. Il frazionamento e' uno degli interventi piu' redditizi in vendita, ma va fatto bene: gli errori si pagano in vendita."))
F.append(("catasto","La categoria catastale dell'immobile cambia dopo la ristrutturazione?",
"Dipende: la categoria cambia se cambia la destinazione d'uso (es. da C/2 laboratorio ad A/2 abitazione) o la classe di rilevanza (es. A/3 ad A/2). Il passaggio tra categorie confluisce in una variazione catastale con aggiornamento della rendita: puo' comportare un aumento della base imponibile IMU e delle imposte di registro alla vendita. E' uno degli aspetti da verificare nella due diligence pre-acquisto: faccio sempre il confronto tra il catastale attuale e quello risultante dal progetto."))
F.append(("catasto","Come si legge una visura catastale in 5 minuti?",
"Punti chiave: intestazione (comune, foglio, particella, subalterno); categoria e classe (A/2 civile abitazione, A/10 ufficio, C/2 laboratorio...); vani e superficie (confronta con lo stato di fatto); rendita catastale (base di calcolo fiscale); intestazione (proprietari e quote, eventuali servitu' e diritti reali). Qualsiasi difformita' tra visura e realta' (superfici, vani, destinazione) segnala un lavoro da fare prima della vendita. Posso fare la verifica per lei su documenti."))
F.append(("catasto","Ho ereditato un immobile: devo fare volture e catastali?",
"L'accettazione di eredita' comporta l'obbligo di voltura catastale e ipotecaria entro 12 mesi (imposta di successione esente o con franchigie a seconda del grado). Se l'immobile non e' mai stato accatastato o ha difformita', l'eredita' e' il momento giusto per sistemarlo. Inoltre verificare che l'immobile ereditato sia regolarmente urbanizzato: eredita' anche le irregolarita'. Un tecnico puo' gestire volture, eventuali sanatorie e la pratica catastale in un unico incarico."))
F.append(("catasto","La mia casa non e' allacciata al Catasto Fabbricati: cosa rischio?",
"Un immobile non accatastato o con difformita' gravi non puo' essere venduto regolarmente (il notaio non puo' trascrivibile), non da accesso ai finanziamenti e puo' subire sanzioni fiscali. La regolarizzazione passa da una pratica catastale (tipo mappa o DOCFA) a cura di un tecnico abilitato, spesso accompagnata da una verifica urbanistica. Prima si agisce meglio e': le irregolarita' si trascinano decenni e svalutano l'immobile."))
F.append(("catasto","Cosa sono le servitu' prediali e come si verificano?",
"Sono diritti reali che gravano su un immobile a favore di altri (passaggi, tubazioni, acque, vedute): si verificano in visura catastale e ipotecaria sotto la voce 'diritti di terzi'. Le servitu' silenzio-assentiscono con il passaggio del tempo? No: esistono solo se costituite per atto o usucapione, ma alcune si possono costituire per destinazione del padre di famiglia. In fase di acquisto verifico sempre la visura ipotecaria per l'esistenza di servitu' nascoste."))

# ---------------- LOCAZIONE E CONDOMINIO (7) ----------------
F.append(("condominio","Il locatario puo' fare lavori senza il mio consenso?",
"No: l'art. 1592 c.c. vieta al conduttore di fare mutazioni o aggiunte senza il consenso scritto del locatore. I miglioramenti utili sono rimborsabili alla riconsegna secondo il criterio del minor valore tra costo e incremento di valore. Se il locatario fa lavori abusivi, il locatore puo' chiedere il ripristino o trattenere dal deposito. Nel contratto conviene sempre specificare le opere consentite e il regime delle autorizzazioni."))
F.append(("condominio","L'inquilino paga l'adeguamento del cappotto?",
"No: l'art. 1123 c.c. prevede che le spese per l'ammodernamento dell'immobile (cappotto, ascensore, efficientamento) sono a carico del proprietario, non del conduttore, salvo diversa pattuizione nel contratto. Il conduttore puo' beneficiare della minor spesa di riscaldamento, ma non e' tenuto a contribuire. La legge 27/2013 (c.d. 'dispositivo Monti') prevede specifici diritti di informazione del conduttore sulle spese condominiali."))
F.append(("condominio","Chi paga la riparazione del tetto del condominio?",
"Il tetto e' parte comune (art. 1117 c.c.) e la ricostruzione per usura e' a carico di tutti i condomini, compresi quelli del piano terra, salvo diverso regolamento di condominio (nel vecchio condominio la ripartizione era proporzionale al valore dei piani). La manutenzione ordinaria (es. guaine localizzate) puo' seguire regole di riparto specifiche. Per liti sul riparto serve la deliberazione assembleare con le maggioranze previste."))
F.append(("condominio","Posso fare un locale condominiale (es. cantina) abitabile?",
"La trasformazione di locali comuni in uso abitativo e' una modifica della destinazione d'uso che richiede in genere il permesso di costruire o la SCIA comunale, il rispetto dei requisiti igienico-sanitari e l'approvazione dell'assemblea per la cessione in uso o la distribuzione. Il cambio di destinazione cambia anche la rendita catastale. E' un intervento possibile ma complesso: serve coordinamento tra tecnico, amministratore e assemblea."))
F.append(("condominio","L'amministratore puo' spendere senza approvazione dell'assemblea?",
"L'amministratore puo' effettuare spese urgenti di manutenzione ordinaria e straordinaria senza preventiva autorizzazione (art. 1138 c.c.), ma deve poi darne conto all'assemblea. Le opere straordinarie non urgenti richiedono la preventiva delibera assembleare. I condomini possono sempre chiedere la convocazione di un'assemblea straordinaria per approvare o contestare l'opera. Il controllo passa dalla trasparenza dei preventivi e delle delibere."))
F.append(("condominio","Il balcone condominiale di chi e'?",
"Di regola il balcone che insiste su parti comuni e' di proprieta' esclusiva del condomino dell'appartamento (art. 1117 c.c. n. 2), ma le parti strutturali (volta, travi) possono essere comuni. La chiusura del balcone e la sua trasformazione in veranda incide sulla facciata comune: serve il consenso dell'assemblea e il titolo edilizio. La giurisprudenza e' consolidata: la proprieta' esclusiva non autorizza opere sulla facciata senza accordo."))
F.append(("condominio","Vendo l'appartamento: devo pagare i lavori condominiani deliberati?",
"No: secondo la giurisprudenza consolidata, il venditore e' tenuto ai pagamenti dei lavori deliberati e non ancora eseguiti, ma il compratore puo' chiedere la riduzione del prezzo o la risoluzione se la spesa e' cospicua e non comunicata. Le spese condominiane deliberate e non comunicate vanno dichiarate nel preliminare di vendita. In pratica: chi vende paga le spese fino al rogito, chi compra paga da quel momento in poi. E' uno dei motivi per cui chiedo sempre le ultime delibere assembleari in fase di compravendita."))

# ---------------- MANUTENZIONE E PATOLOGIE (8) ----------------
F.append(("manutenzione","Le crepe nei muri quando sono pericolose?",
"La maggior parte delle fessurazioni e' fisiologica (ritiro degli intonaci, assestamenti) e si tratta con stucco. Diventano allarmanti quando: sono a cuspide e si allargano nel tempo, interessano l'intonaco e il muro sottostante, seguono i diagonali dei vani porta (possibile cedimento strutturale), compaiono dopo eventi sismici o movimenti del terreno. La regola pratica: fessura < 0,3 mm fisiologica, 0,3-1 mm da monitorare, > 1 mm con andamento progressivo richiede sopralluogo strutturale. Faccia sempre una foto con data per il confronto."))
F.append(("manutenzione","Il tetto perde in un punto solo: basta una pezza?",
"Una pezza e' una soluzione temporanea: la guaina impermeabilizzante invecchia uniformemente, quindi un punto di infiltrazione indica spesso che la membrana vicina e' a fine vita. La soluzione corretta dipende dall'estensione: riparazioni locali per danni puntuali (meccanici, fessure), rifacimento parziale per zone degradate, rifacimento completo per guaine vecchie. Il sopralluogo con termografia o prova di tenuta distingue i casi e le evita di pagare due volte."))
F.append(("manutenzione","Quanto dura una copertura in guaina bituminosa?",
"Una guaina bituminosa armata dura tipicamente 15-25 anni a seconda dell'esposizione, della pendenza e della qualita' di posa; le membrane sintetiche (PVC, TPO) arrivano a 25-35 anni. I segni di fine vita sono: fessurazione, bolle, sfaldamento, guaine che 'risalgono' ai bordi. La manutenzione programmata (verifica ogni 5 anni, pulizia, rifacimento cordoli) puo' allungare la vita di 5-10 anni. Verifichi sempre lo stato dei sottotetti in legno: l'umidita' invisibile li degrada prima della guaina."))
F.append(("manutenzione","L'umidita' sul muro vicino alla finestra e' infiltrazione o condensa?",
"Regola pratica: la condensa compare su superfici fredde (angoli, ponti termici) e migliora con la ventilazione; l'infiltrazione segue un percorso dall'esterno (soglie, davanzali, fessure) e peggiora con la pioggia. Prova rapida: mettere un foglio di carta sul muro umido — se dopo giorni la macchia e' solo dietro il foglio e' condensa; se segue una linea verticale dal davanzale e' infiltrazione. La soluzione cambia completamente: umidita' di condensa si risolve con isolamento e ventilazione, l'infiltrazione con la riparazione del percorso d'acqua."))
F.append(("manutenzione","Quando conviene rifare il tetto anziche' continuare a rattoppare?",
"Il calcolo e' semplice: se negli ultimi 3 anni le riparazioni hanno superato il 30-40% del costo di rifacimento, e la copertura ha piu' di 20 anni, il rifacimento conviene economicamente. Aggiunga il valore aggiunto: nuova stratigrafia coibentata, possibilita' di fotovoltaico integrato, garanzia decennale sul rifacimento, nessun danno da infiltrazioni future. Faccio volentieri il confronto costi-benefici sulla base di un sopralluogo."))
F.append(("manutenzione","Il solaio di legno del sottotetto e' ammalorato: si puo' salvare?",
"Dipende dallo stato: legno con carie superficiali o tarlatura localizzata puo' essere consolidato (iniezioni di resine, sostituzione dei pezzi danneggiati, trattamenti biocidi); legno marcio strutturale o con perdita di sezione superiore al 20-30% va sostituito. Le travi in legno antico sono spesso di qualita' superiore a quelle moderne: il consolidamento e' spesso la scelta migliore anche sotto il profilo storico. Un sopralluogo con prova di durezza (sclero) e valutazione visiva definisce l'intervento."))
F.append(("manutenzione","Cosa controllo prima dell'inverno per evitare danni alla casa?",
"Checklist di fine autunno: pulizia grondaie e caditoie, controllo di scarichi pluviali e pozzetti, verifica guaine e manti intorno ai camini, controllo del disgelo (tubazioni esterne), ispezione caldaia e tiraggio, tenuta degli infissi (guarnizioni), livello di umidita' in cantina e sottotetto. Un sopralluogo tecnico di 2 ore all'anno costa poco e previene danni che costano migliaia di euro. Molti miei clienti la fanno come manutenzione programmata annuale."))
F.append(("manutenzione","L'intonaco si sta staccando dai muri esterni: perche'? ",
"Le cause tipiche: umidita' di risalita che corrode l'aderenza, sali che cristallizzano tra intonaco e supporto, fessurazione della malta per ritiro o movimenti della struttura, intonaco applicato su supporto non preparato. Il rischio e' che i pezzi cadano verso l'esterno (pericolo pubblico) o verso l'interno. La rimozione e rifacimento di una fascia e' di norma sufficiente; se il fenomeno e' generalizzato, serve la diagnosi della causa prima del rifacimento."))

# ---------------- SICUREZZA E ANTISISMICA (6) ----------------
F.append(("sicurezza","La mia casa e' in zona sismica: cosa devo fare subito?",
"I primi controlli costano poco: verifica delle catene (assenti nella maggior parte delle case costruite prima degli anni 80), collegamento solai-muri, stato dei cordoli alla base dei muri, assenza di tamponature pericolose. Se l'edificio e' pre-1981 (prima delle prime norme sismiche serie), una valutazione sismica di livello 1 (VUL1) costa 500-1.500 € e le dice in che classe sismica si trova e cosa conviene fare. Gli interventi di miglioramento usufruiscono di detrazioni dedicate. L'informazione e' la prima protezione."))
F.append(("sicurezza","Il Bonus Sisma conviene ancora dopo il 2024?",
"Il c.d. Sismabonus ha subito modifiche: le aliquote sono state ridotte dal 110% (o 70-80% per i condomini) a livelli inferiori, e l'accesso e' subordinato a valutazioni sismiche e classi di rischio specifiche. Resta comunque una misura interessante per gli edifici piu' vulnerabili, soprattutto in zona ad alta pericolosita' sismica. La convenienza va valutata caso per caso: le consiglio di fare la VUL1 prima di qualsiasi decisione, cosi' sa esattamente da dove partire."))
F.append(("sicurezza","Cosa sono le catene antisismiche e quanto costano metterle?",
"Sono barre o cavi d'acciaio inseriti nei muri portanti, sopra le aperture, che legano i muri al solaio e tra loro: scaricano la spinta sismica fuori piano delle pareti e sono l'intervento piu' efficace sulle case in muratura. Il costo indicativo e' 15-30 €/m.l. di catena installata con fissaggi, quindi 1.500-3.000 € per un appartamento medio; con i miglioramenti si abbassa il rischio sismico di una classe. E' spesso il primo intervento antisismico raccomandato dalle valutazioni."))
F.append(("sicurezza","Quanto e' sicura una casa antisismica classe A?",
"Le classi di rischio sismico (A+, A, B, C, D, E, F) indicano il comportamento atteso sisma di progetto: una classe A supera gli stati limite ultimi con margini, mentre la F indica collasso previsto. Il passaggio da una classe inferiore ad A o B richiede interventi strutturali importanti (catene, rinforzi, ammorsamenti); anche una classe intermedia (C) migliora nettamente la sicurezza reale. Il riferimento e' il D.M. 17/01/2018 e le sue classi di rischio per gli edifici esistenti."))
F.append(("sicurezza","Quando serve la valutazione di rischio sismico per vendere casa?",
"La valutazione sismica non e' un requisito di vendita obbligatorio in senso assoluto, ma e' richiesta per accedere agli incentivi (Sismabonus e varianti) e sempre piu' spesso richiesta dai compratori o dalle banche per i mutui in zona sismica. Avere una VUL recente e un progetto di miglioramento valorizza l'immobile e ne dimostra la qualita' costruttiva. La sua assenza non blocca la vendita, ma la sua presenza e' un argomento di prezzo."))
F.append(("sicurezza","Cosa controllo prima di acquistare una casa in zona sismica?",
"Priorita': anno di costruzione (prima o dopo 1981/2003 per le norme sismiche), presenza di catene e cordoli, tipo di solai (laterocemento meglio di volte), eventuali lesioni da terremoto (valutare la storia sismica locale), qualita' dei muri (muratura piena meglio di tamponatura). Con 500-1.000 € una valutazione sismica rapida le dice in che classe si trova l'immobile e quali interventi servirebbero: e' la migliore assicurazione sull'acquisto."))

# ---------------- writer ----------------
os.makedirs('parsed', exist_ok=True)
meta = {
    "source": "faq_cliente_kimi",
    "license": "Sintesi didattica originale Kimi (pubblico dominio)",
    "commercial_ok": True,
    "attribution": "FAQ cliente a cura di Kimi - risposte da professionista edile",
    "url": "",
}
out = []
for i, (cat, domanda, risposta) in enumerate(F, 1):
    rec = dict(meta)
    rec.update({
        "id": f"FAQ-{i:03d}",
        "category": cat,
        "question": domanda,
        "answer": risposta,
    })
    out.append(rec)

path = 'parsed/faq_cliente_80.jsonl'
with open(path, 'w', encoding='utf-8') as f:
    for r in out:
        f.write(json.dumps(r, ensure_ascii=False) + '\n')
print(f"scritte {len(out)} FAQ -> {os.path.abspath(path)}")
