# -*- coding: utf-8 -*-
"""Giro 7: esami per TUTTI i corsi rimasti senza."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_esami_giro5 import gen

JOBS = [
    ("ROBOTICA_EDILIZIA_PACK", "ROBOTICA", 350),
    ("IMPIANTI_COMPLETA_PACK", "IMPIANTI_COMPLETA", 350),
    ("CAPOLAVORI_E_STORIA_OPERE_PACK", "CAPOLAVORI", 300),
    ("INGEGNERIA_STRUTTURALE_PACK", "STRUTTURE", 300),
    ("DIMENSIONAMENTO_TERMOTECNICO_PACK", "DIMENSIONAMENTO_TERMOTECNICO", 250),
    ("ARCHITETTURA_PACK", "ARCHITETTURA", 250),
    ("GEOMETRA_TOPOGRAFIA_ESTIMO_PACK", "GEOMETRA_ESTIMO", 250),
    ("GEOTECNICA_E_FONDAZIONI_PACK", "GEOTECNICA", 250),
    ("MASTER_DESIGN_PACK", "MASTER_DESIGN", 250),
    ("MACCHINE_TERMICHE_TECNOLOGIA_PACK", "MACCHINE_TERMICHE", 250),
    ("MASTER_IMPRESA_EDILE_PACK", "MASTER_IMPRESA", 250),
    ("FORMULARIO_STRUTTURE_PACK", "FORMULARIO_STRUTTURE", 250),
    ("COSTRUIRE_IN_LEGNO_PACK", "COSTRUZIONI_LEGNO", 220),
    ("COSTRUZIONI_SPECIALI_PACK", "COSTRUZIONI_SPECIALI", 220),
    ("MATERIALI_DEL_FUTURO_PACK", "MATERIALI_FUTURO", 220),
    ("SICUREZZA_ANTINCENDIO_ACCESSIBILITA_PACK", "SICUREZZA_ANTINCENDIO", 220),
    ("TETTI_E_COPERTURE_PACK", "TETTI_COPERTURE", 220),
    ("ENERGETICA_INCENTIVI_PACK", "ENERGETICA_INCENTIVI", 220),
    ("DIMENSIONAMENTO_FV_EOLICO_ACCUMULO_PACK", "DIMENSIONAMENTO_FV_EOLICO", 220),
    ("ACUSTICA_EDILIZIA_PACK", "ACUSTICA", 220),
    ("FORMULARIO_FISICA_IMPIANTI_PACK", "FORMULARIO_FISICA", 220),
    ("MATEMATICA_PER_COSTRUIRE_PACK", "MATEMATICA", 220),
    ("CONTABILITA_APPALTI_PACK", "CONTABILITA_APPALTI", 200),
    ("DATA_CENTER_E_CRITICAL_FACILITIES_PACK", "DATA_CENTER", 200),
    ("EDILIZIA_INDUSTRIALE_LOGISTICA_PACK", "EDILIZIA_INDUSTRIALE", 200),
    ("OSPEDALI_E_HEALTHCARE_PACK", "OSPEDALI", 200),
    ("PISCINE_E_WELLNESS_PACK", "PISCINE", 200),
    ("HOTEL_E_HOSPITALITY_TECNICO_PACK", "HOTEL", 200),
    ("CAD_BIM_PROGETTAZIONE_PACK", "CAD_BIM", 200),
    ("DESIGN_GUSTO_TENDENZE_PACK", "DESIGN_GUSTO", 200),
    ("INTERIOR_PROGETTAZIONE_TECNICA_PACK", "INTERIOR_TECNICO", 200),
    ("LEGISLAZIONE_PRIVATA_EDILIZIA_PACK", "LEGISLAZIONE_EDILIZIA", 200),
    ("INFRASTRUTTURE_VIARIE_PACK", "INFRASTRUTTURE", 180),
    ("REAL_ESTATE_PACK", "REAL_ESTATE", 180),
    ("URBANISTICA_TERRITORIO_PACK", "URBANISTICA", 180),
    ("VERDE_ARREDO_URBANO_PACK", "VERDE_URBANO", 180),
]
for pack, titolo, n in JOBS:
    gen(pack, titolo, n)
